import OddCycleBound.RegionII.Certificate.Coverage

/-! Deterministically generated by `emit_zone_c_chunks.py`. -/

namespace OddCycleBound.RegionII.Certificate

def zoneCChunk176 : BoxTree :=
  (.splitK (RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).1)).2)).2)).2
    (.splitE (RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).1)).2)).2)).2)).1
      (.splitK (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).1)).2)).2)).2)).1)).1
        (.splitE (RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).1)).2)).2)).2)).1)).1)).1
          (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).1)).2)).2)).2)).1)).1)).1)).1 (.cVerified 25))
          (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).1)).2)).2)).2)).1)).1)).1)).2 (.cVerified 24)))
        (.splitE (RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).1)).2)).2)).2)).1)).1)).2
          (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).1)).2)).2)).2)).1)).1)).2)).1 (.cVerified 24))
          (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).1)).2)).2)).2)).1)).1)).2)).2 (.cVerified 23))))
      (.splitK (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).1)).2)).2)).2)).1)).2
        (.leaf (RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).1)).2)).2)).2)).1)).2)).1 (.cVerified 23))
        (.leaf (RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).1)).2)).2)).2)).1)).2)).2 (.cVerified 23))))
    (.splitE (RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).1)).2)).2)).2)).2
      (.splitK (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).1)).2)).2)).2)).2)).1
        (.splitE (RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).1)).2)).2)).2)).2)).1)).1
          (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).1)).2)).2)).2)).2)).1)).1)).1 (.cVerified 24))
          (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).1)).2)).2)).2)).2)).1)).1)).2 (.cVerified 23)))
        (.splitE (RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).1)).2)).2)).2)).2)).1)).2
          (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).1)).2)).2)).2)).2)).1)).2)).1 (.cVerified 23))
          (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).1)).2)).2)).2)).2)).1)).2)).2 (.cVerified 22))))
      (.splitK (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).1)).2)).2)).2)).2)).2
        (.leaf (RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).1)).2)).2)).2)).2)).2)).1 (.cVerified 22))
        (.leaf (RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).1)).2)).2)).2)).2)).2)).2 (.cVerified 21)))))

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
theorem zoneCChunk176_valid :
    zoneCChunk176.validC (RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).1)).2)).2)).2 = true := by
  decide +kernel

def zoneCChunk177 : BoxTree :=
  (.splitK (RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).2)).1)).1
    (.splitE (RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).2)).1)).1)).1
      (.splitK (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).2)).1)).1)).1)).1
        (.splitE (RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).2)).1)).1)).1)).1)).1
          (.splitK (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).2)).1)).1)).1)).1)).1)).1
            (.splitE (RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).2)).1)).1)).1)).1)).1)).1)).1
              (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).2)).1)).1)).1)).1)).1)).1)).1)).1 (.cVerified 27))
              (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).2)).1)).1)).1)).1)).1)).1)).1)).2 (.cVerified 26)))
            (.leaf (RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).2)).1)).1)).1)).1)).1)).1)).2 (.cVerified 26)))
          (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).2)).1)).1)).1)).1)).1)).2 (.cVerified 26)))
        (.splitE (RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).2)).1)).1)).1)).1)).2
          (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).2)).1)).1)).1)).1)).2)).1 (.cSkip))
          (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).2)).1)).1)).1)).1)).2)).2 (.cVerified 24))))
      (.splitK (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).2)).1)).1)).1)).2
        (.splitE (RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).2)).1)).1)).1)).2)).1
          (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).2)).1)).1)).1)).2)).1)).1 (.cVerified 24))
          (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).2)).1)).1)).1)).2)).1)).2 (.cVerified 23)))
        (.splitE (RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).2)).1)).1)).1)).2)).2
          (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).2)).1)).1)).1)).2)).2)).1 (.cVerified 23))
          (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).2)).1)).1)).1)).2)).2)).2 (.cVerified 22)))))
    (.splitE (RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).2)).1)).1)).2
      (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).2)).1)).1)).2)).1 (.cSkip))
      (.splitK (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).2)).1)).1)).2)).2
        (.splitE (RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).2)).1)).1)).2)).2)).1
          (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).2)).1)).1)).2)).2)).1)).1 (.cVerified 21))
          (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).2)).1)).1)).2)).2)).1)).2 (.cVerified 20)))
        (.leaf (RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).2)).1)).1)).2)).2)).2 (.cVerified 20)))))

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
theorem zoneCChunk177_valid :
    zoneCChunk177.validC (RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).2)).1)).1 = true := by
  decide +kernel

def zoneCChunk178 : BoxTree :=
  (.splitK (RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).2)).1)).2
    (.splitE (RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).2)).1)).2)).1
      (.splitK (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).2)).1)).2)).1)).1
        (.splitE (RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).2)).1)).2)).1)).1)).1
          (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).2)).1)).2)).1)).1)).1)).1 (.cVerified 22))
          (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).2)).1)).2)).1)).1)).1)).2 (.cVerified 21)))
        (.leaf (RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).2)).1)).2)).1)).1)).2 (.cVerified 21)))
      (.splitK (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).2)).1)).2)).1)).2
        (.leaf (RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).2)).1)).2)).1)).2)).1 (.cVerified 20))
        (.leaf (RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).2)).1)).2)).1)).2)).2 (.cVerified 19))))
    (.splitE (RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).2)).1)).2)).2
      (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).2)).1)).2)).2)).1 (.cVerified 20))
      (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).2)).1)).2)).2)).2 (.cVerified 18))))

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
theorem zoneCChunk178_valid :
    zoneCChunk178.validC (RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).2)).1)).2 = true := by
  decide +kernel

def zoneCChunk179 : BoxTree :=
  (.splitE (RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).2)).2
    (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).2)).2)).1 (.cSkip))
    (.splitK (RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).2)).2)).2
      (.leaf (RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).2)).2)).2)).1 (.cVerified 18))
      (.leaf (RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).2)).2)).2)).2 (.cVerified 17))))

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
theorem zoneCChunk179_valid :
    zoneCChunk179.validC (RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).1)).2)).2 = true := by
  decide +kernel

def zoneCChunk180 : BoxTree :=
  (.leaf (RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).2 (.cSkip))

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
theorem zoneCChunk180_valid :
    zoneCChunk180.validC (RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).1)).2 = true := by
  decide +kernel

def zoneCChunk181 : BoxTree :=
  (.leaf (RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).2 (.cSkip))

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
theorem zoneCChunk181_valid :
    zoneCChunk181.validC (RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).1)).2 = true := by
  decide +kernel

def zoneCChunk182 : BoxTree :=
  (.leaf (RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).2 (.cSkip))

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
theorem zoneCChunk182_valid :
    zoneCChunk182.validC (RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).1)).2)).2 = true := by
  decide +kernel

def zoneCChunk183 : BoxTree :=
  (.splitK (RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).1
    (.splitK (RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).1)).1
      (.leaf (RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).1)).1)).1 (.cBottom))
      (.splitK (RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).1)).1)).2
        (.splitE (RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).1)).1)).2)).1
          (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).1)).1)).2)).1)).1 (.cVerified 52))
          (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).1)).1)).2)).1)).2 (.cVerified 53)))
        (.splitE (RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).1)).1)).2)).2
          (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).1)).1)).2)).2)).1 (.cVerified 39))
          (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).1)).1)).2)).2)).2 (.cVerified 40)))))
    (.splitK (RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).1)).2
      (.splitE (RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).1)).2)).1
        (.splitK (RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).1)).2)).1)).1
          (.leaf (RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).1)).2)).1)).1)).1 (.cVerified 33))
          (.splitE (RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).1)).2)).1)).1)).2
            (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).1)).2)).1)).1)).2)).1 (.cVerified 32))
            (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).1)).2)).1)).1)).2)).2 (.cVerified 32))))
        (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).1)).2)).1)).2 (.cVerified 27)))
      (.splitE (RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).1)).2)).2
        (.splitE (RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).1)).2)).2)).1
          (.splitK (RatBox.splitE ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).1)).2)).2)).1)).1
            (.leaf (RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).1)).2)).2)).1)).1)).1 (.cVerified 29))
            (.leaf (RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).1)).2)).2)).1)).1)).2 (.cVerified 27)))
          (.leaf (RatBox.splitE ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).1)).2)).2)).1)).2 (.cVerified 25)))
        (.splitK (RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).1)).2)).2)).2
          (.leaf (RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).1)).2)).2)).2)).1 (.cVerified 24))
          (.leaf (RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).1)).2)).2)).2)).2 (.cVerified 21))))))

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
theorem zoneCChunk183_valid :
    zoneCChunk183.validC (RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).1 = true := by
  decide +kernel

def zoneCChunk184 : BoxTree :=
  (.splitE (RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).2)).1
    (.splitK (RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).2)).1)).1
      (.splitE (RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).2)).1)).1)).1
        (.splitK (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).2)).1)).1)).1)).1
          (.splitE (RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).2)).1)).1)).1)).1)).1
            (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).2)).1)).1)).1)).1)).1)).1 (.cVerified 26))
            (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).2)).1)).1)).1)).1)).1)).2 (.cVerified 25)))
          (.splitE (RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).2)).1)).1)).1)).1)).2
            (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).2)).1)).1)).1)).1)).2)).1 (.cVerified 24))
            (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).2)).1)).1)).1)).1)).2)).2 (.cVerified 23))))
        (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).2)).1)).1)).1)).2 (.cVerified 22)))
      (.splitE (RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).2)).1)).1)).2
        (.splitE (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).2)).1)).1)).2)).1
          (.leaf (RatBox.splitE ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).2)).1)).1)).2)).1)).1 (.cVerified 23))
          (.leaf (RatBox.splitE ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).2)).1)).1)).2)).1)).2 (.cVerified 22)))
        (.splitK (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).2)).1)).1)).2)).2
          (.leaf (RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).2)).1)).1)).2)).2)).1 (.cVerified 21))
          (.leaf (RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).2)).1)).1)).2)).2)).2 (.cVerified 20)))))
    (.splitK (RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).2)).1)).2
      (.splitE (RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).2)).1)).2)).1
        (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).2)).1)).2)).1)).1 (.cVerified 20))
        (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).2)).1)).2)).1)).2 (.cVerified 20)))
      (.splitE (RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).2)).1)).2)).2
        (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).2)).1)).2)).2)).1 (.cVerified 18))
        (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).2)).1)).2)).2)).2 (.cVerified 17)))))

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
theorem zoneCChunk184_valid :
    zoneCChunk184.validC (RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).2)).1 = true := by
  decide +kernel

def zoneCChunk185 : BoxTree :=
  (.splitE (RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).2)).2
    (.splitE (RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).2)).2)).1
      (.splitK (RatBox.splitE ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).2)).2)).1)).1
        (.splitE (RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).2)).2)).1)).1)).1
          (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).2)).2)).1)).1)).1)).1 (.cVerified 22))
          (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).2)).2)).1)).1)).1)).2 (.cVerified 20)))
        (.splitE (RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).2)).2)).1)).1)).2
          (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).2)).2)).1)).1)).2)).1 (.cVerified 20))
          (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).2)).2)).1)).1)).2)).2 (.cVerified 19))))
      (.splitK (RatBox.splitE ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).2)).2)).1)).2
        (.splitE (RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).2)).2)).1)).2)).1
          (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).2)).2)).1)).2)).1)).1 (.cVerified 19))
          (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).2)).2)).1)).2)).1)).2 (.cVerified 18)))
        (.splitE (RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).2)).2)).1)).2)).2
          (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).2)).2)).1)).2)).2)).1 (.cVerified 18))
          (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).2)).2)).1)).2)).2)).2 (.cVerified 17)))))
    (.splitK (RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).2)).2)).2
      (.splitE (RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).2)).2)).2)).1
        (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).2)).2)).2)).1)).1 (.cVerified 17))
        (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).2)).2)).2)).1)).2 (.cVerified 16)))
      (.leaf (RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).2)).2)).2)).2 (.cVerified 16))))

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
theorem zoneCChunk185_valid :
    zoneCChunk185.validC (RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).1)).2)).2 = true := by
  decide +kernel

def zoneCChunk186 : BoxTree :=
  (.splitK (RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).2
    (.splitE (RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).2)).1
      (.splitK (RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).2)).1)).1
        (.splitE (RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).2)).1)).1)).1
          (.splitK (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).2)).1)).1)).1)).1
            (.splitE (RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).2)).1)).1)).1)).1)).1
              (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).2)).1)).1)).1)).1)).1)).1 (.cVerified 19))
              (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).2)).1)).1)).1)).1)).1)).2 (.cVerified 18)))
            (.leaf (RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).2)).1)).1)).1)).1)).2 (.cVerified 18)))
          (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).2)).1)).1)).1)).2 (.cVerified 17)))
        (.splitE (RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).2)).1)).1)).2
          (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).2)).1)).1)).2)).1 (.cVerified 17))
          (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).2)).1)).1)).2)).2 (.cVerified 15))))
      (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).2)).1)).2 (.cVerified 15)))
    (.splitE (RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).2)).2
      (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).2)).2)).1 (.cVerified 16))
      (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).2)).2)).2 (.cVerified 15))))

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
theorem zoneCChunk186_valid :
    zoneCChunk186.validC (RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).1)).2 = true := by
  decide +kernel

def zoneCChunk187 : BoxTree :=
  (.splitK (RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).2
    (.splitE (RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).2)).1
      (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).2)).1)).1 (.cVerified 15))
      (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).2)).1)).2 (.cVerified 15)))
    (.leaf (RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).2)).2 (.cVerified 15)))

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
theorem zoneCChunk187_valid :
    zoneCChunk187.validC (RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).1)).2 = true := by
  decide +kernel

def zoneCChunk188 : BoxTree :=
  (.leaf (RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).2 (.cVerified 15))

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
theorem zoneCChunk188_valid :
    zoneCChunk188.validC (RatBox.splitK ((RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).1)).2 = true := by
  decide +kernel

def zoneCChunk189 : BoxTree :=
  (.leaf (RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).2 (.cSkip))

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
theorem zoneCChunk189_valid :
    zoneCChunk189.validC (RatBox.splitK ((RatBox.splitE ((RatBox.splitE (zoneCRoot)).1)).2)).2 = true := by
  decide +kernel

def zoneCChunk190 : BoxTree :=
  (.splitK (RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE (zoneCRoot)).2)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1
    (.splitK (RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE (zoneCRoot)).2)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1
      (.leaf (RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE (zoneCRoot)).2)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1 (.cBottom))
      (.splitK (RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE (zoneCRoot)).2)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).2
        (.leaf (RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE (zoneCRoot)).2)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).2)).1 (.cVerified 50))
        (.splitE (RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE (zoneCRoot)).2)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).2)).2
          (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE (zoneCRoot)).2)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).2)).2)).1 (.cVerified 1716))
          (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE (zoneCRoot)).2)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).2)).2)).2 (.cVerified 62)))))
    (.splitK (RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE (zoneCRoot)).2)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).2
      (.splitE (RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE (zoneCRoot)).2)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).2)).1
        (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE (zoneCRoot)).2)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).2)).1)).1 (.cVerified 1145))
        (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE (zoneCRoot)).2)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).2)).1)).2 (.cVerified 39)))
      (.splitE (RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE (zoneCRoot)).2)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).2)).2
        (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE (zoneCRoot)).2)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).2)).2)).1 (.cVerified 859))
        (.splitK (RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE (zoneCRoot)).2)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).2)).2)).2
          (.leaf (RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE (zoneCRoot)).2)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).2)).2)).2)).1 (.cVerified 32))
          (.splitE (RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE (zoneCRoot)).2)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).2)).2)).2)).2
            (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE (zoneCRoot)).2)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).2)).2)).2)).2)).1 (.cVerified 852))
            (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE (zoneCRoot)).2)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).2)).2)).2)).2)).2 (.cVerified 34)))))))

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
theorem zoneCChunk190_valid :
    zoneCChunk190.validC (RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE (zoneCRoot)).2)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1 = true := by
  decide +kernel

def zoneCChunk191 : BoxTree :=
  (.splitE (RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE (zoneCRoot)).2)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).2)).1
    (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE (zoneCRoot)).2)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).2)).1)).1 (.cVerified 573))
    (.splitK (RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE (zoneCRoot)).2)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).2)).1)).2
      (.splitE (RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE (zoneCRoot)).2)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).2)).1)).2)).1
        (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE (zoneCRoot)).2)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).2)).1)).2)).1)).1 (.cVerified 681))
        (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE (zoneCRoot)).2)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).2)).1)).2)).1)).2 (.cVerified 25)))
      (.splitE (RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE (zoneCRoot)).2)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).2)).1)).2)).2
        (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE (zoneCRoot)).2)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).2)).1)).2)).2)).1 (.cVerified 568))
        (.splitK (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE (zoneCRoot)).2)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).2)).1)).2)).2)).2
          (.splitE (RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE (zoneCRoot)).2)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).2)).1)).2)).2)).2)).1
            (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE (zoneCRoot)).2)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).2)).1)).2)).2)).2)).1)).1 (.cVerified 484))
            (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE (zoneCRoot)).2)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).2)).1)).2)).2)).2)).1)).2 (.cVerified 24)))
          (.splitE (RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE (zoneCRoot)).2)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).2)).1)).2)).2)).2)).2
            (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE (zoneCRoot)).2)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).2)).1)).2)).2)).2)).2)).1 (.cVerified 443))
            (.splitK (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE (zoneCRoot)).2)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).2)).1)).2)).2)).2)).2)).2
              (.leaf (RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE (zoneCRoot)).2)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).2)).1)).2)).2)).2)).2)).2)).1 (.cVerified 23))
              (.splitE (RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE (zoneCRoot)).2)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).2)).1)).2)).2)).2)).2)).2)).2
                (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE (zoneCRoot)).2)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).2)).1)).2)).2)).2)).2)).2)).2)).1 (.cVerified 299))
                (.leaf (RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitE ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE (zoneCRoot)).2)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).2)).1)).2)).2)).2)).2)).2)).2)).2 (.cVerified 22)))))))))

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
theorem zoneCChunk191_valid :
    zoneCChunk191.validC (RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitK ((RatBox.splitE (zoneCRoot)).2)).1)).1)).1)).1)).1)).1)).1)).1)).1)).1)).2)).1 = true := by
  decide +kernel

end OddCycleBound.RegionII.Certificate
