import ApicesCommonness.Cycles.Foundation.Spectral.EigenSystem
import ApicesCommonness.Cycles.Foundation.Model.StepModel
import ApicesCommonness.Cycles.Foundation.FiniteBridge
import ApicesCommonness.Cycles.Host.Matrix
import ApicesCommonness.Cycles.Host.Spectral
import ApicesCommonness.Cycles.Host.Scalars
import ApicesCommonness.Cycles.Host.ScalarBounds
import ApicesCommonness.Cycles.Host.EvenCycle
import ApicesCommonness.Cycles.Host.Regression
import ApicesCommonness.Cycles.Conditional.Defs
import ApicesCommonness.Cycles.Conditional.Trace
import ApicesCommonness.Cycles.Conditional.Diamond
import ApicesCommonness.Cycles.Moments.Basic
import ApicesCommonness.Cycles.Moments.ApexLifting
import ApicesCommonness.Cycles.Finite.OneApex
import ApicesCommonness.Cycles.Finite.TwoApex
import ApicesCommonness.Cycles.Transfer
import ApicesCommonness.Cycles.Certificate.Mask
import ApicesCommonness.Cycles.Certificate.Rooted
import ApicesCommonness.Cycles.Certificate.Accum
import ApicesCommonness.Cycles.Certificate.LDL
import ApicesCommonness.Cycles.Certificate.Checker
import ApicesCommonness.Cycles.Certificate.Targets
import ApicesCommonness.Cycles.Certificate.Schema
import ApicesCommonness.Cycles.Certificate.Sound
import ApicesCommonness.Cycles.Certificate.Groups
import ApicesCommonness.Cycles.Certificate.Checks.Witness
import ApicesCommonness.Cycles.Certificate.Checks.MeanThree
import ApicesCommonness.Cycles.Certificate.Checks.Neg
import ApicesCommonness.Cycles.Certificate.Checks.Pos
import ApicesCommonness.Cycles.Certificate.Main
import ApicesCommonness.Cycles.Finite.ThreeApexGraphs
import ApicesCommonness.Cycles.Finite.ThreeApexMoments
import ApicesCommonness.Cycles.Finite.ThreeApexScalars
import ApicesCommonness.Cycles.Finite.ThreeApex
import ApicesCommonness.Cycles.Finite.AllApices
import ApicesCommonness.Cycles.Main
import ApicesCommonness.Cycles.Equality.Spectral
import ApicesCommonness.Cycles.Equality.Functionals
import ApicesCommonness.Cycles.Equality.CZero
import ApicesCommonness.Cycles.Equality.Main
import ApicesCommonness.Cycles.BlueprintNames

/-! Cycles: commonness of independent apices of even cycles, through fourth moments (paper §4). -/
