import Taeyoung.Methods.Atlas126.HighBoundaries
import Taeyoung.Methods.Atlas126.Corners
import Taeyoung.Methods.Bernstein.CheckedTensor

/-! Generated by `codes/generate_atlas126_contacts_checked.py`.
All polynomial identities and integer certificate tables are kernel checked. -/
set_option maxHeartbeats 10000000
set_option maxRecDepth 100000
set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false
set_option linter.unusedTactic false
open Finset
namespace Taeyoung.Methods.Atlas126
open Taeyoung.Methods.Bernstein


private noncomputable def llB (r y z : ℝ) : ℝ :=
  (2/729 : ℝ) * r ^ 4 * z ^ 2 +
    (-2/243 : ℝ) * r ^ 4 * z +
    (-2/243 : ℝ) * r ^ 4 +
    (47/729 : ℝ) * r ^ 3 * z +
    (-8/729 : ℝ) * r ^ 3 +
    (-5/243 : ℝ) * r ^ 2 * z +
    (40/243 : ℝ) * r ^ 2 +
    (-14/81 : ℝ) * r

private noncomputable def llA (r y z : ℝ) : ℝ :=
  (2/243 : ℝ) * r ^ 4 * y ^ 2 +
    (-14/729 : ℝ) * r ^ 4 * y +
    (2/243 : ℝ) * r ^ 4 * z +
    (8/729 : ℝ) * r ^ 4 +
    (-34/729 : ℝ) * r ^ 3 * y ^ 2 +
    (1/9 : ℝ) * r ^ 3 * y +
    (-2/81 : ℝ) * r ^ 3 * z ^ 2 +
    (2/729 : ℝ) * r ^ 3 * z +
    (-5/81 : ℝ) * r ^ 3 +
    (20/243 : ℝ) * r ^ 2 * y ^ 2 +
    (2/27 : ℝ) * r ^ 2 * y * z +
    (-67/243 : ℝ) * r ^ 2 * y +
    (-56/243 : ℝ) * r ^ 2 * z +
    (46/243 : ℝ) * r ^ 2 +
    (-10/81 : ℝ) * r * y ^ 2 +
    (5/9 : ℝ) * r * y +
    (4/27 : ℝ) * r * z +
    (-34/81 : ℝ) * r +
    (-1/3 : ℝ) * y +
    (1/3 : ℝ)

private def llACoeffTerms : List IntTerm := [
  ⟨0, 0, 0, (243 : ℤ)⟩,
  ⟨0, 1, 0, (-243 : ℤ)⟩,
  ⟨1, 0, 0, (-306 : ℤ)⟩,
  ⟨1, 0, 1, (108 : ℤ)⟩,
  ⟨1, 1, 0, (405 : ℤ)⟩,
  ⟨1, 2, 0, (-90 : ℤ)⟩,
  ⟨2, 0, 0, (138 : ℤ)⟩,
  ⟨2, 0, 1, (-168 : ℤ)⟩,
  ⟨2, 1, 0, (-201 : ℤ)⟩,
  ⟨2, 1, 1, (54 : ℤ)⟩,
  ⟨2, 2, 0, (60 : ℤ)⟩,
  ⟨3, 0, 0, (-45 : ℤ)⟩,
  ⟨3, 0, 1, (2 : ℤ)⟩,
  ⟨3, 0, 2, (-18 : ℤ)⟩,
  ⟨3, 1, 0, (81 : ℤ)⟩,
  ⟨3, 2, 0, (-34 : ℤ)⟩,
  ⟨4, 0, 0, (8 : ℤ)⟩,
  ⟨4, 0, 1, (6 : ℤ)⟩,
  ⟨4, 1, 0, (-14 : ℤ)⟩,
  ⟨4, 2, 0, (6 : ℤ)⟩]

private def llACoeffNumer (i j k : ℕ) : ℤ :=
  intSparseCoeff llACoeffTerms i j k

private def llACoeff (i j k : ℕ) : ℚ :=
  (llACoeffNumer i j k : ℚ) / 729

private theorem llACoeffExpansion (x d u : ℝ) :
    msum llACoeff 4 2 2 x d u = sparseEval (llACoeffTerms.map IntTerm.toRat) x d u / 729 := by
  have he : ∀ i ∈ range 5, ∀ j ∈ range 3, ∀ k ∈ range 3,
      llACoeffNumer i j k = intSparseCoeff llACoeffTerms i j k := by intros; rfl
  have hb : ∀ t ∈ llACoeffTerms, t.i ≤ 4 ∧ t.j ≤ 2 ∧ t.k ≤ 2 := by decide +kernel
  exact msum_intSparse_scaled llACoeffNumer llACoeffTerms 729 4 2 2 he hb x d u

private theorem llAExpansion (r y z : ℝ) :
    msum llACoeff 4 2 2 r y z = llA r y z := by
  rw [llACoeffExpansion]
  simp only [sparseEval, IntTerm.toRat, llACoeffTerms, llA,
    List.map_cons, List.map_nil, List.sum_cons, List.sum_nil]
  push_cast
  ring


private def llAInputData : IntTable :=
  (.node 22 (.node 11 (.node 5 (.node 2 (.node 1 (.leaf (243 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (-243 : ℤ))
    (.leaf (0 : ℤ)))))
    (.node 3 (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (-306 : ℤ))
    (.leaf (108 : ℤ))))))
    (.node 5 (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (405 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (-90 : ℤ)))))
    (.node 3 (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (138 : ℤ))))
    (.node 1 (.leaf (-168 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (-201 : ℤ)))))))
    (.node 11 (.node 5 (.node 2 (.node 1 (.leaf (54 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (60 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))))
    (.node 3 (.node 1 (.leaf (-45 : ℤ))
    (.node 1 (.leaf (2 : ℤ))
    (.leaf (-18 : ℤ))))
    (.node 1 (.leaf (81 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))))
    (.node 6 (.node 3 (.node 1 (.leaf (-34 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 1 (.leaf (8 : ℤ))
    (.node 1 (.leaf (6 : ℤ))
    (.leaf (0 : ℤ)))))
    (.node 3 (.node 1 (.leaf (-14 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 1 (.leaf (6 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))))))

private def llAInputNumer (i j k : ℕ) : ℤ :=
  llAInputData.get ((i * 3 + j) * 3 + k)

private def llAInput (i j k : ℕ) : ℚ :=
  (llAInputNumer i j k : ℚ) / 729

private theorem llAInputNumerCorrect :
    ∀ i ∈ range 5, ∀ j ∈ range 3, ∀ k ∈ range 3,
      llAInputNumer i j k = llACoeffNumer i j k := by
  decide +kernel

private theorem llAInputCorrect :
    ∀ i ∈ range 5, ∀ j ∈ range 3, ∀ k ∈ range 3,
      llAInput i j k = llACoeff i j k := by
  intro i hi j hj k hk
  exact congrArg (fun v : ℤ => (v : ℚ)/729)
    (llAInputNumerCorrect i hi j hj k hk)

private def llAW1Data : IntTable :=
  (.node 12 (.node 6 (.node 3 (.node 1 (.leaf (1 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (4 : ℤ)))))
    (.node 3 (.node 1 (.leaf (1 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (6 : ℤ))
    (.leaf (3 : ℤ))))))
    (.node 6 (.node 3 (.node 1 (.leaf (1 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 1 (.leaf (4 : ℤ))
    (.node 1 (.leaf (3 : ℤ))
    (.leaf (2 : ℤ)))))
    (.node 3 (.node 1 (.leaf (1 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (1 : ℤ))))
    (.node 2 (.node 1 (.leaf (1 : ℤ))
    (.leaf (1 : ℤ)))
    (.node 1 (.leaf (1 : ℤ))
    (.leaf (1 : ℤ)))))))

private def llAW1Numer (k i : ℕ) : ℤ :=
  llAW1Data.get (k * 5 + i)

private def llAW1 (k i : ℕ) : ℚ :=
  (llAW1Numer k i : ℚ) / 1

private theorem llAW1NumerCorrect :
    ∀ k ∈ range 5, ∀ i ∈ range 5,
      llAW1Numer k i = intTransWeight 4 (0) 1 1 k i := by
  decide +kernel

private theorem llAW1Correct : WeightsCorrect 4 (0 : ℚ) (1 : ℚ) llAW1 := by
  intro k hk i hi
  have he := intTransWeight_cast 4 (0) 1 1 k i
    (by simp only [mem_range] at hi; omega) (by norm_num)
  rw [← llAW1NumerCorrect k hk i hi] at he
  norm_num only [show (1 : ℚ)^4 = 1 by norm_num,
    show (0 : ℚ)/1 = 0 by norm_num,
    show (1 : ℚ)/1 = 1 by norm_num] at he
  simpa only [llAW1, neg_div] using he

private def llAW2Data : IntTable :=
  (.node 4 (.node 2 (.node 1 (.leaf (16 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (32 : ℤ))))
    (.node 2 (.node 1 (.leaf (4 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (16 : ℤ))
    (.node 1 (.leaf (4 : ℤ))
    (.leaf (1 : ℤ))))))

private def llAW2Numer (k i : ℕ) : ℤ :=
  llAW2Data.get (k * 3 + i)

private def llAW2 (k i : ℕ) : ℚ :=
  (llAW2Numer k i : ℚ) / 16

private theorem llAW2NumerCorrect :
    ∀ k ∈ range 3, ∀ i ∈ range 3,
      llAW2Numer k i = intTransWeight 2 (0) 1 4 k i := by
  decide +kernel

private theorem llAW2Correct : WeightsCorrect 2 (0 : ℚ) ((1/4) : ℚ) llAW2 := by
  intro k hk i hi
  have he := intTransWeight_cast 2 (0) 1 4 k i
    (by simp only [mem_range] at hi; omega) (by norm_num)
  rw [← llAW2NumerCorrect k hk i hi] at he
  norm_num only [show (4 : ℚ)^2 = 16 by norm_num,
    show (0 : ℚ)/4 = 0 by norm_num,
    show (1 : ℚ)/4 = (1/4) by norm_num] at he
  simpa only [llAW2, neg_div] using he

private def llAW3Data : IntTable :=
  (.node 4 (.node 2 (.node 1 (.leaf (16 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (32 : ℤ))))
    (.node 2 (.node 1 (.leaf (4 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (16 : ℤ))
    (.node 1 (.leaf (4 : ℤ))
    (.leaf (1 : ℤ))))))

private def llAW3Numer (k i : ℕ) : ℤ :=
  llAW3Data.get (k * 3 + i)

private def llAW3 (k i : ℕ) : ℚ :=
  (llAW3Numer k i : ℚ) / 16

private theorem llAW3NumerCorrect :
    ∀ k ∈ range 3, ∀ i ∈ range 3,
      llAW3Numer k i = intTransWeight 2 (0) 1 4 k i := by
  decide +kernel

private theorem llAW3Correct : WeightsCorrect 2 (0 : ℚ) ((1/4) : ℚ) llAW3 := by
  intro k hk i hi
  have he := intTransWeight_cast 2 (0) 1 4 k i
    (by simp only [mem_range] at hi; omega) (by norm_num)
  rw [← llAW3NumerCorrect k hk i hi] at he
  norm_num only [show (4 : ℚ)^2 = 16 by norm_num,
    show (0 : ℚ)/4 = 0 by norm_num,
    show (1 : ℚ)/4 = (1/4) by norm_num] at he
  simpa only [llAW3, neg_div] using he

private def llAS1Data : IntTable :=
  (.node 22 (.node 11 (.node 5 (.node 2 (.node 1 (.leaf (243 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (-243 : ℤ))
    (.leaf (0 : ℤ)))))
    (.node 3 (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (666 : ℤ))
    (.leaf (108 : ℤ))))))
    (.node 5 (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (-567 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (-90 : ℤ)))))
    (.node 3 (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (678 : ℤ))))
    (.node 1 (.leaf (156 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (-444 : ℤ)))))))
    (.node 11 (.node 5 (.node 2 (.node 1 (.leaf (54 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (-210 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))))
    (.node 3 (.node 1 (.leaf (285 : ℤ))
    (.node 1 (.leaf (-10 : ℤ))
    (.leaf (-18 : ℤ))))
    (.node 1 (.leaf (-78 : ℤ))
    (.node 1 (.leaf (108 : ℤ))
    (.leaf (0 : ℤ))))))
    (.node 6 (.node 3 (.node 1 (.leaf (-184 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 1 (.leaf (38 : ℤ))
    (.node 1 (.leaf (-52 : ℤ))
    (.leaf (-18 : ℤ)))))
    (.node 3 (.node 1 (.leaf (28 : ℤ))
    (.node 1 (.leaf (54 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 1 (.leaf (-58 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))))))

private def llAS1Numer (i j k : ℕ) : ℤ :=
  llAS1Data.get ((i * 3 + j) * 3 + k)

private def llAS1 (i j k : ℕ) : ℚ :=
  (llAS1Numer i j k : ℚ) / 729

private theorem llAS1NumerCorrect :
    ∀ h ∈ range 5, ∀ j ∈ range 3, ∀ k ∈ range 3,
      llAS1Numer h j k = ∑ i ∈ range 5, llAInputNumer i j k * llAW1Numer h i := by
  decide +kernel

private theorem llAS1Correct : Axis1Correct 4 2 2 llAW1 llAInput llAS1 := by
  intro h hh j hj k hk
  have he := scaled_dot_eq (fun i => llAInputNumer i j k) (llAW1Numer h) (llAS1Numer h j k) 729 1 4
    (llAS1NumerCorrect h hh j hj k hk)
  norm_num only [show (729 : ℚ)*1 = 729 by norm_num] at he
  exact he

private def llAS2Data : IntTable :=
  (.node 22 (.node 11 (.node 5 (.node 2 (.node 1 (.leaf (3888 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (6804 : ℤ))
    (.leaf (0 : ℤ)))))
    (.node 3 (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (2916 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (10656 : ℤ))
    (.leaf (1728 : ℤ))))))
    (.node 5 (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (19044 : ℤ)))
    (.node 1 (.leaf (3456 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (8298 : ℤ)))))
    (.node 3 (.node 1 (.leaf (1728 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (10848 : ℤ))))
    (.node 1 (.leaf (2496 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (19920 : ℤ)))))))
    (.node 11 (.node 5 (.node 2 (.node 1 (.leaf (5208 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (8862 : ℤ))
    (.node 1 (.leaf (2712 : ℤ))
    (.leaf (0 : ℤ)))))
    (.node 3 (.node 1 (.leaf (4560 : ℤ))
    (.node 1 (.leaf (-160 : ℤ))
    (.leaf (-288 : ℤ))))
    (.node 1 (.leaf (8808 : ℤ))
    (.node 1 (.leaf (112 : ℤ))
    (.leaf (-576 : ℤ))))))
    (.node 6 (.node 3 (.node 1 (.leaf (4064 : ℤ))
    (.node 1 (.leaf (272 : ℤ))
    (.leaf (-288 : ℤ))))
    (.node 1 (.leaf (608 : ℤ))
    (.node 1 (.leaf (-832 : ℤ))
    (.leaf (-288 : ℤ)))))
    (.node 3 (.node 1 (.leaf (1328 : ℤ))
    (.node 1 (.leaf (-1448 : ℤ))
    (.leaf (-576 : ℤ))))
    (.node 1 (.leaf (662 : ℤ))
    (.node 1 (.leaf (-616 : ℤ))
    (.leaf (-288 : ℤ))))))))

private def llAS2Numer (i j k : ℕ) : ℤ :=
  llAS2Data.get ((i * 3 + j) * 3 + k)

private def llAS2 (i j k : ℕ) : ℚ :=
  (llAS2Numer i j k : ℚ) / 11664

private theorem llAS2NumerCorrect :
    ∀ k ∈ range 5, ∀ j ∈ range 3, ∀ h ∈ range 3,
      llAS2Numer k j h = ∑ i ∈ range 3, llAS1Numer k i h * llAW2Numer j i := by
  decide +kernel

private theorem llAS2Correct : Axis2Correct 4 2 2 llAW2 llAS1 llAS2 := by
  intro k hk j hj h hh
  have he := scaled_dot_eq (fun i => llAS1Numer k i h) (llAW2Numer j) (llAS2Numer k j h) 729 16 2
    (llAS2NumerCorrect k hk j hj h hh)
  norm_num only [show (729 : ℚ)*16 = 11664 by norm_num] at he
  exact he

private def llAS3Data : IntTable :=
  (.node 22 (.node 11 (.node 5 (.node 2 (.node 1 (.leaf (62208 : ℤ))
    (.leaf (124416 : ℤ)))
    (.node 1 (.leaf (62208 : ℤ))
    (.node 1 (.leaf (108864 : ℤ))
    (.leaf (217728 : ℤ)))))
    (.node 3 (.node 1 (.leaf (108864 : ℤ))
    (.node 1 (.leaf (46656 : ℤ))
    (.leaf (93312 : ℤ))))
    (.node 1 (.leaf (46656 : ℤ))
    (.node 1 (.leaf (170496 : ℤ))
    (.leaf (347904 : ℤ))))))
    (.node 5 (.node 2 (.node 1 (.leaf (177408 : ℤ))
    (.leaf (304704 : ℤ)))
    (.node 1 (.leaf (623232 : ℤ))
    (.node 1 (.leaf (318528 : ℤ))
    (.leaf (132768 : ℤ)))))
    (.node 3 (.node 1 (.leaf (272448 : ℤ))
    (.node 1 (.leaf (139680 : ℤ))
    (.leaf (173568 : ℤ))))
    (.node 1 (.leaf (357120 : ℤ))
    (.node 1 (.leaf (183552 : ℤ))
    (.leaf (318720 : ℤ)))))))
    (.node 11 (.node 5 (.node 2 (.node 1 (.leaf (658272 : ℤ))
    (.leaf (339552 : ℤ)))
    (.node 1 (.leaf (141792 : ℤ))
    (.node 1 (.leaf (294432 : ℤ))
    (.leaf (152640 : ℤ)))))
    (.node 3 (.node 1 (.leaf (72960 : ℤ))
    (.node 1 (.leaf (145280 : ℤ))
    (.leaf (72032 : ℤ))))
    (.node 1 (.leaf (140928 : ℤ))
    (.node 1 (.leaf (282304 : ℤ))
    (.leaf (140800 : ℤ))))))
    (.node 6 (.node 3 (.node 1 (.leaf (65024 : ℤ))
    (.node 1 (.leaf (131136 : ℤ))
    (.leaf (65824 : ℤ))))
    (.node 1 (.leaf (9728 : ℤ))
    (.node 1 (.leaf (16128 : ℤ))
    (.leaf (6112 : ℤ)))))
    (.node 3 (.node 1 (.leaf (21248 : ℤ))
    (.node 1 (.leaf (36704 : ℤ))
    (.leaf (14880 : ℤ))))
    (.node 1 (.leaf (10592 : ℤ))
    (.node 1 (.leaf (18720 : ℤ))
    (.leaf (7840 : ℤ))))))))

private def llAS3Numer (i j k : ℕ) : ℤ :=
  llAS3Data.get ((i * 3 + j) * 3 + k)

private def llAS3 (i j k : ℕ) : ℚ :=
  (llAS3Numer i j k : ℚ) / 186624

private theorem llAS3NumerCorrect :
    ∀ k ∈ range 5, ∀ j ∈ range 3, ∀ h ∈ range 3,
      llAS3Numer k j h = ∑ i ∈ range 3, llAS2Numer k j i * llAW3Numer h i := by
  decide +kernel

private theorem llAS3Correct : Axis3Correct 4 2 2 llAW3 llAS2 llAS3 := by
  intro k hk j hj h hh
  have he := scaled_dot_eq (fun i => llAS2Numer k j i) (llAW3Numer h) (llAS3Numer k j h) 11664 16 2
    (llAS3NumerCorrect k hk j hj h hh)
  norm_num only [show (11664 : ℚ)*16 = 186624 by norm_num] at he
  exact he

private theorem llANumerSigns :
    ∀ i ∈ range 5, ∀ j ∈ range 3, ∀ k ∈ range 3,
      0 ≤ llAS3Numer i j k := by
  decide +kernel

private theorem llASigns :
    ∀ i ∈ range 5, ∀ j ∈ range 3, ∀ k ∈ range 3,
      0 ≤ llAS3 i j k := by
  intro i hi j hj k hk
  apply div_nonneg
  · exact_mod_cast llANumerSigns i hi j hj k hk
  · norm_num


private theorem llACertificate :
    ∀ i ∈ range 5, ∀ j ∈ range 3, ∀ k ∈ range 3,
      0 ≤ trans3 llACoeff 4 2 2 (0 : ℚ) (1 : ℚ) (0 : ℚ) ((1/4) : ℚ) (0 : ℚ) ((1/4) : ℚ) i j k := by
  have exactTable := checked_trans3 llACoeff llAS1 llAS2 llAS3 4 2 2 (0 : ℚ) (1 : ℚ) (0 : ℚ) ((1/4) : ℚ) (0 : ℚ) ((1/4) : ℚ) llAW1 llAW2 llAW3
    llAW1Correct llAW2Correct llAW3Correct
    (axis1Correct_of_table llAInputCorrect llAS1Correct) llAS2Correct llAS3Correct
  intro i hi j hj k hk
  rw [← exactTable i hi j hj k hk]
  exact llASigns i hi j hj k hk

private theorem llA_nonneg {r y z : ℝ}
    (hr0 : (0 : ℝ) ≤ r) (hr1 : r ≤ (1 : ℝ))
    (hy0 : (0 : ℝ) ≤ y) (hy1 : y ≤ (1/4 : ℝ))
    (hz0 : (0 : ℝ) ≤ z) (hz1 : z ≤ (1/4 : ℝ)) : 0 ≤ llA r y z := by
  have h := msum_nonneg_on_box llACoeff 4 2 2 (x := r) (y := y) (z := z)
    (by norm_num) (by norm_num) (by norm_num)
    (by push_cast; linarith) (by push_cast; linarith)
    (by push_cast; linarith) (by push_cast; linarith)
    (by push_cast; linarith) (by push_cast; linarith) llACertificate
  rwa [llAExpansion] at h


private noncomputable def llC (r y z : ℝ) : ℝ :=
  (-2/729 : ℝ) * r ^ 4 * z +
    (2/243 : ℝ) * r ^ 4 +
    (-2/729 : ℝ) * r ^ 3 * z +
    (-23/729 : ℝ) * r ^ 3 +
    (4/243 : ℝ) * r ^ 2 +
    (1/81 : ℝ) * r

private def llCCoeffTerms : List IntTerm := [
  ⟨1, 0, 0, (9 : ℤ)⟩,
  ⟨2, 0, 0, (12 : ℤ)⟩,
  ⟨3, 0, 0, (-23 : ℤ)⟩,
  ⟨3, 0, 1, (-2 : ℤ)⟩,
  ⟨4, 0, 0, (6 : ℤ)⟩,
  ⟨4, 0, 1, (-2 : ℤ)⟩]

private def llCCoeffNumer (i j k : ℕ) : ℤ :=
  intSparseCoeff llCCoeffTerms i j k

private def llCCoeff (i j k : ℕ) : ℚ :=
  (llCCoeffNumer i j k : ℚ) / 729

private theorem llCCoeffExpansion (x d u : ℝ) :
    msum llCCoeff 4 0 1 x d u = sparseEval (llCCoeffTerms.map IntTerm.toRat) x d u / 729 := by
  have he : ∀ i ∈ range 5, ∀ j ∈ range 1, ∀ k ∈ range 2,
      llCCoeffNumer i j k = intSparseCoeff llCCoeffTerms i j k := by intros; rfl
  have hb : ∀ t ∈ llCCoeffTerms, t.i ≤ 4 ∧ t.j ≤ 0 ∧ t.k ≤ 1 := by decide +kernel
  exact msum_intSparse_scaled llCCoeffNumer llCCoeffTerms 729 4 0 1 he hb x d u

private theorem llCExpansion (r y z : ℝ) :
    msum llCCoeff 4 0 1 r y z = llC r y z := by
  rw [llCCoeffExpansion]
  simp only [sparseEval, IntTerm.toRat, llCCoeffTerms, llC,
    List.map_cons, List.map_nil, List.sum_cons, List.sum_nil]
  push_cast
  ring


private def llCInputData : IntTable :=
  (.node 5 (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (9 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (12 : ℤ)))))
    (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (-23 : ℤ)))
    (.node 1 (.leaf (-2 : ℤ))
    (.node 1 (.leaf (6 : ℤ))
    (.leaf (-2 : ℤ))))))

private def llCInputNumer (i j k : ℕ) : ℤ :=
  llCInputData.get ((i * 1 + j) * 2 + k)

private def llCInput (i j k : ℕ) : ℚ :=
  (llCInputNumer i j k : ℚ) / 729

private theorem llCInputNumerCorrect :
    ∀ i ∈ range 5, ∀ j ∈ range 1, ∀ k ∈ range 2,
      llCInputNumer i j k = llCCoeffNumer i j k := by
  decide +kernel

private theorem llCInputCorrect :
    ∀ i ∈ range 5, ∀ j ∈ range 1, ∀ k ∈ range 2,
      llCInput i j k = llCCoeff i j k := by
  intro i hi j hj k hk
  exact congrArg (fun v : ℤ => (v : ℚ)/729)
    (llCInputNumerCorrect i hi j hj k hk)

private def llCW1Data : IntTable :=
  (.node 12 (.node 6 (.node 3 (.node 1 (.leaf (1 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (4 : ℤ)))))
    (.node 3 (.node 1 (.leaf (1 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (6 : ℤ))
    (.leaf (3 : ℤ))))))
    (.node 6 (.node 3 (.node 1 (.leaf (1 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 1 (.leaf (4 : ℤ))
    (.node 1 (.leaf (3 : ℤ))
    (.leaf (2 : ℤ)))))
    (.node 3 (.node 1 (.leaf (1 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (1 : ℤ))))
    (.node 2 (.node 1 (.leaf (1 : ℤ))
    (.leaf (1 : ℤ)))
    (.node 1 (.leaf (1 : ℤ))
    (.leaf (1 : ℤ)))))))

private def llCW1Numer (k i : ℕ) : ℤ :=
  llCW1Data.get (k * 5 + i)

private def llCW1 (k i : ℕ) : ℚ :=
  (llCW1Numer k i : ℚ) / 1

private theorem llCW1NumerCorrect :
    ∀ k ∈ range 5, ∀ i ∈ range 5,
      llCW1Numer k i = intTransWeight 4 (0) 1 1 k i := by
  decide +kernel

private theorem llCW1Correct : WeightsCorrect 4 (0 : ℚ) (1 : ℚ) llCW1 := by
  intro k hk i hi
  have he := intTransWeight_cast 4 (0) 1 1 k i
    (by simp only [mem_range] at hi; omega) (by norm_num)
  rw [← llCW1NumerCorrect k hk i hi] at he
  norm_num only [show (1 : ℚ)^4 = 1 by norm_num,
    show (0 : ℚ)/1 = 0 by norm_num,
    show (1 : ℚ)/1 = 1 by norm_num] at he
  simpa only [llCW1, neg_div] using he

private def llCW2Data : IntTable :=
  (.leaf (1 : ℤ))

private def llCW2Numer (k i : ℕ) : ℤ :=
  llCW2Data.get (k * 1 + i)

private def llCW2 (k i : ℕ) : ℚ :=
  (llCW2Numer k i : ℚ) / 1

private theorem llCW2NumerCorrect :
    ∀ k ∈ range 1, ∀ i ∈ range 1,
      llCW2Numer k i = intTransWeight 0 (0) 1 4 k i := by
  decide +kernel

private theorem llCW2Correct : WeightsCorrect 0 (0 : ℚ) ((1/4) : ℚ) llCW2 := by
  intro k hk i hi
  have he := intTransWeight_cast 0 (0) 1 4 k i
    (by simp only [mem_range] at hi; omega) (by norm_num)
  rw [← llCW2NumerCorrect k hk i hi] at he
  norm_num only [show (4 : ℚ)^0 = 1 by norm_num,
    show (0 : ℚ)/4 = 0 by norm_num,
    show (1 : ℚ)/4 = (1/4) by norm_num] at he
  simpa only [llCW2, neg_div] using he

private def llCW3Data : IntTable :=
  (.node 2 (.node 1 (.leaf (4 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (4 : ℤ))
    (.leaf (1 : ℤ))))

private def llCW3Numer (k i : ℕ) : ℤ :=
  llCW3Data.get (k * 2 + i)

private def llCW3 (k i : ℕ) : ℚ :=
  (llCW3Numer k i : ℚ) / 4

private theorem llCW3NumerCorrect :
    ∀ k ∈ range 2, ∀ i ∈ range 2,
      llCW3Numer k i = intTransWeight 1 (0) 1 4 k i := by
  decide +kernel

private theorem llCW3Correct : WeightsCorrect 1 (0 : ℚ) ((1/4) : ℚ) llCW3 := by
  intro k hk i hi
  have he := intTransWeight_cast 1 (0) 1 4 k i
    (by simp only [mem_range] at hi; omega) (by norm_num)
  rw [← llCW3NumerCorrect k hk i hi] at he
  norm_num only [show (4 : ℚ)^1 = 4 by norm_num,
    show (0 : ℚ)/4 = 0 by norm_num,
    show (1 : ℚ)/4 = (1/4) by norm_num] at he
  simpa only [llCW3, neg_div] using he

private def llCS1Data : IntTable :=
  (.node 5 (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (9 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (39 : ℤ)))))
    (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (28 : ℤ)))
    (.node 1 (.leaf (-2 : ℤ))
    (.node 1 (.leaf (4 : ℤ))
    (.leaf (-4 : ℤ))))))

private def llCS1Numer (i j k : ℕ) : ℤ :=
  llCS1Data.get ((i * 1 + j) * 2 + k)

private def llCS1 (i j k : ℕ) : ℚ :=
  (llCS1Numer i j k : ℚ) / 729

private theorem llCS1NumerCorrect :
    ∀ h ∈ range 5, ∀ j ∈ range 1, ∀ k ∈ range 2,
      llCS1Numer h j k = ∑ i ∈ range 5, llCInputNumer i j k * llCW1Numer h i := by
  decide +kernel

private theorem llCS1Correct : Axis1Correct 4 0 1 llCW1 llCInput llCS1 := by
  intro h hh j hj k hk
  have he := scaled_dot_eq (fun i => llCInputNumer i j k) (llCW1Numer h) (llCS1Numer h j k) 729 1 4
    (llCS1NumerCorrect h hh j hj k hk)
  norm_num only [show (729 : ℚ)*1 = 729 by norm_num] at he
  exact he

private def llCS2Data : IntTable :=
  (.node 5 (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (9 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (39 : ℤ)))))
    (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (28 : ℤ)))
    (.node 1 (.leaf (-2 : ℤ))
    (.node 1 (.leaf (4 : ℤ))
    (.leaf (-4 : ℤ))))))

private def llCS2Numer (i j k : ℕ) : ℤ :=
  llCS2Data.get ((i * 1 + j) * 2 + k)

private def llCS2 (i j k : ℕ) : ℚ :=
  (llCS2Numer i j k : ℚ) / 729

private theorem llCS2NumerCorrect :
    ∀ k ∈ range 5, ∀ j ∈ range 1, ∀ h ∈ range 2,
      llCS2Numer k j h = ∑ i ∈ range 1, llCS1Numer k i h * llCW2Numer j i := by
  decide +kernel

private theorem llCS2Correct : Axis2Correct 4 0 1 llCW2 llCS1 llCS2 := by
  intro k hk j hj h hh
  have he := scaled_dot_eq (fun i => llCS1Numer k i h) (llCW2Numer j) (llCS2Numer k j h) 729 1 0
    (llCS2NumerCorrect k hk j hj h hh)
  norm_num only [show (729 : ℚ)*1 = 729 by norm_num] at he
  exact he

private def llCS3Data : IntTable :=
  (.node 5 (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (36 : ℤ))
    (.node 1 (.leaf (36 : ℤ))
    (.leaf (156 : ℤ)))))
    (.node 2 (.node 1 (.leaf (156 : ℤ))
    (.leaf (112 : ℤ)))
    (.node 1 (.leaf (110 : ℤ))
    (.node 1 (.leaf (16 : ℤ))
    (.leaf (12 : ℤ))))))

private def llCS3Numer (i j k : ℕ) : ℤ :=
  llCS3Data.get ((i * 1 + j) * 2 + k)

private def llCS3 (i j k : ℕ) : ℚ :=
  (llCS3Numer i j k : ℚ) / 2916

private theorem llCS3NumerCorrect :
    ∀ k ∈ range 5, ∀ j ∈ range 1, ∀ h ∈ range 2,
      llCS3Numer k j h = ∑ i ∈ range 2, llCS2Numer k j i * llCW3Numer h i := by
  decide +kernel

private theorem llCS3Correct : Axis3Correct 4 0 1 llCW3 llCS2 llCS3 := by
  intro k hk j hj h hh
  have he := scaled_dot_eq (fun i => llCS2Numer k j i) (llCW3Numer h) (llCS3Numer k j h) 729 4 1
    (llCS3NumerCorrect k hk j hj h hh)
  norm_num only [show (729 : ℚ)*4 = 2916 by norm_num] at he
  exact he

private theorem llCNumerSigns :
    ∀ i ∈ range 5, ∀ j ∈ range 1, ∀ k ∈ range 2,
      0 ≤ llCS3Numer i j k := by
  decide +kernel

private theorem llCSigns :
    ∀ i ∈ range 5, ∀ j ∈ range 1, ∀ k ∈ range 2,
      0 ≤ llCS3 i j k := by
  intro i hi j hj k hk
  apply div_nonneg
  · exact_mod_cast llCNumerSigns i hi j hj k hk
  · norm_num


private theorem llCCertificate :
    ∀ i ∈ range 5, ∀ j ∈ range 1, ∀ k ∈ range 2,
      0 ≤ trans3 llCCoeff 4 0 1 (0 : ℚ) (1 : ℚ) (0 : ℚ) ((1/4) : ℚ) (0 : ℚ) ((1/4) : ℚ) i j k := by
  have exactTable := checked_trans3 llCCoeff llCS1 llCS2 llCS3 4 0 1 (0 : ℚ) (1 : ℚ) (0 : ℚ) ((1/4) : ℚ) (0 : ℚ) ((1/4) : ℚ) llCW1 llCW2 llCW3
    llCW1Correct llCW2Correct llCW3Correct
    (axis1Correct_of_table llCInputCorrect llCS1Correct) llCS2Correct llCS3Correct
  intro i hi j hj k hk
  rw [← exactTable i hi j hj k hk]
  exact llCSigns i hi j hj k hk

private theorem llC_nonneg {r y z : ℝ}
    (hr0 : (0 : ℝ) ≤ r) (hr1 : r ≤ (1 : ℝ))
    (hy0 : (0 : ℝ) ≤ y) (hy1 : y ≤ (1/4 : ℝ))
    (hz0 : (0 : ℝ) ≤ z) (hz1 : z ≤ (1/4 : ℝ)) : 0 ≤ llC r y z := by
  have h := msum_nonneg_on_box llCCoeff 4 0 1 (x := r) (y := y) (z := z)
    (by norm_num) (by norm_num) (by norm_num)
    (by push_cast; linarith) (by push_cast; linarith)
    (by push_cast; linarith) (by push_cast; linarith)
    (by push_cast; linarith) (by push_cast; linarith) llCCertificate
  rwa [llCExpansion] at h


private noncomputable def llDet (r y z : ℝ) : ℝ :=
  (-16/177147 : ℝ) * r ^ 8 * y ^ 2 * z +
    (16/59049 : ℝ) * r ^ 8 * y ^ 2 +
    (112/531441 : ℝ) * r ^ 8 * y * z +
    (-112/177147 : ℝ) * r ^ 8 * y +
    (-4/531441 : ℝ) * r ^ 8 * z ^ 4 +
    (8/177147 : ℝ) * r ^ 8 * z ^ 3 +
    (-20/177147 : ℝ) * r ^ 8 * z ^ 2 +
    (8/531441 : ℝ) * r ^ 8 * z +
    (52/177147 : ℝ) * r ^ 8 +
    (224/531441 : ℝ) * r ^ 7 * y ^ 2 * z +
    (-152/59049 : ℝ) * r ^ 7 * y ^ 2 +
    (-536/531441 : ℝ) * r ^ 7 * y * z +
    (3232/531441 : ℝ) * r ^ 7 * y +
    (-44/531441 : ℝ) * r ^ 7 * z ^ 3 +
    (100/531441 : ℝ) * r ^ 7 * z ^ 2 +
    (260/531441 : ℝ) * r ^ 7 * z +
    (-1912/531441 : ℝ) * r ^ 7 +
    (-208/531441 : ℝ) * r ^ 6 * y ^ 2 * z +
    (4856/531441 : ℝ) * r ^ 6 * y ^ 2 +
    (-16/19683 : ℝ) * r ^ 6 * y * z ^ 2 +
    (752/177147 : ℝ) * r ^ 6 * y * z +
    (-4316/177147 : ℝ) * r ^ 6 * y +
    (68/177147 : ℝ) * r ^ 6 * z ^ 3 +
    (115/531441 : ℝ) * r ^ 6 * z ^ 2 +
    (-2660/531441 : ℝ) * r ^ 6 * z +
    (9212/531441 : ℝ) * r ^ 6 +
    (80/177147 : ℝ) * r ^ 5 * y ^ 2 * z +
    (-3032/177147 : ℝ) * r ^ 5 * y ^ 2 +
    (-16/19683 : ℝ) * r ^ 5 * y * z ^ 2 +
    (-2200/177147 : ℝ) * r ^ 5 * y * z +
    (10532/177147 : ℝ) * r ^ 5 * y +
    (170/59049 : ℝ) * r ^ 5 * z ^ 2 +
    (2224/177147 : ℝ) * r ^ 5 * z +
    (-7168/177147 : ℝ) * r ^ 5 +
    (80/59049 : ℝ) * r ^ 4 * y ^ 2 * z +
    (368/19683 : ℝ) * r ^ 4 * y ^ 2 +
    (16/6561 : ℝ) * r ^ 4 * y * z +
    (-5536/59049 : ℝ) * r ^ 4 * y +
    (-193/59049 : ℝ) * r ^ 4 * z ^ 2 +
    (-220/59049 : ℝ) * r ^ 4 * z +
    (836/19683 : ℝ) * r ^ 4 +
    (-80/19683 : ℝ) * r ^ 3 * y ^ 2 +
    (16/2187 : ℝ) * r ^ 3 * y * z +
    (1280/19683 : ℝ) * r ^ 3 * y +
    (-244/19683 : ℝ) * r ^ 3 * z +
    (-68/19683 : ℝ) * r ^ 3 +
    (-40/6561 : ℝ) * r ^ 2 * y ^ 2 +
    (4/729 : ℝ) * r ^ 2 * y +
    (16/2187 : ℝ) * r ^ 2 * z +
    (-188/6561 : ℝ) * r ^ 2 +
    (-4/243 : ℝ) * r * y +
    (4/243 : ℝ) * r

private def llDetCoeffTerms : List IntTerm := [
  ⟨1, 0, 0, (8748 : ℤ)⟩,
  ⟨1, 1, 0, (-8748 : ℤ)⟩,
  ⟨2, 0, 0, (-15228 : ℤ)⟩,
  ⟨2, 0, 1, (3888 : ℤ)⟩,
  ⟨2, 1, 0, (2916 : ℤ)⟩,
  ⟨2, 2, 0, (-3240 : ℤ)⟩,
  ⟨3, 0, 0, (-1836 : ℤ)⟩,
  ⟨3, 0, 1, (-6588 : ℤ)⟩,
  ⟨3, 1, 0, (34560 : ℤ)⟩,
  ⟨3, 1, 1, (3888 : ℤ)⟩,
  ⟨3, 2, 0, (-2160 : ℤ)⟩,
  ⟨4, 0, 0, (22572 : ℤ)⟩,
  ⟨4, 0, 1, (-1980 : ℤ)⟩,
  ⟨4, 0, 2, (-1737 : ℤ)⟩,
  ⟨4, 1, 0, (-49824 : ℤ)⟩,
  ⟨4, 1, 1, (1296 : ℤ)⟩,
  ⟨4, 2, 0, (9936 : ℤ)⟩,
  ⟨4, 2, 1, (720 : ℤ)⟩,
  ⟨5, 0, 0, (-21504 : ℤ)⟩,
  ⟨5, 0, 1, (6672 : ℤ)⟩,
  ⟨5, 0, 2, (1530 : ℤ)⟩,
  ⟨5, 1, 0, (31596 : ℤ)⟩,
  ⟨5, 1, 1, (-6600 : ℤ)⟩,
  ⟨5, 1, 2, (-432 : ℤ)⟩,
  ⟨5, 2, 0, (-9096 : ℤ)⟩,
  ⟨5, 2, 1, (240 : ℤ)⟩,
  ⟨6, 0, 0, (9212 : ℤ)⟩,
  ⟨6, 0, 1, (-2660 : ℤ)⟩,
  ⟨6, 0, 2, (115 : ℤ)⟩,
  ⟨6, 0, 3, (204 : ℤ)⟩,
  ⟨6, 1, 0, (-12948 : ℤ)⟩,
  ⟨6, 1, 1, (2256 : ℤ)⟩,
  ⟨6, 1, 2, (-432 : ℤ)⟩,
  ⟨6, 2, 0, (4856 : ℤ)⟩,
  ⟨6, 2, 1, (-208 : ℤ)⟩,
  ⟨7, 0, 0, (-1912 : ℤ)⟩,
  ⟨7, 0, 1, (260 : ℤ)⟩,
  ⟨7, 0, 2, (100 : ℤ)⟩,
  ⟨7, 0, 3, (-44 : ℤ)⟩,
  ⟨7, 1, 0, (3232 : ℤ)⟩,
  ⟨7, 1, 1, (-536 : ℤ)⟩,
  ⟨7, 2, 0, (-1368 : ℤ)⟩,
  ⟨7, 2, 1, (224 : ℤ)⟩,
  ⟨8, 0, 0, (156 : ℤ)⟩,
  ⟨8, 0, 1, (8 : ℤ)⟩,
  ⟨8, 0, 2, (-60 : ℤ)⟩,
  ⟨8, 0, 3, (24 : ℤ)⟩,
  ⟨8, 0, 4, (-4 : ℤ)⟩,
  ⟨8, 1, 0, (-336 : ℤ)⟩,
  ⟨8, 1, 1, (112 : ℤ)⟩,
  ⟨8, 2, 0, (144 : ℤ)⟩,
  ⟨8, 2, 1, (-48 : ℤ)⟩]

private def llDetCoeffNumer (i j k : ℕ) : ℤ :=
  intSparseCoeff llDetCoeffTerms i j k

private def llDetCoeff (i j k : ℕ) : ℚ :=
  (llDetCoeffNumer i j k : ℚ) / 531441

private theorem llDetCoeffExpansion (x d u : ℝ) :
    msum llDetCoeff 8 2 4 x d u = sparseEval (llDetCoeffTerms.map IntTerm.toRat) x d u / 531441 := by
  have he : ∀ i ∈ range 9, ∀ j ∈ range 3, ∀ k ∈ range 5,
      llDetCoeffNumer i j k = intSparseCoeff llDetCoeffTerms i j k := by intros; rfl
  have hb : ∀ t ∈ llDetCoeffTerms, t.i ≤ 8 ∧ t.j ≤ 2 ∧ t.k ≤ 4 := by decide +kernel
  exact msum_intSparse_scaled llDetCoeffNumer llDetCoeffTerms 531441 8 2 4 he hb x d u

private theorem llDetExpansion (r y z : ℝ) :
    msum llDetCoeff 8 2 4 r y z = llDet r y z := by
  rw [llDetCoeffExpansion]
  simp only [sparseEval, IntTerm.toRat, llDetCoeffTerms, llDet,
    List.map_cons, List.map_nil, List.sum_cons, List.sum_nil]
  push_cast
  ring


private def llDetInputData : IntTable :=
  (.node 67 (.node 33 (.node 16 (.node 8 (.node 4 (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))))
    (.node 4 (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (8748 : ℤ))))))
    (.node 8 (.node 4 (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 2 (.node 1 (.leaf (-8748 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))))
    (.node 4 (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (-15228 : ℤ))
    (.node 1 (.leaf (3888 : ℤ))
    (.leaf (0 : ℤ))))))))
    (.node 17 (.node 8 (.node 4 (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (2916 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (-3240 : ℤ)))))
    (.node 4 (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 2 (.node 1 (.leaf (-1836 : ℤ))
    (.leaf (-6588 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))))))
    (.node 8 (.node 4 (.node 2 (.node 1 (.leaf (34560 : ℤ))
    (.leaf (3888 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (-2160 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))))
    (.node 4 (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (22572 : ℤ))
    (.leaf (-1980 : ℤ))))
    (.node 2 (.node 1 (.leaf (-1737 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (-49824 : ℤ))
    (.leaf (1296 : ℤ)))))))))
    (.node 34 (.node 17 (.node 8 (.node 4 (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (9936 : ℤ))))
    (.node 2 (.node 1 (.leaf (720 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))))
    (.node 4 (.node 2 (.node 1 (.leaf (-21504 : ℤ))
    (.leaf (6672 : ℤ)))
    (.node 1 (.leaf (1530 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (31596 : ℤ)))
    (.node 1 (.leaf (-6600 : ℤ))
    (.node 1 (.leaf (-432 : ℤ))
    (.leaf (0 : ℤ)))))))
    (.node 8 (.node 4 (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (-9096 : ℤ)))
    (.node 1 (.leaf (240 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (9212 : ℤ))
    (.leaf (-2660 : ℤ)))))
    (.node 4 (.node 2 (.node 1 (.leaf (115 : ℤ))
    (.leaf (204 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (-12948 : ℤ))))
    (.node 2 (.node 1 (.leaf (2256 : ℤ))
    (.leaf (-432 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (4856 : ℤ))))))))
    (.node 17 (.node 8 (.node 4 (.node 2 (.node 1 (.leaf (-208 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 2 (.node 1 (.leaf (-1912 : ℤ))
    (.leaf (260 : ℤ)))
    (.node 1 (.leaf (100 : ℤ))
    (.leaf (-44 : ℤ)))))
    (.node 4 (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (3232 : ℤ)))
    (.node 1 (.leaf (-536 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (-1368 : ℤ))
    (.node 1 (.leaf (224 : ℤ))
    (.leaf (0 : ℤ)))))))
    (.node 8 (.node 4 (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (156 : ℤ))
    (.leaf (8 : ℤ))))
    (.node 2 (.node 1 (.leaf (-60 : ℤ))
    (.leaf (24 : ℤ)))
    (.node 1 (.leaf (-4 : ℤ))
    (.leaf (-336 : ℤ)))))
    (.node 4 (.node 2 (.node 1 (.leaf (112 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 2 (.node 1 (.leaf (144 : ℤ))
    (.leaf (-48 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))))))))

private def llDetInputNumer (i j k : ℕ) : ℤ :=
  llDetInputData.get ((i * 3 + j) * 5 + k)

private def llDetInput (i j k : ℕ) : ℚ :=
  (llDetInputNumer i j k : ℚ) / 531441

private theorem llDetInputNumerCorrect :
    ∀ i ∈ range 9, ∀ j ∈ range 3, ∀ k ∈ range 5,
      llDetInputNumer i j k = llDetCoeffNumer i j k := by
  decide +kernel

private theorem llDetInputCorrect :
    ∀ i ∈ range 9, ∀ j ∈ range 3, ∀ k ∈ range 5,
      llDetInput i j k = llDetCoeff i j k := by
  intro i hi j hj k hk
  exact congrArg (fun v : ℤ => (v : ℚ)/531441)
    (llDetInputNumerCorrect i hi j hj k hk)

private def llDetW1Data : IntTable :=
  (.node 40 (.node 20 (.node 10 (.node 5 (.node 2 (.node 1 (.leaf (1 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))))
    (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (8 : ℤ))))))
    (.node 5 (.node 2 (.node 1 (.leaf (1 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))))
    (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (28 : ℤ))
    (.leaf (7 : ℤ)))))))
    (.node 10 (.node 5 (.node 2 (.node 1 (.leaf (1 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))))
    (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (56 : ℤ))
    (.node 1 (.leaf (21 : ℤ))
    (.leaf (6 : ℤ))))))
    (.node 5 (.node 2 (.node 1 (.leaf (1 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))))
    (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (70 : ℤ)))
    (.node 1 (.leaf (35 : ℤ))
    (.node 1 (.leaf (15 : ℤ))
    (.leaf (5 : ℤ))))))))
    (.node 20 (.node 10 (.node 5 (.node 2 (.node 1 (.leaf (1 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))))
    (.node 2 (.node 1 (.leaf (56 : ℤ))
    (.leaf (35 : ℤ)))
    (.node 1 (.leaf (20 : ℤ))
    (.node 1 (.leaf (10 : ℤ))
    (.leaf (4 : ℤ))))))
    (.node 5 (.node 2 (.node 1 (.leaf (1 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (28 : ℤ)))))
    (.node 2 (.node 1 (.leaf (21 : ℤ))
    (.leaf (15 : ℤ)))
    (.node 1 (.leaf (10 : ℤ))
    (.node 1 (.leaf (6 : ℤ))
    (.leaf (3 : ℤ)))))))
    (.node 10 (.node 5 (.node 2 (.node 1 (.leaf (1 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (8 : ℤ))
    (.leaf (7 : ℤ)))))
    (.node 2 (.node 1 (.leaf (6 : ℤ))
    (.leaf (5 : ℤ)))
    (.node 1 (.leaf (4 : ℤ))
    (.node 1 (.leaf (3 : ℤ))
    (.leaf (2 : ℤ))))))
    (.node 5 (.node 2 (.node 1 (.leaf (1 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (1 : ℤ))
    (.node 1 (.leaf (1 : ℤ))
    (.leaf (1 : ℤ)))))
    (.node 3 (.node 1 (.leaf (1 : ℤ))
    (.node 1 (.leaf (1 : ℤ))
    (.leaf (1 : ℤ))))
    (.node 1 (.leaf (1 : ℤ))
    (.node 1 (.leaf (1 : ℤ))
    (.leaf (1 : ℤ)))))))))

private def llDetW1Numer (k i : ℕ) : ℤ :=
  llDetW1Data.get (k * 9 + i)

private def llDetW1 (k i : ℕ) : ℚ :=
  (llDetW1Numer k i : ℚ) / 1

private theorem llDetW1NumerCorrect :
    ∀ k ∈ range 9, ∀ i ∈ range 9,
      llDetW1Numer k i = intTransWeight 8 (0) 1 1 k i := by
  decide +kernel

private theorem llDetW1Correct : WeightsCorrect 8 (0 : ℚ) (1 : ℚ) llDetW1 := by
  intro k hk i hi
  have he := intTransWeight_cast 8 (0) 1 1 k i
    (by simp only [mem_range] at hi; omega) (by norm_num)
  rw [← llDetW1NumerCorrect k hk i hi] at he
  norm_num only [show (1 : ℚ)^8 = 1 by norm_num,
    show (0 : ℚ)/1 = 0 by norm_num,
    show (1 : ℚ)/1 = 1 by norm_num] at he
  simpa only [llDetW1, neg_div] using he

private def llDetW2Data : IntTable :=
  (.node 4 (.node 2 (.node 1 (.leaf (16 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (32 : ℤ))))
    (.node 2 (.node 1 (.leaf (4 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (16 : ℤ))
    (.node 1 (.leaf (4 : ℤ))
    (.leaf (1 : ℤ))))))

private def llDetW2Numer (k i : ℕ) : ℤ :=
  llDetW2Data.get (k * 3 + i)

private def llDetW2 (k i : ℕ) : ℚ :=
  (llDetW2Numer k i : ℚ) / 16

private theorem llDetW2NumerCorrect :
    ∀ k ∈ range 3, ∀ i ∈ range 3,
      llDetW2Numer k i = intTransWeight 2 (0) 1 4 k i := by
  decide +kernel

private theorem llDetW2Correct : WeightsCorrect 2 (0 : ℚ) ((1/4) : ℚ) llDetW2 := by
  intro k hk i hi
  have he := intTransWeight_cast 2 (0) 1 4 k i
    (by simp only [mem_range] at hi; omega) (by norm_num)
  rw [← llDetW2NumerCorrect k hk i hi] at he
  norm_num only [show (4 : ℚ)^2 = 16 by norm_num,
    show (0 : ℚ)/4 = 0 by norm_num,
    show (1 : ℚ)/4 = (1/4) by norm_num] at he
  simpa only [llDetW2, neg_div] using he

private def llDetW3Data : IntTable :=
  (.node 12 (.node 6 (.node 3 (.node 1 (.leaf (256 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (1024 : ℤ)))))
    (.node 3 (.node 1 (.leaf (64 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (1536 : ℤ))
    (.leaf (192 : ℤ))))))
    (.node 6 (.node 3 (.node 1 (.leaf (16 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 1 (.leaf (1024 : ℤ))
    (.node 1 (.leaf (192 : ℤ))
    (.leaf (32 : ℤ)))))
    (.node 3 (.node 1 (.leaf (4 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (256 : ℤ))))
    (.node 2 (.node 1 (.leaf (64 : ℤ))
    (.leaf (16 : ℤ)))
    (.node 1 (.leaf (4 : ℤ))
    (.leaf (1 : ℤ)))))))

private def llDetW3Numer (k i : ℕ) : ℤ :=
  llDetW3Data.get (k * 5 + i)

private def llDetW3 (k i : ℕ) : ℚ :=
  (llDetW3Numer k i : ℚ) / 256

private theorem llDetW3NumerCorrect :
    ∀ k ∈ range 5, ∀ i ∈ range 5,
      llDetW3Numer k i = intTransWeight 4 (0) 1 4 k i := by
  decide +kernel

private theorem llDetW3Correct : WeightsCorrect 4 (0 : ℚ) ((1/4) : ℚ) llDetW3 := by
  intro k hk i hi
  have he := intTransWeight_cast 4 (0) 1 4 k i
    (by simp only [mem_range] at hi; omega) (by norm_num)
  rw [← llDetW3NumerCorrect k hk i hi] at he
  norm_num only [show (4 : ℚ)^4 = 256 by norm_num,
    show (0 : ℚ)/4 = 0 by norm_num,
    show (1 : ℚ)/4 = (1/4) by norm_num] at he
  simpa only [llDetW3, neg_div] using he

private def llDetS1Data : IntTable :=
  (.node 67 (.node 33 (.node 16 (.node 8 (.node 4 (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))))
    (.node 4 (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (8748 : ℤ))))))
    (.node 8 (.node 4 (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 2 (.node 1 (.leaf (-8748 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))))
    (.node 4 (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (46008 : ℤ))
    (.node 1 (.leaf (3888 : ℤ))
    (.leaf (0 : ℤ))))))))
    (.node 17 (.node 8 (.node 4 (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (-58320 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (-3240 : ℤ)))))
    (.node 4 (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 2 (.node 1 (.leaf (90504 : ℤ))
    (.leaf (16740 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))))))
    (.node 8 (.node 4 (.node 2 (.node 1 (.leaf (-131652 : ℤ))
    (.leaf (3888 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (-21600 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))))
    (.node 4 (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (91152 : ℤ))
    (.leaf (23400 : ℤ))))
    (.node 2 (.node 1 (.leaf (-1737 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (-139464 : ℤ))
    (.leaf (20736 : ℤ)))))))))
    (.node 34 (.node 17 (.node 8 (.node 4 (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (-49464 : ℤ))))
    (.node 2 (.node 1 (.leaf (720 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))))
    (.node 4 (.node 2 (.node 1 (.leaf (52044 : ℤ))
    (.leaf (10632 : ℤ)))
    (.node 1 (.leaf (-5418 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (-69960 : ℤ)))
    (.node 1 (.leaf (37464 : ℤ))
    (.node 1 (.leaf (-432 : ℤ))
    (.leaf (0 : ℤ)))))))
    (.node 8 (.node 4 (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (-55752 : ℤ)))
    (.node 1 (.leaf (3120 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (17060 : ℤ))
    (.leaf (-2084 : ℤ)))))
    (.node 4 (.node 2 (.node 1 (.leaf (-5717 : ℤ))
    (.leaf (204 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (-11472 : ℤ))))
    (.node 2 (.node 1 (.leaf (29112 : ℤ))
    (.leaf (-1728 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (-33016 : ℤ))))))))
    (.node 17 (.node 8 (.node 4 (.node 2 (.node 1 (.leaf (4832 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 2 (.node 1 (.leaf (2976 : ℤ))
    (.leaf (-2576 : ℤ)))
    (.node 1 (.leaf (-2028 : ℤ))
    (.leaf (364 : ℤ)))))
    (.node 4 (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (1888 : ℤ)))
    (.node 1 (.leaf (8800 : ℤ))
    (.leaf (-2160 : ℤ))))
    (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (-9440 : ℤ))
    (.node 1 (.leaf (3408 : ℤ))
    (.leaf (0 : ℤ)))))))
    (.node 8 (.node 4 (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (208 : ℤ))
    (.leaf (-400 : ℤ))))
    (.node 2 (.node 1 (.leaf (-52 : ℤ))
    (.leaf (184 : ℤ)))
    (.node 1 (.leaf (-4 : ℤ))
    (.leaf (448 : ℤ)))))
    (.node 4 (.node 2 (.node 1 (.leaf (416 : ℤ))
    (.leaf (-864 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 2 (.node 1 (.leaf (-928 : ℤ))
    (.leaf (928 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))))))))

private def llDetS1Numer (i j k : ℕ) : ℤ :=
  llDetS1Data.get ((i * 3 + j) * 5 + k)

private def llDetS1 (i j k : ℕ) : ℚ :=
  (llDetS1Numer i j k : ℚ) / 531441

private theorem llDetS1NumerCorrect :
    ∀ h ∈ range 9, ∀ j ∈ range 3, ∀ k ∈ range 5,
      llDetS1Numer h j k = ∑ i ∈ range 9, llDetInputNumer i j k * llDetW1Numer h i := by
  decide +kernel

private theorem llDetS1Correct : Axis1Correct 8 2 4 llDetW1 llDetInput llDetS1 := by
  intro h hh j hj k hk
  have he := scaled_dot_eq (fun i => llDetInputNumer i j k) (llDetW1Numer h) (llDetS1Numer h j k) 531441 1 8
    (llDetS1NumerCorrect h hh j hj k hk)
  norm_num only [show (531441 : ℚ)*1 = 531441 by norm_num] at he
  exact he

private def llDetS2Data : IntTable :=
  (.node 67 (.node 33 (.node 16 (.node 8 (.node 4 (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))))
    (.node 4 (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (139968 : ℤ))))))
    (.node 8 (.node 4 (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 2 (.node 1 (.leaf (244944 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))))
    (.node 4 (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (104976 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (736128 : ℤ))
    (.node 1 (.leaf (62208 : ℤ))
    (.leaf (0 : ℤ))))))))
    (.node 17 (.node 8 (.node 4 (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (1238976 : ℤ))
    (.leaf (124416 : ℤ))))
    (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (499608 : ℤ)))))
    (.node 4 (.node 2 (.node 1 (.leaf (62208 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 2 (.node 1 (.leaf (1448064 : ℤ))
    (.leaf (267840 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))))))
    (.node 8 (.node 4 (.node 2 (.node 1 (.leaf (2369520 : ℤ))
    (.leaf (551232 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (899856 : ℤ)))
    (.node 1 (.leaf (283392 : ℤ))
    (.leaf (0 : ℤ)))))
    (.node 4 (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (1458432 : ℤ))
    (.leaf (374400 : ℤ))))
    (.node 2 (.node 1 (.leaf (-27792 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (2359008 : ℤ))
    (.leaf (831744 : ℤ)))))))))
    (.node 34 (.node 17 (.node 8 (.node 4 (.node 2 (.node 1 (.leaf (-55584 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (851112 : ℤ))))
    (.node 2 (.node 1 (.leaf (458064 : ℤ))
    (.leaf (-27792 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))))
    (.node 4 (.node 2 (.node 1 (.leaf (832704 : ℤ))
    (.leaf (170112 : ℤ)))
    (.node 1 (.leaf (-86688 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (1385568 : ℤ)))
    (.node 1 (.leaf (490080 : ℤ))
    (.node 1 (.leaf (-175104 : ℤ))
    (.leaf (0 : ℤ)))))))
    (.node 8 (.node 4 (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (497112 : ℤ)))
    (.node 1 (.leaf (323088 : ℤ))
    (.leaf (-88416 : ℤ))))
    (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (272960 : ℤ))
    (.leaf (-33344 : ℤ)))))
    (.node 4 (.node 2 (.node 1 (.leaf (-91472 : ℤ))
    (.leaf (3264 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (500032 : ℤ))))
    (.node 2 (.node 1 (.leaf (49760 : ℤ))
    (.leaf (-189856 : ℤ)))
    (.node 1 (.leaf (6528 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (194056 : ℤ))))))))
    (.node 17 (.node 8 (.node 4 (.node 2 (.node 1 (.leaf (87936 : ℤ))
    (.leaf (-98384 : ℤ)))
    (.node 1 (.leaf (3264 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 2 (.node 1 (.leaf (47616 : ℤ))
    (.leaf (-41216 : ℤ)))
    (.node 1 (.leaf (-32448 : ℤ))
    (.leaf (5824 : ℤ)))))
    (.node 4 (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (102784 : ℤ)))
    (.node 1 (.leaf (-47232 : ℤ))
    (.leaf (-73536 : ℤ))))
    (.node 2 (.node 1 (.leaf (11648 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (45728 : ℤ))
    (.node 1 (.leaf (-2608 : ℤ))
    (.leaf (-41088 : ℤ)))))))
    (.node 8 (.node 4 (.node 2 (.node 1 (.leaf (5824 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (3328 : ℤ))
    (.leaf (-6400 : ℤ))))
    (.node 2 (.node 1 (.leaf (-832 : ℤ))
    (.leaf (2944 : ℤ)))
    (.node 1 (.leaf (-64 : ℤ))
    (.leaf (8448 : ℤ)))))
    (.node 4 (.node 2 (.node 1 (.leaf (-11136 : ℤ))
    (.leaf (-5120 : ℤ)))
    (.node 1 (.leaf (5888 : ℤ))
    (.leaf (-128 : ℤ))))
    (.node 2 (.node 1 (.leaf (4192 : ℤ))
    (.leaf (-3808 : ℤ)))
    (.node 1 (.leaf (-4288 : ℤ))
    (.node 1 (.leaf (2944 : ℤ))
    (.leaf (-64 : ℤ))))))))))

private def llDetS2Numer (i j k : ℕ) : ℤ :=
  llDetS2Data.get ((i * 3 + j) * 5 + k)

private def llDetS2 (i j k : ℕ) : ℚ :=
  (llDetS2Numer i j k : ℚ) / 8503056

private theorem llDetS2NumerCorrect :
    ∀ k ∈ range 9, ∀ j ∈ range 3, ∀ h ∈ range 5,
      llDetS2Numer k j h = ∑ i ∈ range 3, llDetS1Numer k i h * llDetW2Numer j i := by
  decide +kernel

private theorem llDetS2Correct : Axis2Correct 8 2 4 llDetW2 llDetS1 llDetS2 := by
  intro k hk j hj h hh
  have he := scaled_dot_eq (fun i => llDetS1Numer k i h) (llDetW2Numer j) (llDetS2Numer k j h) 531441 16 2
    (llDetS2NumerCorrect k hk j hj h hh)
  norm_num only [show (531441 : ℚ)*16 = 8503056 by norm_num] at he
  exact he

private def llDetS3Data : IntTable :=
  (.node 67 (.node 33 (.node 16 (.node 8 (.node 4 (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))))
    (.node 4 (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (35831808 : ℤ))))))
    (.node 8 (.node 4 (.node 2 (.node 1 (.leaf (143327232 : ℤ))
    (.leaf (214990848 : ℤ)))
    (.node 1 (.leaf (143327232 : ℤ))
    (.leaf (35831808 : ℤ))))
    (.node 2 (.node 1 (.leaf (62705664 : ℤ))
    (.leaf (250822656 : ℤ)))
    (.node 1 (.leaf (376233984 : ℤ))
    (.leaf (250822656 : ℤ)))))
    (.node 4 (.node 2 (.node 1 (.leaf (62705664 : ℤ))
    (.leaf (26873856 : ℤ)))
    (.node 1 (.leaf (107495424 : ℤ))
    (.leaf (161243136 : ℤ))))
    (.node 2 (.node 1 (.leaf (107495424 : ℤ))
    (.leaf (26873856 : ℤ)))
    (.node 1 (.leaf (188448768 : ℤ))
    (.node 1 (.leaf (757776384 : ℤ))
    (.leaf (1142636544 : ℤ))))))))
    (.node 17 (.node 8 (.node 4 (.node 2 (.node 1 (.leaf (765739008 : ℤ))
    (.leaf (192430080 : ℤ)))
    (.node 1 (.leaf (317177856 : ℤ))
    (.leaf (1276674048 : ℤ))))
    (.node 2 (.node 1 (.leaf (1926955008 : ℤ))
    (.leaf (1292599296 : ℤ)))
    (.node 1 (.leaf (325140480 : ℤ))
    (.leaf (127899648 : ℤ)))))
    (.node 4 (.node 2 (.node 1 (.leaf (515579904 : ℤ))
    (.leaf (779341824 : ℤ)))
    (.node 1 (.leaf (523542528 : ℤ))
    (.leaf (131880960 : ℤ))))
    (.node 2 (.node 1 (.leaf (370704384 : ℤ))
    (.leaf (1499959296 : ℤ)))
    (.node 1 (.leaf (2275651584 : ℤ))
    (.node 1 (.leaf (1534242816 : ℤ))
    (.leaf (387846144 : ℤ)))))))
    (.node 8 (.node 4 (.node 2 (.node 1 (.leaf (606597120 : ℤ))
    (.leaf (2461667328 : ℤ)))
    (.node 1 (.leaf (3745419264 : ℤ))
    (.leaf (2532225024 : ℤ))))
    (.node 2 (.node 1 (.leaf (641875968 : ℤ))
    (.leaf (230363136 : ℤ)))
    (.node 1 (.leaf (939589632 : ℤ))
    (.leaf (1436590080 : ℤ)))))
    (.node 4 (.node 2 (.node 1 (.leaf (975863808 : ℤ))
    (.leaf (248500224 : ℤ)))
    (.node 1 (.leaf (373358592 : ℤ))
    (.leaf (1517395968 : ℤ))))
    (.node 2 (.node 1 (.leaf (2311591680 : ℤ))
    (.leaf (1564429824 : ℤ)))
    (.node 1 (.leaf (396875520 : ℤ))
    (.node 1 (.leaf (603906048 : ℤ))
    (.leaf (2468855808 : ℤ)))))))))
    (.node 34 (.node 17 (.node 8 (.node 4 (.node 2 (.node 1 (.leaf (3782241792 : ℤ))
    (.leaf (2573540352 : ℤ)))
    (.node 1 (.leaf (656248320 : ℤ))
    (.leaf (217884672 : ℤ))))
    (.node 2 (.node 1 (.leaf (900854784 : ℤ))
    (.leaf (1394811648 : ℤ)))
    (.node 1 (.leaf (958597632 : ℤ))
    (.leaf (246756096 : ℤ)))))
    (.node 4 (.node 2 (.node 1 (.leaf (213172224 : ℤ))
    (.leaf (863576064 : ℤ)))
    (.node 1 (.leaf (1310307840 : ℤ))
    (.leaf (882576384 : ℤ))))
    (.node 2 (.node 1 (.leaf (222672384 : ℤ))
    (.leaf (354705408 : ℤ)))
    (.node 1 (.leaf (1450186752 : ℤ))
    (.node 1 (.leaf (2219526144 : ℤ))
    (.leaf (1507313664 : ℤ)))))))
    (.node 8 (.node 4 (.node 2 (.node 1 (.leaf (383268864 : ℤ))
    (.leaf (127260672 : ℤ)))
    (.node 1 (.leaf (529720320 : ℤ))
    (.leaf (824182272 : ℤ))))
    (.node 2 (.node 1 (.leaf (568246272 : ℤ))
    (.leaf (146523648 : ℤ)))
    (.node 1 (.leaf (69877760 : ℤ))
    (.leaf (277377024 : ℤ)))))
    (.node 4 (.node 2 (.node 1 (.leaf (411400960 : ℤ))
    (.leaf (270194944 : ℤ)))
    (.node 1 (.leaf (66293248 : ℤ))
    (.leaf (128008192 : ℤ))))
    (.node 2 (.node 1 (.leaf (515217408 : ℤ))
    (.leaf (774565376 : ℤ)))
    (.node 1 (.leaf (515537408 : ℤ))
    (.node 1 (.leaf (128181248 : ℤ))
    (.leaf (49678336 : ℤ))))))))
    (.node 17 (.node 8 (.node 4 (.node 2 (.node 1 (.leaf (204341248 : ℤ))
    (.leaf (313379584 : ℤ)))
    (.node 1 (.leaf (212461824 : ℤ))
    (.leaf (53745152 : ℤ))))
    (.node 2 (.node 1 (.leaf (12189696 : ℤ))
    (.leaf (46120960 : ℤ)))
    (.node 1 (.leaf (64705536 : ℤ))
    (.leaf (39830272 : ℤ)))))
    (.node 4 (.node 2 (.node 1 (.leaf (9056000 : ℤ))
    (.leaf (26312704 : ℤ)))
    (.node 1 (.leaf (102227968 : ℤ))
    (.leaf (147631104 : ℤ))))
    (.node 2 (.node 1 (.leaf (93875712 : ℤ))
    (.leaf (22159872 : ℤ)))
    (.node 1 (.leaf (11706368 : ℤ))
    (.node 1 (.leaf (46658560 : ℤ))
    (.leaf (69080064 : ℤ)))))))
    (.node 8 (.node 4 (.node 2 (.node 1 (.leaf (45033216 : ℤ))
    (.leaf (10905344 : ℤ)))
    (.node 1 (.leaf (851968 : ℤ))
    (.leaf (2998272 : ℤ))))
    (.node 2 (.node 1 (.leaf (3869696 : ℤ))
    (.leaf (2164224 : ℤ)))
    (.node 1 (.leaf (440768 : ℤ))
    (.leaf (2162688 : ℤ)))))
    (.node 4 (.node 2 (.node 1 (.leaf (7938048 : ℤ))
    (.leaf (10756096 : ℤ)))
    (.node 1 (.leaf (6372352 : ℤ))
    (.leaf (1391488 : ℤ))))
    (.node 2 (.node 1 (.leaf (1073152 : ℤ))
    (.leaf (4048896 : ℤ)))
    (.node 1 (.leaf (5639168 : ℤ))
    (.node 1 (.leaf (3436032 : ℤ))
    (.leaf (772544 : ℤ))))))))))

private def llDetS3Numer (i j k : ℕ) : ℤ :=
  llDetS3Data.get ((i * 3 + j) * 5 + k)

private def llDetS3 (i j k : ℕ) : ℚ :=
  (llDetS3Numer i j k : ℚ) / 2176782336

private theorem llDetS3NumerCorrect :
    ∀ k ∈ range 9, ∀ j ∈ range 3, ∀ h ∈ range 5,
      llDetS3Numer k j h = ∑ i ∈ range 5, llDetS2Numer k j i * llDetW3Numer h i := by
  decide +kernel

private theorem llDetS3Correct : Axis3Correct 8 2 4 llDetW3 llDetS2 llDetS3 := by
  intro k hk j hj h hh
  have he := scaled_dot_eq (fun i => llDetS2Numer k j i) (llDetW3Numer h) (llDetS3Numer k j h) 8503056 256 4
    (llDetS3NumerCorrect k hk j hj h hh)
  norm_num only [show (8503056 : ℚ)*256 = 2176782336 by norm_num] at he
  exact he

private theorem llDetNumerSigns :
    ∀ i ∈ range 9, ∀ j ∈ range 3, ∀ k ∈ range 5,
      0 ≤ llDetS3Numer i j k := by
  decide +kernel

private theorem llDetSigns :
    ∀ i ∈ range 9, ∀ j ∈ range 3, ∀ k ∈ range 5,
      0 ≤ llDetS3 i j k := by
  intro i hi j hj k hk
  apply div_nonneg
  · exact_mod_cast llDetNumerSigns i hi j hj k hk
  · norm_num


private theorem llDetCertificate :
    ∀ i ∈ range 9, ∀ j ∈ range 3, ∀ k ∈ range 5,
      0 ≤ trans3 llDetCoeff 8 2 4 (0 : ℚ) (1 : ℚ) (0 : ℚ) ((1/4) : ℚ) (0 : ℚ) ((1/4) : ℚ) i j k := by
  have exactTable := checked_trans3 llDetCoeff llDetS1 llDetS2 llDetS3 8 2 4 (0 : ℚ) (1 : ℚ) (0 : ℚ) ((1/4) : ℚ) (0 : ℚ) ((1/4) : ℚ) llDetW1 llDetW2 llDetW3
    llDetW1Correct llDetW2Correct llDetW3Correct
    (axis1Correct_of_table llDetInputCorrect llDetS1Correct) llDetS2Correct llDetS3Correct
  intro i hi j hj k hk
  rw [← exactTable i hi j hj k hk]
  exact llDetSigns i hi j hj k hk

private theorem llDet_nonneg {r y z : ℝ}
    (hr0 : (0 : ℝ) ≤ r) (hr1 : r ≤ (1 : ℝ))
    (hy0 : (0 : ℝ) ≤ y) (hy1 : y ≤ (1/4 : ℝ))
    (hz0 : (0 : ℝ) ≤ z) (hz1 : z ≤ (1/4 : ℝ)) : 0 ≤ llDet r y z := by
  have h := msum_nonneg_on_box llDetCoeff 8 2 4 (x := r) (y := y) (z := z)
    (by norm_num) (by norm_num) (by norm_num)
    (by push_cast; linarith) (by push_cast; linarith)
    (by push_cast; linarith) (by push_cast; linarith)
    (by push_cast; linarith) (by push_cast; linarith) llDetCertificate
  rwa [llDetExpansion] at h


private theorem llDetIdentity (r y z : ℝ) :
    llDet r y z = 4*llA r y z*llC r y z-(llB r y z)^2 := by
  simp only [llDet,llA,llB,llC]
  ring

private theorem llIdentity (r y z : ℝ) :
    highLLTarget r (1-y) (1-z) = llA r y z*y^2+llB r y z*y*z+llC r y z*z^2 := by
  simp only [highLLTarget,llA,llB,llC]
  ring

theorem highLLLocal {x d u : ℝ}
    (hx0 : 0 ≤ x) (hx1 : x ≤ 1)
    (hd0 : (3/4 : ℝ) ≤ d) (hd1 : d ≤ 1)
    (hu0 : (3/4 : ℝ) ≤ u) (hu1 : u ≤ 1) : 0 ≤ highLLTarget x d u := by
  have hy0 : 0 ≤ 1-d := by linarith
  have hy1 : 1-d ≤ (1/4 : ℝ) := by linarith
  have hz0 : 0 ≤ 1-u := by linarith
  have hz1 : 1-u ≤ (1/4 : ℝ) := by linarith
  have hA := llA_nonneg hx0 hx1 hy0 hy1 hz0 hz1
  have hC := llC_nonneg hx0 hx1 hy0 hy1 hz0 hz1
  have hdet := llDet_nonneg hx0 hx1 hy0 hy1 hz0 hz1
  rw [llDetIdentity] at hdet
  have h := quadratic_nonneg hA hC (by linarith :
    (llB x (1-d) (1-u))^2 ≤ 4*llA x (1-d) (1-u)*llC x (1-d) (1-u))
    (d := 1-d) (t := 1-u)
  rw [← llIdentity] at h
  simpa only [sub_sub_cancel] using h

end Taeyoung.Methods.Atlas126
