import Taeyoung.Methods.Atlas126.HighBoundaries
import Taeyoung.Methods.Atlas126.Corners
import Taeyoung.Methods.Bernstein.CheckedTensor

/-! Generated by `codes/generate_atlas126_contacts_checked.py`.
All polynomial identities and integer certificate tables are kernel checked. -/
set_option maxHeartbeats 10000000
set_option maxRecDepth 100000
set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false
set_option linter.unusedTactic false
open Finset
namespace Taeyoung.Methods.Atlas126
open Taeyoung.Methods.Bernstein


private noncomputable def thU (r y z : ℝ) : ℝ :=
  (37/2916 : ℝ) * r ^ 6 +
    (103/5832 : ℝ) * r ^ 5 +
    (-313/5832 : ℝ) * r ^ 4 +
    (-233/2916 : ℝ) * r ^ 3 +
    (37/2916 : ℝ) * r ^ 2 +
    (41/729 : ℝ) * r +
    (25/729 : ℝ)

private def thUCoeffTerms : List IntTerm := [
  ⟨0, 0, 0, (200 : ℤ)⟩,
  ⟨1, 0, 0, (328 : ℤ)⟩,
  ⟨2, 0, 0, (74 : ℤ)⟩,
  ⟨3, 0, 0, (-466 : ℤ)⟩,
  ⟨4, 0, 0, (-313 : ℤ)⟩,
  ⟨5, 0, 0, (103 : ℤ)⟩,
  ⟨6, 0, 0, (74 : ℤ)⟩]

private def thUCoeffNumer (i j k : ℕ) : ℤ :=
  intSparseCoeff thUCoeffTerms i j k

private def thUCoeff (i j k : ℕ) : ℚ :=
  (thUCoeffNumer i j k : ℚ) / 5832

private theorem thUCoeffExpansion (x d u : ℝ) :
    msum thUCoeff 6 0 0 x d u = sparseEval (thUCoeffTerms.map IntTerm.toRat) x d u / 5832 := by
  have he : ∀ i ∈ range 7, ∀ j ∈ range 1, ∀ k ∈ range 1,
      thUCoeffNumer i j k = intSparseCoeff thUCoeffTerms i j k := by intros; rfl
  have hb : ∀ t ∈ thUCoeffTerms, t.i ≤ 6 ∧ t.j ≤ 0 ∧ t.k ≤ 0 := by decide +kernel
  exact msum_intSparse_scaled thUCoeffNumer thUCoeffTerms 5832 6 0 0 he hb x d u

private theorem thUExpansion (r y z : ℝ) :
    msum thUCoeff 6 0 0 r y z = thU r y z := by
  rw [thUCoeffExpansion]
  simp only [sparseEval, IntTerm.toRat, thUCoeffTerms, thU,
    List.map_cons, List.map_nil, List.sum_cons, List.sum_nil]
  push_cast
  ring


private def thUInputData : IntTable :=
  (.node 3 (.node 1 (.leaf (200 : ℤ))
    (.node 1 (.leaf (328 : ℤ))
    (.leaf (74 : ℤ))))
    (.node 2 (.node 1 (.leaf (-466 : ℤ))
    (.leaf (-313 : ℤ)))
    (.node 1 (.leaf (103 : ℤ))
    (.leaf (74 : ℤ)))))

private def thUInputNumer (i j k : ℕ) : ℤ :=
  thUInputData.get ((i * 1 + j) * 1 + k)

private def thUInput (i j k : ℕ) : ℚ :=
  (thUInputNumer i j k : ℚ) / 5832

private theorem thUInputNumerCorrect :
    ∀ i ∈ range 7, ∀ j ∈ range 1, ∀ k ∈ range 1,
      thUInputNumer i j k = thUCoeffNumer i j k := by
  decide +kernel

private theorem thUInputCorrect :
    ∀ i ∈ range 7, ∀ j ∈ range 1, ∀ k ∈ range 1,
      thUInput i j k = thUCoeff i j k := by
  intro i hi j hj k hk
  exact congrArg (fun v : ℤ => (v : ℚ)/5832)
    (thUInputNumerCorrect i hi j hj k hk)

private def thUW1Data : IntTable :=
  (.node 24 (.node 12 (.node 6 (.node 3 (.node 1 (.leaf (68719476736 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))))
    (.node 3 (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (412316860416 : ℤ))
    (.leaf (1073741824 : ℤ))))
    (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))))
    (.node 6 (.node 3 (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (1030792151040 : ℤ))))
    (.node 1 (.leaf (5368709120 : ℤ))
    (.node 1 (.leaf (16777216 : ℤ))
    (.leaf (0 : ℤ)))))
    (.node 3 (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 1 (.leaf (1374389534720 : ℤ))
    (.node 1 (.leaf (10737418240 : ℤ))
    (.leaf (67108864 : ℤ)))))))
    (.node 12 (.node 6 (.node 3 (.node 1 (.leaf (262144 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (1030792151040 : ℤ))
    (.leaf (10737418240 : ℤ)))))
    (.node 3 (.node 1 (.leaf (100663296 : ℤ))
    (.node 1 (.leaf (786432 : ℤ))
    (.leaf (4096 : ℤ))))
    (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (412316860416 : ℤ))))))
    (.node 6 (.node 3 (.node 1 (.leaf (5368709120 : ℤ))
    (.node 1 (.leaf (67108864 : ℤ))
    (.leaf (786432 : ℤ))))
    (.node 1 (.leaf (8192 : ℤ))
    (.node 1 (.leaf (64 : ℤ))
    (.leaf (0 : ℤ)))))
    (.node 3 (.node 1 (.leaf (68719476736 : ℤ))
    (.node 1 (.leaf (1073741824 : ℤ))
    (.leaf (16777216 : ℤ))))
    (.node 2 (.node 1 (.leaf (262144 : ℤ))
    (.leaf (4096 : ℤ)))
    (.node 1 (.leaf (64 : ℤ))
    (.leaf (1 : ℤ))))))))

private def thUW1Numer (k i : ℕ) : ℤ :=
  thUW1Data.get (k * 7 + i)

private def thUW1 (k i : ℕ) : ℚ :=
  (thUW1Numer k i : ℚ) / 68719476736

private theorem thUW1NumerCorrect :
    ∀ k ∈ range 7, ∀ i ∈ range 7,
      thUW1Numer k i = intTransWeight 6 (0) 1 64 k i := by
  decide +kernel

private theorem thUW1Correct : WeightsCorrect 6 (0 : ℚ) ((1/64) : ℚ) thUW1 := by
  intro k hk i hi
  have he := intTransWeight_cast 6 (0) 1 64 k i
    (by simp only [mem_range] at hi; omega) (by norm_num)
  rw [← thUW1NumerCorrect k hk i hi] at he
  norm_num only [show (64 : ℚ)^6 = 68719476736 by norm_num,
    show (0 : ℚ)/64 = 0 by norm_num,
    show (1 : ℚ)/64 = (1/64) by norm_num] at he
  simpa only [thUW1, neg_div] using he

private def thUW2Data : IntTable :=
  (.leaf (1 : ℤ))

private def thUW2Numer (k i : ℕ) : ℤ :=
  thUW2Data.get (k * 1 + i)

private def thUW2 (k i : ℕ) : ℚ :=
  (thUW2Numer k i : ℚ) / 1

private theorem thUW2NumerCorrect :
    ∀ k ∈ range 1, ∀ i ∈ range 1,
      thUW2Numer k i = intTransWeight 0 (0) 1 64 k i := by
  decide +kernel

private theorem thUW2Correct : WeightsCorrect 0 (0 : ℚ) ((1/64) : ℚ) thUW2 := by
  intro k hk i hi
  have he := intTransWeight_cast 0 (0) 1 64 k i
    (by simp only [mem_range] at hi; omega) (by norm_num)
  rw [← thUW2NumerCorrect k hk i hi] at he
  norm_num only [show (64 : ℚ)^0 = 1 by norm_num,
    show (0 : ℚ)/64 = 0 by norm_num,
    show (1 : ℚ)/64 = (1/64) by norm_num] at he
  simpa only [thUW2, neg_div] using he

private def thUW3Data : IntTable :=
  (.leaf (1 : ℤ))

private def thUW3Numer (k i : ℕ) : ℤ :=
  thUW3Data.get (k * 1 + i)

private def thUW3 (k i : ℕ) : ℚ :=
  (thUW3Numer k i : ℚ) / 1

private theorem thUW3NumerCorrect :
    ∀ k ∈ range 1, ∀ i ∈ range 1,
      thUW3Numer k i = intTransWeight 0 (0) 1 64 k i := by
  decide +kernel

private theorem thUW3Correct : WeightsCorrect 0 (0 : ℚ) ((1/64) : ℚ) thUW3 := by
  intro k hk i hi
  have he := intTransWeight_cast 0 (0) 1 64 k i
    (by simp only [mem_range] at hi; omega) (by norm_num)
  rw [← thUW3NumerCorrect k hk i hi] at he
  norm_num only [show (64 : ℚ)^0 = 1 by norm_num,
    show (0 : ℚ)/64 = 0 by norm_num,
    show (1 : ℚ)/64 = (1/64) by norm_num] at he
  simpa only [thUW3, neg_div] using he

private def thUS1Data : IntTable :=
  (.node 3 (.node 1 (.leaf (13743895347200 : ℤ))
    (.node 1 (.leaf (82815559401472 : ℤ))
    (.leaf (207920608313344 : ℤ))))
    (.node 2 (.node 1 (.leaf (278404624023552 : ℤ))
    (.leaf (209687384715264 : ℤ)))
    (.node 1 (.leaf (84228905695680 : ℤ))
    (.leaf (14097200744970 : ℤ)))))

private def thUS1Numer (i j k : ℕ) : ℤ :=
  thUS1Data.get ((i * 1 + j) * 1 + k)

private def thUS1 (i j k : ℕ) : ℚ :=
  (thUS1Numer i j k : ℚ) / 400771988324352

private theorem thUS1NumerCorrect :
    ∀ h ∈ range 7, ∀ j ∈ range 1, ∀ k ∈ range 1,
      thUS1Numer h j k = ∑ i ∈ range 7, thUInputNumer i j k * thUW1Numer h i := by
  decide +kernel

private theorem thUS1Correct : Axis1Correct 6 0 0 thUW1 thUInput thUS1 := by
  intro h hh j hj k hk
  have he := scaled_dot_eq (fun i => thUInputNumer i j k) (thUW1Numer h) (thUS1Numer h j k) 5832 68719476736 6
    (thUS1NumerCorrect h hh j hj k hk)
  norm_num only [show (5832 : ℚ)*68719476736 = 400771988324352 by norm_num] at he
  exact he

private def thUS2Data : IntTable :=
  (.node 3 (.node 1 (.leaf (13743895347200 : ℤ))
    (.node 1 (.leaf (82815559401472 : ℤ))
    (.leaf (207920608313344 : ℤ))))
    (.node 2 (.node 1 (.leaf (278404624023552 : ℤ))
    (.leaf (209687384715264 : ℤ)))
    (.node 1 (.leaf (84228905695680 : ℤ))
    (.leaf (14097200744970 : ℤ)))))

private def thUS2Numer (i j k : ℕ) : ℤ :=
  thUS2Data.get ((i * 1 + j) * 1 + k)

private def thUS2 (i j k : ℕ) : ℚ :=
  (thUS2Numer i j k : ℚ) / 400771988324352

private theorem thUS2NumerCorrect :
    ∀ k ∈ range 7, ∀ j ∈ range 1, ∀ h ∈ range 1,
      thUS2Numer k j h = ∑ i ∈ range 1, thUS1Numer k i h * thUW2Numer j i := by
  decide +kernel

private theorem thUS2Correct : Axis2Correct 6 0 0 thUW2 thUS1 thUS2 := by
  intro k hk j hj h hh
  have he := scaled_dot_eq (fun i => thUS1Numer k i h) (thUW2Numer j) (thUS2Numer k j h) 400771988324352 1 0
    (thUS2NumerCorrect k hk j hj h hh)
  norm_num only [show (400771988324352 : ℚ)*1 = 400771988324352 by norm_num] at he
  exact he

private def thUS3Data : IntTable :=
  (.node 3 (.node 1 (.leaf (13743895347200 : ℤ))
    (.node 1 (.leaf (82815559401472 : ℤ))
    (.leaf (207920608313344 : ℤ))))
    (.node 2 (.node 1 (.leaf (278404624023552 : ℤ))
    (.leaf (209687384715264 : ℤ)))
    (.node 1 (.leaf (84228905695680 : ℤ))
    (.leaf (14097200744970 : ℤ)))))

private def thUS3Numer (i j k : ℕ) : ℤ :=
  thUS3Data.get ((i * 1 + j) * 1 + k)

private def thUS3 (i j k : ℕ) : ℚ :=
  (thUS3Numer i j k : ℚ) / 400771988324352

private theorem thUS3NumerCorrect :
    ∀ k ∈ range 7, ∀ j ∈ range 1, ∀ h ∈ range 1,
      thUS3Numer k j h = ∑ i ∈ range 1, thUS2Numer k j i * thUW3Numer h i := by
  decide +kernel

private theorem thUS3Correct : Axis3Correct 6 0 0 thUW3 thUS2 thUS3 := by
  intro k hk j hj h hh
  have he := scaled_dot_eq (fun i => thUS2Numer k j i) (thUW3Numer h) (thUS3Numer k j h) 400771988324352 1 0
    (thUS3NumerCorrect k hk j hj h hh)
  norm_num only [show (400771988324352 : ℚ)*1 = 400771988324352 by norm_num] at he
  exact he

private theorem thUNumerSigns :
    ∀ i ∈ range 7, ∀ j ∈ range 1, ∀ k ∈ range 1,
      0 ≤ thUS3Numer i j k := by
  decide +kernel

private theorem thUSigns :
    ∀ i ∈ range 7, ∀ j ∈ range 1, ∀ k ∈ range 1,
      0 ≤ thUS3 i j k := by
  intro i hi j hj k hk
  apply div_nonneg
  · exact_mod_cast thUNumerSigns i hi j hj k hk
  · norm_num


private theorem thUCertificate :
    ∀ i ∈ range 7, ∀ j ∈ range 1, ∀ k ∈ range 1,
      0 ≤ trans3 thUCoeff 6 0 0 (0 : ℚ) ((1/64) : ℚ) (0 : ℚ) ((1/64) : ℚ) (0 : ℚ) ((1/64) : ℚ) i j k := by
  have exactTable := checked_trans3 thUCoeff thUS1 thUS2 thUS3 6 0 0 (0 : ℚ) ((1/64) : ℚ) (0 : ℚ) ((1/64) : ℚ) (0 : ℚ) ((1/64) : ℚ) thUW1 thUW2 thUW3
    thUW1Correct thUW2Correct thUW3Correct
    (axis1Correct_of_table thUInputCorrect thUS1Correct) thUS2Correct thUS3Correct
  intro i hi j hj k hk
  rw [← exactTable i hi j hj k hk]
  exact thUSigns i hi j hj k hk

private theorem thU_nonneg {r y z : ℝ}
    (hr0 : (0 : ℝ) ≤ r) (hr1 : r ≤ (1/64 : ℝ))
    (hy0 : (0 : ℝ) ≤ y) (hy1 : y ≤ (1/64 : ℝ))
    (hz0 : (0 : ℝ) ≤ z) (hz1 : z ≤ (1/64 : ℝ)) : 0 ≤ thU r y z := by
  have h := msum_nonneg_on_box thUCoeff 6 0 0 (x := r) (y := y) (z := z)
    (by norm_num) (by norm_num) (by norm_num)
    (by push_cast; linarith) (by push_cast; linarith)
    (by push_cast; linarith) (by push_cast; linarith)
    (by push_cast; linarith) (by push_cast; linarith) thUCertificate
  rwa [thUExpansion] at h


private noncomputable def thV (r y z : ℝ) : ℝ :=
  (1/486 : ℝ) * r ^ 5 +
    (-1/1458 : ℝ) * r ^ 4 +
    (-73/2916 : ℝ) * r ^ 3 +
    (-1/108 : ℝ) * r ^ 2 +
    (2/729 : ℝ) * r +
    (22/729 : ℝ)

private def thVCoeffTerms : List IntTerm := [
  ⟨0, 0, 0, (88 : ℤ)⟩,
  ⟨1, 0, 0, (8 : ℤ)⟩,
  ⟨2, 0, 0, (-27 : ℤ)⟩,
  ⟨3, 0, 0, (-73 : ℤ)⟩,
  ⟨4, 0, 0, (-2 : ℤ)⟩,
  ⟨5, 0, 0, (6 : ℤ)⟩]

private def thVCoeffNumer (i j k : ℕ) : ℤ :=
  intSparseCoeff thVCoeffTerms i j k

private def thVCoeff (i j k : ℕ) : ℚ :=
  (thVCoeffNumer i j k : ℚ) / 2916

private theorem thVCoeffExpansion (x d u : ℝ) :
    msum thVCoeff 5 0 0 x d u = sparseEval (thVCoeffTerms.map IntTerm.toRat) x d u / 2916 := by
  have he : ∀ i ∈ range 6, ∀ j ∈ range 1, ∀ k ∈ range 1,
      thVCoeffNumer i j k = intSparseCoeff thVCoeffTerms i j k := by intros; rfl
  have hb : ∀ t ∈ thVCoeffTerms, t.i ≤ 5 ∧ t.j ≤ 0 ∧ t.k ≤ 0 := by decide +kernel
  exact msum_intSparse_scaled thVCoeffNumer thVCoeffTerms 2916 5 0 0 he hb x d u

private theorem thVExpansion (r y z : ℝ) :
    msum thVCoeff 5 0 0 r y z = thV r y z := by
  rw [thVCoeffExpansion]
  simp only [sparseEval, IntTerm.toRat, thVCoeffTerms, thV,
    List.map_cons, List.map_nil, List.sum_cons, List.sum_nil]
  push_cast
  ring


private def thVInputData : IntTable :=
  (.node 3 (.node 1 (.leaf (88 : ℤ))
    (.node 1 (.leaf (8 : ℤ))
    (.leaf (-27 : ℤ))))
    (.node 1 (.leaf (-73 : ℤ))
    (.node 1 (.leaf (-2 : ℤ))
    (.leaf (6 : ℤ)))))

private def thVInputNumer (i j k : ℕ) : ℤ :=
  thVInputData.get ((i * 1 + j) * 1 + k)

private def thVInput (i j k : ℕ) : ℚ :=
  (thVInputNumer i j k : ℚ) / 2916

private theorem thVInputNumerCorrect :
    ∀ i ∈ range 6, ∀ j ∈ range 1, ∀ k ∈ range 1,
      thVInputNumer i j k = thVCoeffNumer i j k := by
  decide +kernel

private theorem thVInputCorrect :
    ∀ i ∈ range 6, ∀ j ∈ range 1, ∀ k ∈ range 1,
      thVInput i j k = thVCoeff i j k := by
  intro i hi j hj k hk
  exact congrArg (fun v : ℤ => (v : ℚ)/2916)
    (thVInputNumerCorrect i hi j hj k hk)

private def thVW1Data : IntTable :=
  (.node 18 (.node 9 (.node 4 (.node 2 (.node 1 (.leaf (1073741824 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (5368709120 : ℤ))
    (.node 1 (.leaf (16777216 : ℤ))
    (.leaf (0 : ℤ))))))
    (.node 4 (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (10737418240 : ℤ))))
    (.node 2 (.node 1 (.leaf (67108864 : ℤ))
    (.leaf (262144 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))))))
    (.node 9 (.node 4 (.node 2 (.node 1 (.leaf (10737418240 : ℤ))
    (.leaf (100663296 : ℤ)))
    (.node 1 (.leaf (786432 : ℤ))
    (.leaf (4096 : ℤ))))
    (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (5368709120 : ℤ))
    (.node 1 (.leaf (67108864 : ℤ))
    (.leaf (786432 : ℤ))))))
    (.node 4 (.node 2 (.node 1 (.leaf (8192 : ℤ))
    (.leaf (64 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (1073741824 : ℤ))))
    (.node 2 (.node 1 (.leaf (16777216 : ℤ))
    (.leaf (262144 : ℤ)))
    (.node 1 (.leaf (4096 : ℤ))
    (.node 1 (.leaf (64 : ℤ))
    (.leaf (1 : ℤ))))))))

private def thVW1Numer (k i : ℕ) : ℤ :=
  thVW1Data.get (k * 6 + i)

private def thVW1 (k i : ℕ) : ℚ :=
  (thVW1Numer k i : ℚ) / 1073741824

private theorem thVW1NumerCorrect :
    ∀ k ∈ range 6, ∀ i ∈ range 6,
      thVW1Numer k i = intTransWeight 5 (0) 1 64 k i := by
  decide +kernel

private theorem thVW1Correct : WeightsCorrect 5 (0 : ℚ) ((1/64) : ℚ) thVW1 := by
  intro k hk i hi
  have he := intTransWeight_cast 5 (0) 1 64 k i
    (by simp only [mem_range] at hi; omega) (by norm_num)
  rw [← thVW1NumerCorrect k hk i hi] at he
  norm_num only [show (64 : ℚ)^5 = 1073741824 by norm_num,
    show (0 : ℚ)/64 = 0 by norm_num,
    show (1 : ℚ)/64 = (1/64) by norm_num] at he
  simpa only [thVW1, neg_div] using he

private def thVW2Data : IntTable :=
  (.leaf (1 : ℤ))

private def thVW2Numer (k i : ℕ) : ℤ :=
  thVW2Data.get (k * 1 + i)

private def thVW2 (k i : ℕ) : ℚ :=
  (thVW2Numer k i : ℚ) / 1

private theorem thVW2NumerCorrect :
    ∀ k ∈ range 1, ∀ i ∈ range 1,
      thVW2Numer k i = intTransWeight 0 (0) 1 64 k i := by
  decide +kernel

private theorem thVW2Correct : WeightsCorrect 0 (0 : ℚ) ((1/64) : ℚ) thVW2 := by
  intro k hk i hi
  have he := intTransWeight_cast 0 (0) 1 64 k i
    (by simp only [mem_range] at hi; omega) (by norm_num)
  rw [← thVW2NumerCorrect k hk i hi] at he
  norm_num only [show (64 : ℚ)^0 = 1 by norm_num,
    show (0 : ℚ)/64 = 0 by norm_num,
    show (1 : ℚ)/64 = (1/64) by norm_num] at he
  simpa only [thVW2, neg_div] using he

private def thVW3Data : IntTable :=
  (.leaf (1 : ℤ))

private def thVW3Numer (k i : ℕ) : ℤ :=
  thVW3Data.get (k * 1 + i)

private def thVW3 (k i : ℕ) : ℚ :=
  (thVW3Numer k i : ℚ) / 1

private theorem thVW3NumerCorrect :
    ∀ k ∈ range 1, ∀ i ∈ range 1,
      thVW3Numer k i = intTransWeight 0 (0) 1 64 k i := by
  decide +kernel

private theorem thVW3Correct : WeightsCorrect 0 (0 : ℚ) ((1/64) : ℚ) thVW3 := by
  intro k hk i hi
  have he := intTransWeight_cast 0 (0) 1 64 k i
    (by simp only [mem_range] at hi; omega) (by norm_num)
  rw [← thVW3NumerCorrect k hk i hi] at he
  norm_num only [show (64 : ℚ)^0 = 1 by norm_num,
    show (0 : ℚ)/64 = 0 by norm_num,
    show (1 : ℚ)/64 = (1/64) by norm_num] at he
  simpa only [thVW3, neg_div] using he

private def thVS1Data : IntTable :=
  (.node 3 (.node 1 (.leaf (94489280512 : ℤ))
    (.node 1 (.leaf (472580620288 : ℤ))
    (.leaf (945422598144 : ℤ))))
    (.node 1 (.leaf (945676578816 : ℤ))
    (.node 1 (.leaf (472961441664 : ℤ))
    (.leaf (94616121222 : ℤ)))))

private def thVS1Numer (i j k : ℕ) : ℤ :=
  thVS1Data.get ((i * 1 + j) * 1 + k)

private def thVS1 (i j k : ℕ) : ℚ :=
  (thVS1Numer i j k : ℚ) / 3131031158784

private theorem thVS1NumerCorrect :
    ∀ h ∈ range 6, ∀ j ∈ range 1, ∀ k ∈ range 1,
      thVS1Numer h j k = ∑ i ∈ range 6, thVInputNumer i j k * thVW1Numer h i := by
  decide +kernel

private theorem thVS1Correct : Axis1Correct 5 0 0 thVW1 thVInput thVS1 := by
  intro h hh j hj k hk
  have he := scaled_dot_eq (fun i => thVInputNumer i j k) (thVW1Numer h) (thVS1Numer h j k) 2916 1073741824 5
    (thVS1NumerCorrect h hh j hj k hk)
  norm_num only [show (2916 : ℚ)*1073741824 = 3131031158784 by norm_num] at he
  exact he

private def thVS2Data : IntTable :=
  (.node 3 (.node 1 (.leaf (94489280512 : ℤ))
    (.node 1 (.leaf (472580620288 : ℤ))
    (.leaf (945422598144 : ℤ))))
    (.node 1 (.leaf (945676578816 : ℤ))
    (.node 1 (.leaf (472961441664 : ℤ))
    (.leaf (94616121222 : ℤ)))))

private def thVS2Numer (i j k : ℕ) : ℤ :=
  thVS2Data.get ((i * 1 + j) * 1 + k)

private def thVS2 (i j k : ℕ) : ℚ :=
  (thVS2Numer i j k : ℚ) / 3131031158784

private theorem thVS2NumerCorrect :
    ∀ k ∈ range 6, ∀ j ∈ range 1, ∀ h ∈ range 1,
      thVS2Numer k j h = ∑ i ∈ range 1, thVS1Numer k i h * thVW2Numer j i := by
  decide +kernel

private theorem thVS2Correct : Axis2Correct 5 0 0 thVW2 thVS1 thVS2 := by
  intro k hk j hj h hh
  have he := scaled_dot_eq (fun i => thVS1Numer k i h) (thVW2Numer j) (thVS2Numer k j h) 3131031158784 1 0
    (thVS2NumerCorrect k hk j hj h hh)
  norm_num only [show (3131031158784 : ℚ)*1 = 3131031158784 by norm_num] at he
  exact he

private def thVS3Data : IntTable :=
  (.node 3 (.node 1 (.leaf (94489280512 : ℤ))
    (.node 1 (.leaf (472580620288 : ℤ))
    (.leaf (945422598144 : ℤ))))
    (.node 1 (.leaf (945676578816 : ℤ))
    (.node 1 (.leaf (472961441664 : ℤ))
    (.leaf (94616121222 : ℤ)))))

private def thVS3Numer (i j k : ℕ) : ℤ :=
  thVS3Data.get ((i * 1 + j) * 1 + k)

private def thVS3 (i j k : ℕ) : ℚ :=
  (thVS3Numer i j k : ℚ) / 3131031158784

private theorem thVS3NumerCorrect :
    ∀ k ∈ range 6, ∀ j ∈ range 1, ∀ h ∈ range 1,
      thVS3Numer k j h = ∑ i ∈ range 1, thVS2Numer k j i * thVW3Numer h i := by
  decide +kernel

private theorem thVS3Correct : Axis3Correct 5 0 0 thVW3 thVS2 thVS3 := by
  intro k hk j hj h hh
  have he := scaled_dot_eq (fun i => thVS2Numer k j i) (thVW3Numer h) (thVS3Numer k j h) 3131031158784 1 0
    (thVS3NumerCorrect k hk j hj h hh)
  norm_num only [show (3131031158784 : ℚ)*1 = 3131031158784 by norm_num] at he
  exact he

private theorem thVNumerSigns :
    ∀ i ∈ range 6, ∀ j ∈ range 1, ∀ k ∈ range 1,
      0 ≤ thVS3Numer i j k := by
  decide +kernel

private theorem thVSigns :
    ∀ i ∈ range 6, ∀ j ∈ range 1, ∀ k ∈ range 1,
      0 ≤ thVS3 i j k := by
  intro i hi j hj k hk
  apply div_nonneg
  · exact_mod_cast thVNumerSigns i hi j hj k hk
  · norm_num


private theorem thVCertificate :
    ∀ i ∈ range 6, ∀ j ∈ range 1, ∀ k ∈ range 1,
      0 ≤ trans3 thVCoeff 5 0 0 (0 : ℚ) ((1/64) : ℚ) (0 : ℚ) ((1/64) : ℚ) (0 : ℚ) ((1/64) : ℚ) i j k := by
  have exactTable := checked_trans3 thVCoeff thVS1 thVS2 thVS3 5 0 0 (0 : ℚ) ((1/64) : ℚ) (0 : ℚ) ((1/64) : ℚ) (0 : ℚ) ((1/64) : ℚ) thVW1 thVW2 thVW3
    thVW1Correct thVW2Correct thVW3Correct
    (axis1Correct_of_table thVInputCorrect thVS1Correct) thVS2Correct thVS3Correct
  intro i hi j hj k hk
  rw [← exactTable i hi j hj k hk]
  exact thVSigns i hi j hj k hk

private theorem thV_nonneg {r y z : ℝ}
    (hr0 : (0 : ℝ) ≤ r) (hr1 : r ≤ (1/64 : ℝ))
    (hy0 : (0 : ℝ) ≤ y) (hy1 : y ≤ (1/64 : ℝ))
    (hz0 : (0 : ℝ) ≤ z) (hz1 : z ≤ (1/64 : ℝ)) : 0 ≤ thV r y z := by
  have h := msum_nonneg_on_box thVCoeff 5 0 0 (x := r) (y := y) (z := z)
    (by norm_num) (by norm_num) (by norm_num)
    (by push_cast; linarith) (by push_cast; linarith)
    (by push_cast; linarith) (by push_cast; linarith)
    (by push_cast; linarith) (by push_cast; linarith) thVCertificate
  rwa [thVExpansion] at h


private noncomputable def thW (r y z : ℝ) : ℝ :=
  (-5/486 : ℝ) * r ^ 6 +
    (5/1458 : ℝ) * r ^ 5 +
    (5/108 : ℝ) * r ^ 4 +
    (-1/2916 : ℝ) * r ^ 3 +
    (-17/1458 : ℝ) * r ^ 2 +
    (-8/243 : ℝ) * r +
    (4/729 : ℝ)

private def thWCoeffTerms : List IntTerm := [
  ⟨0, 0, 0, (16 : ℤ)⟩,
  ⟨1, 0, 0, (-96 : ℤ)⟩,
  ⟨2, 0, 0, (-34 : ℤ)⟩,
  ⟨3, 0, 0, (-1 : ℤ)⟩,
  ⟨4, 0, 0, (135 : ℤ)⟩,
  ⟨5, 0, 0, (10 : ℤ)⟩,
  ⟨6, 0, 0, (-30 : ℤ)⟩]

private def thWCoeffNumer (i j k : ℕ) : ℤ :=
  intSparseCoeff thWCoeffTerms i j k

private def thWCoeff (i j k : ℕ) : ℚ :=
  (thWCoeffNumer i j k : ℚ) / 2916

private theorem thWCoeffExpansion (x d u : ℝ) :
    msum thWCoeff 6 0 0 x d u = sparseEval (thWCoeffTerms.map IntTerm.toRat) x d u / 2916 := by
  have he : ∀ i ∈ range 7, ∀ j ∈ range 1, ∀ k ∈ range 1,
      thWCoeffNumer i j k = intSparseCoeff thWCoeffTerms i j k := by intros; rfl
  have hb : ∀ t ∈ thWCoeffTerms, t.i ≤ 6 ∧ t.j ≤ 0 ∧ t.k ≤ 0 := by decide +kernel
  exact msum_intSparse_scaled thWCoeffNumer thWCoeffTerms 2916 6 0 0 he hb x d u

private theorem thWExpansion (r y z : ℝ) :
    msum thWCoeff 6 0 0 r y z = thW r y z := by
  rw [thWCoeffExpansion]
  simp only [sparseEval, IntTerm.toRat, thWCoeffTerms, thW,
    List.map_cons, List.map_nil, List.sum_cons, List.sum_nil]
  push_cast
  ring


private def thWInputData : IntTable :=
  (.node 3 (.node 1 (.leaf (16 : ℤ))
    (.node 1 (.leaf (-96 : ℤ))
    (.leaf (-34 : ℤ))))
    (.node 2 (.node 1 (.leaf (-1 : ℤ))
    (.leaf (135 : ℤ)))
    (.node 1 (.leaf (10 : ℤ))
    (.leaf (-30 : ℤ)))))

private def thWInputNumer (i j k : ℕ) : ℤ :=
  thWInputData.get ((i * 1 + j) * 1 + k)

private def thWInput (i j k : ℕ) : ℚ :=
  (thWInputNumer i j k : ℚ) / 2916

private theorem thWInputNumerCorrect :
    ∀ i ∈ range 7, ∀ j ∈ range 1, ∀ k ∈ range 1,
      thWInputNumer i j k = thWCoeffNumer i j k := by
  decide +kernel

private theorem thWInputCorrect :
    ∀ i ∈ range 7, ∀ j ∈ range 1, ∀ k ∈ range 1,
      thWInput i j k = thWCoeff i j k := by
  intro i hi j hj k hk
  exact congrArg (fun v : ℤ => (v : ℚ)/2916)
    (thWInputNumerCorrect i hi j hj k hk)

private def thWW1Data : IntTable :=
  (.node 24 (.node 12 (.node 6 (.node 3 (.node 1 (.leaf (68719476736 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))))
    (.node 3 (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (412316860416 : ℤ))
    (.leaf (1073741824 : ℤ))))
    (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))))
    (.node 6 (.node 3 (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (1030792151040 : ℤ))))
    (.node 1 (.leaf (5368709120 : ℤ))
    (.node 1 (.leaf (16777216 : ℤ))
    (.leaf (0 : ℤ)))))
    (.node 3 (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 1 (.leaf (1374389534720 : ℤ))
    (.node 1 (.leaf (10737418240 : ℤ))
    (.leaf (67108864 : ℤ)))))))
    (.node 12 (.node 6 (.node 3 (.node 1 (.leaf (262144 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (1030792151040 : ℤ))
    (.leaf (10737418240 : ℤ)))))
    (.node 3 (.node 1 (.leaf (100663296 : ℤ))
    (.node 1 (.leaf (786432 : ℤ))
    (.leaf (4096 : ℤ))))
    (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (412316860416 : ℤ))))))
    (.node 6 (.node 3 (.node 1 (.leaf (5368709120 : ℤ))
    (.node 1 (.leaf (67108864 : ℤ))
    (.leaf (786432 : ℤ))))
    (.node 1 (.leaf (8192 : ℤ))
    (.node 1 (.leaf (64 : ℤ))
    (.leaf (0 : ℤ)))))
    (.node 3 (.node 1 (.leaf (68719476736 : ℤ))
    (.node 1 (.leaf (1073741824 : ℤ))
    (.leaf (16777216 : ℤ))))
    (.node 2 (.node 1 (.leaf (262144 : ℤ))
    (.leaf (4096 : ℤ)))
    (.node 1 (.leaf (64 : ℤ))
    (.leaf (1 : ℤ))))))))

private def thWW1Numer (k i : ℕ) : ℤ :=
  thWW1Data.get (k * 7 + i)

private def thWW1 (k i : ℕ) : ℚ :=
  (thWW1Numer k i : ℚ) / 68719476736

private theorem thWW1NumerCorrect :
    ∀ k ∈ range 7, ∀ i ∈ range 7,
      thWW1Numer k i = intTransWeight 6 (0) 1 64 k i := by
  decide +kernel

private theorem thWW1Correct : WeightsCorrect 6 (0 : ℚ) ((1/64) : ℚ) thWW1 := by
  intro k hk i hi
  have he := intTransWeight_cast 6 (0) 1 64 k i
    (by simp only [mem_range] at hi; omega) (by norm_num)
  rw [← thWW1NumerCorrect k hk i hi] at he
  norm_num only [show (64 : ℚ)^6 = 68719476736 by norm_num,
    show (0 : ℚ)/64 = 0 by norm_num,
    show (1 : ℚ)/64 = (1/64) by norm_num] at he
  simpa only [thWW1, neg_div] using he

private def thWW2Data : IntTable :=
  (.leaf (1 : ℤ))

private def thWW2Numer (k i : ℕ) : ℤ :=
  thWW2Data.get (k * 1 + i)

private def thWW2 (k i : ℕ) : ℚ :=
  (thWW2Numer k i : ℚ) / 1

private theorem thWW2NumerCorrect :
    ∀ k ∈ range 1, ∀ i ∈ range 1,
      thWW2Numer k i = intTransWeight 0 (0) 1 64 k i := by
  decide +kernel

private theorem thWW2Correct : WeightsCorrect 0 (0 : ℚ) ((1/64) : ℚ) thWW2 := by
  intro k hk i hi
  have he := intTransWeight_cast 0 (0) 1 64 k i
    (by simp only [mem_range] at hi; omega) (by norm_num)
  rw [← thWW2NumerCorrect k hk i hi] at he
  norm_num only [show (64 : ℚ)^0 = 1 by norm_num,
    show (0 : ℚ)/64 = 0 by norm_num,
    show (1 : ℚ)/64 = (1/64) by norm_num] at he
  simpa only [thWW2, neg_div] using he

private def thWW3Data : IntTable :=
  (.leaf (1 : ℤ))

private def thWW3Numer (k i : ℕ) : ℤ :=
  thWW3Data.get (k * 1 + i)

private def thWW3 (k i : ℕ) : ℚ :=
  (thWW3Numer k i : ℚ) / 1

private theorem thWW3NumerCorrect :
    ∀ k ∈ range 1, ∀ i ∈ range 1,
      thWW3Numer k i = intTransWeight 0 (0) 1 64 k i := by
  decide +kernel

private theorem thWW3Correct : WeightsCorrect 0 (0 : ℚ) ((1/64) : ℚ) thWW3 := by
  intro k hk i hi
  have he := intTransWeight_cast 0 (0) 1 64 k i
    (by simp only [mem_range] at hi; omega) (by norm_num)
  rw [← thWW3NumerCorrect k hk i hi] at he
  norm_num only [show (64 : ℚ)^0 = 1 by norm_num,
    show (0 : ℚ)/64 = 0 by norm_num,
    show (1 : ℚ)/64 = (1/64) by norm_num] at he
  simpa only [thWW3, neg_div] using he

private def thWS1Data : IntTable :=
  (.node 3 (.node 1 (.leaf (1099511627776 : ℤ))
    (.node 1 (.leaf (6493990551552 : ℤ))
    (.leaf (15976707915776 : ℤ))))
    (.node 2 (.node 1 (.leaf (20957158440960 : ℤ))
    (.leaf (15458459480064 : ℤ)))
    (.node 1 (.leaf (6079392309888 : ℤ))
    (.leaf (995862278754 : ℤ)))))

private def thWS1Numer (i j k : ℕ) : ℤ :=
  thWS1Data.get ((i * 1 + j) * 1 + k)

private def thWS1 (i j k : ℕ) : ℚ :=
  (thWS1Numer i j k : ℚ) / 200385994162176

private theorem thWS1NumerCorrect :
    ∀ h ∈ range 7, ∀ j ∈ range 1, ∀ k ∈ range 1,
      thWS1Numer h j k = ∑ i ∈ range 7, thWInputNumer i j k * thWW1Numer h i := by
  decide +kernel

private theorem thWS1Correct : Axis1Correct 6 0 0 thWW1 thWInput thWS1 := by
  intro h hh j hj k hk
  have he := scaled_dot_eq (fun i => thWInputNumer i j k) (thWW1Numer h) (thWS1Numer h j k) 2916 68719476736 6
    (thWS1NumerCorrect h hh j hj k hk)
  norm_num only [show (2916 : ℚ)*68719476736 = 200385994162176 by norm_num] at he
  exact he

private def thWS2Data : IntTable :=
  (.node 3 (.node 1 (.leaf (1099511627776 : ℤ))
    (.node 1 (.leaf (6493990551552 : ℤ))
    (.leaf (15976707915776 : ℤ))))
    (.node 2 (.node 1 (.leaf (20957158440960 : ℤ))
    (.leaf (15458459480064 : ℤ)))
    (.node 1 (.leaf (6079392309888 : ℤ))
    (.leaf (995862278754 : ℤ)))))

private def thWS2Numer (i j k : ℕ) : ℤ :=
  thWS2Data.get ((i * 1 + j) * 1 + k)

private def thWS2 (i j k : ℕ) : ℚ :=
  (thWS2Numer i j k : ℚ) / 200385994162176

private theorem thWS2NumerCorrect :
    ∀ k ∈ range 7, ∀ j ∈ range 1, ∀ h ∈ range 1,
      thWS2Numer k j h = ∑ i ∈ range 1, thWS1Numer k i h * thWW2Numer j i := by
  decide +kernel

private theorem thWS2Correct : Axis2Correct 6 0 0 thWW2 thWS1 thWS2 := by
  intro k hk j hj h hh
  have he := scaled_dot_eq (fun i => thWS1Numer k i h) (thWW2Numer j) (thWS2Numer k j h) 200385994162176 1 0
    (thWS2NumerCorrect k hk j hj h hh)
  norm_num only [show (200385994162176 : ℚ)*1 = 200385994162176 by norm_num] at he
  exact he

private def thWS3Data : IntTable :=
  (.node 3 (.node 1 (.leaf (1099511627776 : ℤ))
    (.node 1 (.leaf (6493990551552 : ℤ))
    (.leaf (15976707915776 : ℤ))))
    (.node 2 (.node 1 (.leaf (20957158440960 : ℤ))
    (.leaf (15458459480064 : ℤ)))
    (.node 1 (.leaf (6079392309888 : ℤ))
    (.leaf (995862278754 : ℤ)))))

private def thWS3Numer (i j k : ℕ) : ℤ :=
  thWS3Data.get ((i * 1 + j) * 1 + k)

private def thWS3 (i j k : ℕ) : ℚ :=
  (thWS3Numer i j k : ℚ) / 200385994162176

private theorem thWS3NumerCorrect :
    ∀ k ∈ range 7, ∀ j ∈ range 1, ∀ h ∈ range 1,
      thWS3Numer k j h = ∑ i ∈ range 1, thWS2Numer k j i * thWW3Numer h i := by
  decide +kernel

private theorem thWS3Correct : Axis3Correct 6 0 0 thWW3 thWS2 thWS3 := by
  intro k hk j hj h hh
  have he := scaled_dot_eq (fun i => thWS2Numer k j i) (thWW3Numer h) (thWS3Numer k j h) 200385994162176 1 0
    (thWS3NumerCorrect k hk j hj h hh)
  norm_num only [show (200385994162176 : ℚ)*1 = 200385994162176 by norm_num] at he
  exact he

private theorem thWNumerSigns :
    ∀ i ∈ range 7, ∀ j ∈ range 1, ∀ k ∈ range 1,
      0 ≤ thWS3Numer i j k := by
  decide +kernel

private theorem thWSigns :
    ∀ i ∈ range 7, ∀ j ∈ range 1, ∀ k ∈ range 1,
      0 ≤ thWS3 i j k := by
  intro i hi j hj k hk
  apply div_nonneg
  · exact_mod_cast thWNumerSigns i hi j hj k hk
  · norm_num


private theorem thWCertificate :
    ∀ i ∈ range 7, ∀ j ∈ range 1, ∀ k ∈ range 1,
      0 ≤ trans3 thWCoeff 6 0 0 (0 : ℚ) ((1/64) : ℚ) (0 : ℚ) ((1/64) : ℚ) (0 : ℚ) ((1/64) : ℚ) i j k := by
  have exactTable := checked_trans3 thWCoeff thWS1 thWS2 thWS3 6 0 0 (0 : ℚ) ((1/64) : ℚ) (0 : ℚ) ((1/64) : ℚ) (0 : ℚ) ((1/64) : ℚ) thWW1 thWW2 thWW3
    thWW1Correct thWW2Correct thWW3Correct
    (axis1Correct_of_table thWInputCorrect thWS1Correct) thWS2Correct thWS3Correct
  intro i hi j hj k hk
  rw [← exactTable i hi j hj k hk]
  exact thWSigns i hi j hj k hk

private theorem thW_nonneg {r y z : ℝ}
    (hr0 : (0 : ℝ) ≤ r) (hr1 : r ≤ (1/64 : ℝ))
    (hy0 : (0 : ℝ) ≤ y) (hy1 : y ≤ (1/64 : ℝ))
    (hz0 : (0 : ℝ) ≤ z) (hz1 : z ≤ (1/64 : ℝ)) : 0 ≤ thW r y z := by
  have h := msum_nonneg_on_box thWCoeff 6 0 0 (x := r) (y := y) (z := z)
    (by norm_num) (by norm_num) (by norm_num)
    (by push_cast; linarith) (by push_cast; linarith)
    (by push_cast; linarith) (by push_cast; linarith)
    (by push_cast; linarith) (by push_cast; linarith) thWCertificate
  rwa [thWExpansion] at h


private noncomputable def thA (r y z : ℝ) : ℝ :=
  (-53/5832 : ℝ) * r ^ 5 +
    (-43/5832 : ℝ) * r ^ 4 +
    (611/5832 : ℝ) * r ^ 3 +
    (1187/5832 : ℝ) * r ^ 2 +
    (545/2916 : ℝ) * r +
    (31/1458 : ℝ)

private def thACoeffTerms : List IntTerm := [
  ⟨0, 0, 0, (124 : ℤ)⟩,
  ⟨1, 0, 0, (1090 : ℤ)⟩,
  ⟨2, 0, 0, (1187 : ℤ)⟩,
  ⟨3, 0, 0, (611 : ℤ)⟩,
  ⟨4, 0, 0, (-43 : ℤ)⟩,
  ⟨5, 0, 0, (-53 : ℤ)⟩]

private def thACoeffNumer (i j k : ℕ) : ℤ :=
  intSparseCoeff thACoeffTerms i j k

private def thACoeff (i j k : ℕ) : ℚ :=
  (thACoeffNumer i j k : ℚ) / 5832

private theorem thACoeffExpansion (x d u : ℝ) :
    msum thACoeff 5 0 0 x d u = sparseEval (thACoeffTerms.map IntTerm.toRat) x d u / 5832 := by
  have he : ∀ i ∈ range 6, ∀ j ∈ range 1, ∀ k ∈ range 1,
      thACoeffNumer i j k = intSparseCoeff thACoeffTerms i j k := by intros; rfl
  have hb : ∀ t ∈ thACoeffTerms, t.i ≤ 5 ∧ t.j ≤ 0 ∧ t.k ≤ 0 := by decide +kernel
  exact msum_intSparse_scaled thACoeffNumer thACoeffTerms 5832 5 0 0 he hb x d u

private theorem thAExpansion (r y z : ℝ) :
    msum thACoeff 5 0 0 r y z = thA r y z := by
  rw [thACoeffExpansion]
  simp only [sparseEval, IntTerm.toRat, thACoeffTerms, thA,
    List.map_cons, List.map_nil, List.sum_cons, List.sum_nil]
  push_cast
  ring


private def thAInputData : IntTable :=
  (.node 3 (.node 1 (.leaf (124 : ℤ))
    (.node 1 (.leaf (1090 : ℤ))
    (.leaf (1187 : ℤ))))
    (.node 1 (.leaf (611 : ℤ))
    (.node 1 (.leaf (-43 : ℤ))
    (.leaf (-53 : ℤ)))))

private def thAInputNumer (i j k : ℕ) : ℤ :=
  thAInputData.get ((i * 1 + j) * 1 + k)

private def thAInput (i j k : ℕ) : ℚ :=
  (thAInputNumer i j k : ℚ) / 5832

private theorem thAInputNumerCorrect :
    ∀ i ∈ range 6, ∀ j ∈ range 1, ∀ k ∈ range 1,
      thAInputNumer i j k = thACoeffNumer i j k := by
  decide +kernel

private theorem thAInputCorrect :
    ∀ i ∈ range 6, ∀ j ∈ range 1, ∀ k ∈ range 1,
      thAInput i j k = thACoeff i j k := by
  intro i hi j hj k hk
  exact congrArg (fun v : ℤ => (v : ℚ)/5832)
    (thAInputNumerCorrect i hi j hj k hk)

private def thAW1Data : IntTable :=
  (.node 18 (.node 9 (.node 4 (.node 2 (.node 1 (.leaf (1073741824 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (5368709120 : ℤ))
    (.node 1 (.leaf (16777216 : ℤ))
    (.leaf (0 : ℤ))))))
    (.node 4 (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (10737418240 : ℤ))))
    (.node 2 (.node 1 (.leaf (67108864 : ℤ))
    (.leaf (262144 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))))))
    (.node 9 (.node 4 (.node 2 (.node 1 (.leaf (10737418240 : ℤ))
    (.leaf (100663296 : ℤ)))
    (.node 1 (.leaf (786432 : ℤ))
    (.leaf (4096 : ℤ))))
    (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (5368709120 : ℤ))
    (.node 1 (.leaf (67108864 : ℤ))
    (.leaf (786432 : ℤ))))))
    (.node 4 (.node 2 (.node 1 (.leaf (8192 : ℤ))
    (.leaf (64 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (1073741824 : ℤ))))
    (.node 2 (.node 1 (.leaf (16777216 : ℤ))
    (.leaf (262144 : ℤ)))
    (.node 1 (.leaf (4096 : ℤ))
    (.node 1 (.leaf (64 : ℤ))
    (.leaf (1 : ℤ))))))))

private def thAW1Numer (k i : ℕ) : ℤ :=
  thAW1Data.get (k * 6 + i)

private def thAW1 (k i : ℕ) : ℚ :=
  (thAW1Numer k i : ℚ) / 1073741824

private theorem thAW1NumerCorrect :
    ∀ k ∈ range 6, ∀ i ∈ range 6,
      thAW1Numer k i = intTransWeight 5 (0) 1 64 k i := by
  decide +kernel

private theorem thAW1Correct : WeightsCorrect 5 (0 : ℚ) ((1/64) : ℚ) thAW1 := by
  intro k hk i hi
  have he := intTransWeight_cast 5 (0) 1 64 k i
    (by simp only [mem_range] at hi; omega) (by norm_num)
  rw [← thAW1NumerCorrect k hk i hi] at he
  norm_num only [show (64 : ℚ)^5 = 1073741824 by norm_num,
    show (0 : ℚ)/64 = 0 by norm_num,
    show (1 : ℚ)/64 = (1/64) by norm_num] at he
  simpa only [thAW1, neg_div] using he

private def thAW2Data : IntTable :=
  (.leaf (1 : ℤ))

private def thAW2Numer (k i : ℕ) : ℤ :=
  thAW2Data.get (k * 1 + i)

private def thAW2 (k i : ℕ) : ℚ :=
  (thAW2Numer k i : ℚ) / 1

private theorem thAW2NumerCorrect :
    ∀ k ∈ range 1, ∀ i ∈ range 1,
      thAW2Numer k i = intTransWeight 0 (0) 1 64 k i := by
  decide +kernel

private theorem thAW2Correct : WeightsCorrect 0 (0 : ℚ) ((1/64) : ℚ) thAW2 := by
  intro k hk i hi
  have he := intTransWeight_cast 0 (0) 1 64 k i
    (by simp only [mem_range] at hi; omega) (by norm_num)
  rw [← thAW2NumerCorrect k hk i hi] at he
  norm_num only [show (64 : ℚ)^0 = 1 by norm_num,
    show (0 : ℚ)/64 = 0 by norm_num,
    show (1 : ℚ)/64 = (1/64) by norm_num] at he
  simpa only [thAW2, neg_div] using he

private def thAW3Data : IntTable :=
  (.leaf (1 : ℤ))

private def thAW3Numer (k i : ℕ) : ℤ :=
  thAW3Data.get (k * 1 + i)

private def thAW3 (k i : ℕ) : ℚ :=
  (thAW3Numer k i : ℚ) / 1

private theorem thAW3NumerCorrect :
    ∀ k ∈ range 1, ∀ i ∈ range 1,
      thAW3Numer k i = intTransWeight 0 (0) 1 64 k i := by
  decide +kernel

private theorem thAW3Correct : WeightsCorrect 0 (0 : ℚ) ((1/64) : ℚ) thAW3 := by
  intro k hk i hi
  have he := intTransWeight_cast 0 (0) 1 64 k i
    (by simp only [mem_range] at hi; omega) (by norm_num)
  rw [← thAW3NumerCorrect k hk i hi] at he
  norm_num only [show (64 : ℚ)^0 = 1 by norm_num,
    show (0 : ℚ)/64 = 0 by norm_num,
    show (1 : ℚ)/64 = (1/64) by norm_num] at he
  simpa only [thAW3, neg_div] using he

private def thAS1Data : IntTable :=
  (.node 3 (.node 1 (.leaf (133143986176 : ℤ))
    (.node 1 (.leaf (684007096320 : ℤ))
    (.leaf (1404899688448 : ℤ))))
    (.node 1 (.leaf (1442098851840 : ℤ))
    (.node 1 (.leaf (739807089984 : ℤ))
    (.leaf (151744816395 : ℤ)))))

private def thAS1Numer (i j k : ℕ) : ℤ :=
  thAS1Data.get ((i * 1 + j) * 1 + k)

private def thAS1 (i j k : ℕ) : ℚ :=
  (thAS1Numer i j k : ℚ) / 6262062317568

private theorem thAS1NumerCorrect :
    ∀ h ∈ range 6, ∀ j ∈ range 1, ∀ k ∈ range 1,
      thAS1Numer h j k = ∑ i ∈ range 6, thAInputNumer i j k * thAW1Numer h i := by
  decide +kernel

private theorem thAS1Correct : Axis1Correct 5 0 0 thAW1 thAInput thAS1 := by
  intro h hh j hj k hk
  have he := scaled_dot_eq (fun i => thAInputNumer i j k) (thAW1Numer h) (thAS1Numer h j k) 5832 1073741824 5
    (thAS1NumerCorrect h hh j hj k hk)
  norm_num only [show (5832 : ℚ)*1073741824 = 6262062317568 by norm_num] at he
  exact he

private def thAS2Data : IntTable :=
  (.node 3 (.node 1 (.leaf (133143986176 : ℤ))
    (.node 1 (.leaf (684007096320 : ℤ))
    (.leaf (1404899688448 : ℤ))))
    (.node 1 (.leaf (1442098851840 : ℤ))
    (.node 1 (.leaf (739807089984 : ℤ))
    (.leaf (151744816395 : ℤ)))))

private def thAS2Numer (i j k : ℕ) : ℤ :=
  thAS2Data.get ((i * 1 + j) * 1 + k)

private def thAS2 (i j k : ℕ) : ℚ :=
  (thAS2Numer i j k : ℚ) / 6262062317568

private theorem thAS2NumerCorrect :
    ∀ k ∈ range 6, ∀ j ∈ range 1, ∀ h ∈ range 1,
      thAS2Numer k j h = ∑ i ∈ range 1, thAS1Numer k i h * thAW2Numer j i := by
  decide +kernel

private theorem thAS2Correct : Axis2Correct 5 0 0 thAW2 thAS1 thAS2 := by
  intro k hk j hj h hh
  have he := scaled_dot_eq (fun i => thAS1Numer k i h) (thAW2Numer j) (thAS2Numer k j h) 6262062317568 1 0
    (thAS2NumerCorrect k hk j hj h hh)
  norm_num only [show (6262062317568 : ℚ)*1 = 6262062317568 by norm_num] at he
  exact he

private def thAS3Data : IntTable :=
  (.node 3 (.node 1 (.leaf (133143986176 : ℤ))
    (.node 1 (.leaf (684007096320 : ℤ))
    (.leaf (1404899688448 : ℤ))))
    (.node 1 (.leaf (1442098851840 : ℤ))
    (.node 1 (.leaf (739807089984 : ℤ))
    (.leaf (151744816395 : ℤ)))))

private def thAS3Numer (i j k : ℕ) : ℤ :=
  thAS3Data.get ((i * 1 + j) * 1 + k)

private def thAS3 (i j k : ℕ) : ℚ :=
  (thAS3Numer i j k : ℚ) / 6262062317568

private theorem thAS3NumerCorrect :
    ∀ k ∈ range 6, ∀ j ∈ range 1, ∀ h ∈ range 1,
      thAS3Numer k j h = ∑ i ∈ range 1, thAS2Numer k j i * thAW3Numer h i := by
  decide +kernel

private theorem thAS3Correct : Axis3Correct 5 0 0 thAW3 thAS2 thAS3 := by
  intro k hk j hj h hh
  have he := scaled_dot_eq (fun i => thAS2Numer k j i) (thAW3Numer h) (thAS3Numer k j h) 6262062317568 1 0
    (thAS3NumerCorrect k hk j hj h hh)
  norm_num only [show (6262062317568 : ℚ)*1 = 6262062317568 by norm_num] at he
  exact he

private theorem thANumerSigns :
    ∀ i ∈ range 6, ∀ j ∈ range 1, ∀ k ∈ range 1,
      0 ≤ thAS3Numer i j k := by
  decide +kernel

private theorem thASigns :
    ∀ i ∈ range 6, ∀ j ∈ range 1, ∀ k ∈ range 1,
      0 ≤ thAS3 i j k := by
  intro i hi j hj k hk
  apply div_nonneg
  · exact_mod_cast thANumerSigns i hi j hj k hk
  · norm_num


private theorem thACertificate :
    ∀ i ∈ range 6, ∀ j ∈ range 1, ∀ k ∈ range 1,
      0 ≤ trans3 thACoeff 5 0 0 (0 : ℚ) ((1/64) : ℚ) (0 : ℚ) ((1/64) : ℚ) (0 : ℚ) ((1/64) : ℚ) i j k := by
  have exactTable := checked_trans3 thACoeff thAS1 thAS2 thAS3 5 0 0 (0 : ℚ) ((1/64) : ℚ) (0 : ℚ) ((1/64) : ℚ) (0 : ℚ) ((1/64) : ℚ) thAW1 thAW2 thAW3
    thAW1Correct thAW2Correct thAW3Correct
    (axis1Correct_of_table thAInputCorrect thAS1Correct) thAS2Correct thAS3Correct
  intro i hi j hj k hk
  rw [← exactTable i hi j hj k hk]
  exact thASigns i hi j hj k hk

private theorem thA_nonneg {r y z : ℝ}
    (hr0 : (0 : ℝ) ≤ r) (hr1 : r ≤ (1/64 : ℝ))
    (hy0 : (0 : ℝ) ≤ y) (hy1 : y ≤ (1/64 : ℝ))
    (hz0 : (0 : ℝ) ≤ z) (hz1 : z ≤ (1/64 : ℝ)) : 0 ≤ thA r y z := by
  have h := msum_nonneg_on_box thACoeff 5 0 0 (x := r) (y := y) (z := z)
    (by norm_num) (by norm_num) (by norm_num)
    (by push_cast; linarith) (by push_cast; linarith)
    (by push_cast; linarith) (by push_cast; linarith)
    (by push_cast; linarith) (by push_cast; linarith) thACertificate
  rwa [thAExpansion] at h


private noncomputable def thB (r y z : ℝ) : ℝ :=
  (-2/243 : ℝ) * r ^ 7 * y ^ 2 +
    (22/729 : ℝ) * r ^ 7 * y +
    (-32/729 : ℝ) * r ^ 7 +
    (8/729 : ℝ) * r ^ 6 * y ^ 2 +
    (4/243 : ℝ) * r ^ 6 * y * z +
    (-7/729 : ℝ) * r ^ 6 * y +
    (-8/243 : ℝ) * r ^ 6 * z +
    (-19/1458 : ℝ) * r ^ 6 +
    (2/81 : ℝ) * r ^ 5 * y ^ 2 +
    (-4/729 : ℝ) * r ^ 5 * y * z +
    (-71/729 : ℝ) * r ^ 5 * y +
    (8/729 : ℝ) * r ^ 5 * z +
    (95/729 : ℝ) * r ^ 5 +
    (-16/729 : ℝ) * r ^ 4 * y ^ 2 * z ^ 3 +
    (-8/243 : ℝ) * r ^ 4 * y ^ 2 * z ^ 2 +
    (-4/243 : ℝ) * r ^ 4 * y ^ 2 * z +
    (-38/729 : ℝ) * r ^ 4 * y ^ 2 +
    (56/729 : ℝ) * r ^ 4 * y * z ^ 3 +
    (76/729 : ℝ) * r ^ 4 * y * z ^ 2 +
    (-2/243 : ℝ) * r ^ 4 * y * z +
    (61/729 : ℝ) * r ^ 4 * y +
    (-8/81 : ℝ) * r ^ 4 * z ^ 3 +
    (-88/729 : ℝ) * r ^ 4 * z ^ 2 +
    (49/729 : ℝ) * r ^ 4 * z +
    (-44/729 : ℝ) * r ^ 4 +
    (64/729 : ℝ) * r ^ 3 * y ^ 2 * z ^ 3 +
    (32/243 : ℝ) * r ^ 3 * y ^ 2 * z ^ 2 +
    (16/243 : ℝ) * r ^ 3 * y ^ 2 * z +
    (22/729 : ℝ) * r ^ 3 * y ^ 2 +
    (-184/729 : ℝ) * r ^ 3 * y * z ^ 3 +
    (-268/729 : ℝ) * r ^ 3 * y * z ^ 2 +
    (-98/729 : ℝ) * r ^ 3 * y * z +
    (-7/243 : ℝ) * r ^ 3 * y +
    (56/243 : ℝ) * r ^ 3 * z ^ 3 +
    (220/729 : ℝ) * r ^ 3 * z ^ 2 +
    (4/81 : ℝ) * r ^ 3 * z +
    (-71/1458 : ℝ) * r ^ 3 +
    (-32/243 : ℝ) * r ^ 2 * y ^ 2 * z ^ 3 +
    (-16/81 : ℝ) * r ^ 2 * y ^ 2 * z ^ 2 +
    (-8/81 : ℝ) * r ^ 2 * y ^ 2 * z +
    (-4/243 : ℝ) * r ^ 2 * y ^ 2 +
    (8/27 : ℝ) * r ^ 2 * y * z ^ 3 +
    (116/243 : ℝ) * r ^ 2 * y * z ^ 2 +
    (190/729 : ℝ) * r ^ 2 * y * z +
    (50/729 : ℝ) * r ^ 2 * y +
    (-8/81 : ℝ) * r ^ 2 * z ^ 3 +
    (-56/243 : ℝ) * r ^ 2 * z ^ 2 +
    (-131/729 : ℝ) * r ^ 2 * z +
    (-53/729 : ℝ) * r ^ 2 +
    (64/729 : ℝ) * r * y ^ 2 * z ^ 3 +
    (32/243 : ℝ) * r * y ^ 2 * z ^ 2 +
    (16/243 : ℝ) * r * y ^ 2 * z +
    (14/729 : ℝ) * r * y ^ 2 +
    (-104/729 : ℝ) * r * y * z ^ 3 +
    (-196/729 : ℝ) * r * y * z ^ 2 +
    (-38/243 : ℝ) * r * y * z +
    (-38/729 : ℝ) * r * y +
    (-8/81 : ℝ) * r * z ^ 3 +
    (28/729 : ℝ) * r * z ^ 2 +
    (62/729 : ℝ) * r * z +
    (73/729 : ℝ) * r +
    (-16/729 : ℝ) * y ^ 2 * z ^ 3 +
    (-8/243 : ℝ) * y ^ 2 * z ^ 2 +
    (-4/243 : ℝ) * y ^ 2 * z +
    (-2/243 : ℝ) * y ^ 2 +
    (16/729 : ℝ) * y * z ^ 3 +
    (40/729 : ℝ) * y * z ^ 2 +
    (20/729 : ℝ) * y * z +
    (4/729 : ℝ) * y +
    (16/243 : ℝ) * z ^ 3 +
    (8/729 : ℝ) * z ^ 2 +
    (2/243 : ℝ)

private def thBCoeffTerms : List IntTerm := [
  ⟨0, 0, 0, (12 : ℤ)⟩,
  ⟨0, 0, 2, (16 : ℤ)⟩,
  ⟨0, 0, 3, (96 : ℤ)⟩,
  ⟨0, 1, 0, (8 : ℤ)⟩,
  ⟨0, 1, 1, (40 : ℤ)⟩,
  ⟨0, 1, 2, (80 : ℤ)⟩,
  ⟨0, 1, 3, (32 : ℤ)⟩,
  ⟨0, 2, 0, (-12 : ℤ)⟩,
  ⟨0, 2, 1, (-24 : ℤ)⟩,
  ⟨0, 2, 2, (-48 : ℤ)⟩,
  ⟨0, 2, 3, (-32 : ℤ)⟩,
  ⟨1, 0, 0, (146 : ℤ)⟩,
  ⟨1, 0, 1, (124 : ℤ)⟩,
  ⟨1, 0, 2, (56 : ℤ)⟩,
  ⟨1, 0, 3, (-144 : ℤ)⟩,
  ⟨1, 1, 0, (-76 : ℤ)⟩,
  ⟨1, 1, 1, (-228 : ℤ)⟩,
  ⟨1, 1, 2, (-392 : ℤ)⟩,
  ⟨1, 1, 3, (-208 : ℤ)⟩,
  ⟨1, 2, 0, (28 : ℤ)⟩,
  ⟨1, 2, 1, (96 : ℤ)⟩,
  ⟨1, 2, 2, (192 : ℤ)⟩,
  ⟨1, 2, 3, (128 : ℤ)⟩,
  ⟨2, 0, 0, (-106 : ℤ)⟩,
  ⟨2, 0, 1, (-262 : ℤ)⟩,
  ⟨2, 0, 2, (-336 : ℤ)⟩,
  ⟨2, 0, 3, (-144 : ℤ)⟩,
  ⟨2, 1, 0, (100 : ℤ)⟩,
  ⟨2, 1, 1, (380 : ℤ)⟩,
  ⟨2, 1, 2, (696 : ℤ)⟩,
  ⟨2, 1, 3, (432 : ℤ)⟩,
  ⟨2, 2, 0, (-24 : ℤ)⟩,
  ⟨2, 2, 1, (-144 : ℤ)⟩,
  ⟨2, 2, 2, (-288 : ℤ)⟩,
  ⟨2, 2, 3, (-192 : ℤ)⟩,
  ⟨3, 0, 0, (-71 : ℤ)⟩,
  ⟨3, 0, 1, (72 : ℤ)⟩,
  ⟨3, 0, 2, (440 : ℤ)⟩,
  ⟨3, 0, 3, (336 : ℤ)⟩,
  ⟨3, 1, 0, (-42 : ℤ)⟩,
  ⟨3, 1, 1, (-196 : ℤ)⟩,
  ⟨3, 1, 2, (-536 : ℤ)⟩,
  ⟨3, 1, 3, (-368 : ℤ)⟩,
  ⟨3, 2, 0, (44 : ℤ)⟩,
  ⟨3, 2, 1, (96 : ℤ)⟩,
  ⟨3, 2, 2, (192 : ℤ)⟩,
  ⟨3, 2, 3, (128 : ℤ)⟩,
  ⟨4, 0, 0, (-88 : ℤ)⟩,
  ⟨4, 0, 1, (98 : ℤ)⟩,
  ⟨4, 0, 2, (-176 : ℤ)⟩,
  ⟨4, 0, 3, (-144 : ℤ)⟩,
  ⟨4, 1, 0, (122 : ℤ)⟩,
  ⟨4, 1, 1, (-12 : ℤ)⟩,
  ⟨4, 1, 2, (152 : ℤ)⟩,
  ⟨4, 1, 3, (112 : ℤ)⟩,
  ⟨4, 2, 0, (-76 : ℤ)⟩,
  ⟨4, 2, 1, (-24 : ℤ)⟩,
  ⟨4, 2, 2, (-48 : ℤ)⟩,
  ⟨4, 2, 3, (-32 : ℤ)⟩,
  ⟨5, 0, 0, (190 : ℤ)⟩,
  ⟨5, 0, 1, (16 : ℤ)⟩,
  ⟨5, 1, 0, (-142 : ℤ)⟩,
  ⟨5, 1, 1, (-8 : ℤ)⟩,
  ⟨5, 2, 0, (36 : ℤ)⟩,
  ⟨6, 0, 0, (-19 : ℤ)⟩,
  ⟨6, 0, 1, (-48 : ℤ)⟩,
  ⟨6, 1, 0, (-14 : ℤ)⟩,
  ⟨6, 1, 1, (24 : ℤ)⟩,
  ⟨6, 2, 0, (16 : ℤ)⟩,
  ⟨7, 0, 0, (-64 : ℤ)⟩,
  ⟨7, 1, 0, (44 : ℤ)⟩,
  ⟨7, 2, 0, (-12 : ℤ)⟩]

private def thBCoeffNumer (i j k : ℕ) : ℤ :=
  intSparseCoeff thBCoeffTerms i j k

private def thBCoeff (i j k : ℕ) : ℚ :=
  (thBCoeffNumer i j k : ℚ) / 1458

private theorem thBCoeffExpansion (x d u : ℝ) :
    msum thBCoeff 7 2 3 x d u = sparseEval (thBCoeffTerms.map IntTerm.toRat) x d u / 1458 := by
  have he : ∀ i ∈ range 8, ∀ j ∈ range 3, ∀ k ∈ range 4,
      thBCoeffNumer i j k = intSparseCoeff thBCoeffTerms i j k := by intros; rfl
  have hb : ∀ t ∈ thBCoeffTerms, t.i ≤ 7 ∧ t.j ≤ 2 ∧ t.k ≤ 3 := by decide +kernel
  exact msum_intSparse_scaled thBCoeffNumer thBCoeffTerms 1458 7 2 3 he hb x d u

private theorem thBExpansion (r y z : ℝ) :
    msum thBCoeff 7 2 3 r y z = thB r y z := by
  rw [thBCoeffExpansion]
  simp only [sparseEval, IntTerm.toRat, thBCoeffTerms, thB,
    List.map_cons, List.map_nil, List.sum_cons, List.sum_nil]
  push_cast
  ring


private def thBInputData : IntTable :=
  (.node 48 (.node 24 (.node 12 (.node 6 (.node 3 (.node 1 (.leaf (12 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (16 : ℤ))))
    (.node 1 (.leaf (96 : ℤ))
    (.node 1 (.leaf (8 : ℤ))
    (.leaf (40 : ℤ)))))
    (.node 3 (.node 1 (.leaf (80 : ℤ))
    (.node 1 (.leaf (32 : ℤ))
    (.leaf (-12 : ℤ))))
    (.node 1 (.leaf (-24 : ℤ))
    (.node 1 (.leaf (-48 : ℤ))
    (.leaf (-32 : ℤ))))))
    (.node 6 (.node 3 (.node 1 (.leaf (146 : ℤ))
    (.node 1 (.leaf (124 : ℤ))
    (.leaf (56 : ℤ))))
    (.node 1 (.leaf (-144 : ℤ))
    (.node 1 (.leaf (-76 : ℤ))
    (.leaf (-228 : ℤ)))))
    (.node 3 (.node 1 (.leaf (-392 : ℤ))
    (.node 1 (.leaf (-208 : ℤ))
    (.leaf (28 : ℤ))))
    (.node 1 (.leaf (96 : ℤ))
    (.node 1 (.leaf (192 : ℤ))
    (.leaf (128 : ℤ)))))))
    (.node 12 (.node 6 (.node 3 (.node 1 (.leaf (-106 : ℤ))
    (.node 1 (.leaf (-262 : ℤ))
    (.leaf (-336 : ℤ))))
    (.node 1 (.leaf (-144 : ℤ))
    (.node 1 (.leaf (100 : ℤ))
    (.leaf (380 : ℤ)))))
    (.node 3 (.node 1 (.leaf (696 : ℤ))
    (.node 1 (.leaf (432 : ℤ))
    (.leaf (-24 : ℤ))))
    (.node 1 (.leaf (-144 : ℤ))
    (.node 1 (.leaf (-288 : ℤ))
    (.leaf (-192 : ℤ))))))
    (.node 6 (.node 3 (.node 1 (.leaf (-71 : ℤ))
    (.node 1 (.leaf (72 : ℤ))
    (.leaf (440 : ℤ))))
    (.node 1 (.leaf (336 : ℤ))
    (.node 1 (.leaf (-42 : ℤ))
    (.leaf (-196 : ℤ)))))
    (.node 3 (.node 1 (.leaf (-536 : ℤ))
    (.node 1 (.leaf (-368 : ℤ))
    (.leaf (44 : ℤ))))
    (.node 1 (.leaf (96 : ℤ))
    (.node 1 (.leaf (192 : ℤ))
    (.leaf (128 : ℤ))))))))
    (.node 24 (.node 12 (.node 6 (.node 3 (.node 1 (.leaf (-88 : ℤ))
    (.node 1 (.leaf (98 : ℤ))
    (.leaf (-176 : ℤ))))
    (.node 1 (.leaf (-144 : ℤ))
    (.node 1 (.leaf (122 : ℤ))
    (.leaf (-12 : ℤ)))))
    (.node 3 (.node 1 (.leaf (152 : ℤ))
    (.node 1 (.leaf (112 : ℤ))
    (.leaf (-76 : ℤ))))
    (.node 1 (.leaf (-24 : ℤ))
    (.node 1 (.leaf (-48 : ℤ))
    (.leaf (-32 : ℤ))))))
    (.node 6 (.node 3 (.node 1 (.leaf (190 : ℤ))
    (.node 1 (.leaf (16 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (-142 : ℤ))
    (.leaf (-8 : ℤ)))))
    (.node 3 (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (36 : ℤ))))
    (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))))))
    (.node 12 (.node 6 (.node 3 (.node 1 (.leaf (-19 : ℤ))
    (.node 1 (.leaf (-48 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (-14 : ℤ))
    (.leaf (24 : ℤ)))))
    (.node 3 (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (16 : ℤ))))
    (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))))
    (.node 6 (.node 3 (.node 1 (.leaf (-64 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (44 : ℤ))
    (.leaf (0 : ℤ)))))
    (.node 3 (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (-12 : ℤ))))
    (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))))))))

private def thBInputNumer (i j k : ℕ) : ℤ :=
  thBInputData.get ((i * 3 + j) * 4 + k)

private def thBInput (i j k : ℕ) : ℚ :=
  (thBInputNumer i j k : ℚ) / 1458

private theorem thBInputNumerCorrect :
    ∀ i ∈ range 8, ∀ j ∈ range 3, ∀ k ∈ range 4,
      thBInputNumer i j k = thBCoeffNumer i j k := by
  decide +kernel

private theorem thBInputCorrect :
    ∀ i ∈ range 8, ∀ j ∈ range 3, ∀ k ∈ range 4,
      thBInput i j k = thBCoeff i j k := by
  intro i hi j hj k hk
  exact congrArg (fun v : ℤ => (v : ℚ)/1458)
    (thBInputNumerCorrect i hi j hj k hk)

private def thBW1Data : IntTable :=
  (.node 32 (.node 16 (.node 8 (.node 4 (.node 2 (.node 1 (.leaf (4398046511104 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))))
    (.node 4 (.node 2 (.node 1 (.leaf (30786325577728 : ℤ))
    (.leaf (68719476736 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))))
    (.node 8 (.node 4 (.node 2 (.node 1 (.leaf (92358976733184 : ℤ))
    (.leaf (412316860416 : ℤ)))
    (.node 1 (.leaf (1073741824 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))))
    (.node 4 (.node 2 (.node 1 (.leaf (153931627888640 : ℤ))
    (.leaf (1030792151040 : ℤ)))
    (.node 1 (.leaf (5368709120 : ℤ))
    (.leaf (16777216 : ℤ))))
    (.node 2 (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))))))
    (.node 16 (.node 8 (.node 4 (.node 2 (.node 1 (.leaf (153931627888640 : ℤ))
    (.leaf (1374389534720 : ℤ)))
    (.node 1 (.leaf (10737418240 : ℤ))
    (.leaf (67108864 : ℤ))))
    (.node 2 (.node 1 (.leaf (262144 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))))
    (.node 4 (.node 2 (.node 1 (.leaf (92358976733184 : ℤ))
    (.leaf (1030792151040 : ℤ)))
    (.node 1 (.leaf (10737418240 : ℤ))
    (.leaf (100663296 : ℤ))))
    (.node 2 (.node 1 (.leaf (786432 : ℤ))
    (.leaf (4096 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))))
    (.node 8 (.node 4 (.node 2 (.node 1 (.leaf (30786325577728 : ℤ))
    (.leaf (412316860416 : ℤ)))
    (.node 1 (.leaf (5368709120 : ℤ))
    (.leaf (67108864 : ℤ))))
    (.node 2 (.node 1 (.leaf (786432 : ℤ))
    (.leaf (8192 : ℤ)))
    (.node 1 (.leaf (64 : ℤ))
    (.leaf (0 : ℤ)))))
    (.node 4 (.node 2 (.node 1 (.leaf (4398046511104 : ℤ))
    (.leaf (68719476736 : ℤ)))
    (.node 1 (.leaf (1073741824 : ℤ))
    (.leaf (16777216 : ℤ))))
    (.node 2 (.node 1 (.leaf (262144 : ℤ))
    (.leaf (4096 : ℤ)))
    (.node 1 (.leaf (64 : ℤ))
    (.leaf (1 : ℤ))))))))

private def thBW1Numer (k i : ℕ) : ℤ :=
  thBW1Data.get (k * 8 + i)

private def thBW1 (k i : ℕ) : ℚ :=
  (thBW1Numer k i : ℚ) / 4398046511104

private theorem thBW1NumerCorrect :
    ∀ k ∈ range 8, ∀ i ∈ range 8,
      thBW1Numer k i = intTransWeight 7 (0) 1 64 k i := by
  decide +kernel

private theorem thBW1Correct : WeightsCorrect 7 (0 : ℚ) ((1/64) : ℚ) thBW1 := by
  intro k hk i hi
  have he := intTransWeight_cast 7 (0) 1 64 k i
    (by simp only [mem_range] at hi; omega) (by norm_num)
  rw [← thBW1NumerCorrect k hk i hi] at he
  norm_num only [show (64 : ℚ)^7 = 4398046511104 by norm_num,
    show (0 : ℚ)/64 = 0 by norm_num,
    show (1 : ℚ)/64 = (1/64) by norm_num] at he
  simpa only [thBW1, neg_div] using he

private def thBW2Data : IntTable :=
  (.node 4 (.node 2 (.node 1 (.leaf (4096 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (8192 : ℤ))))
    (.node 2 (.node 1 (.leaf (64 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (4096 : ℤ))
    (.node 1 (.leaf (64 : ℤ))
    (.leaf (1 : ℤ))))))

private def thBW2Numer (k i : ℕ) : ℤ :=
  thBW2Data.get (k * 3 + i)

private def thBW2 (k i : ℕ) : ℚ :=
  (thBW2Numer k i : ℚ) / 4096

private theorem thBW2NumerCorrect :
    ∀ k ∈ range 3, ∀ i ∈ range 3,
      thBW2Numer k i = intTransWeight 2 (0) 1 64 k i := by
  decide +kernel

private theorem thBW2Correct : WeightsCorrect 2 (0 : ℚ) ((1/64) : ℚ) thBW2 := by
  intro k hk i hi
  have he := intTransWeight_cast 2 (0) 1 64 k i
    (by simp only [mem_range] at hi; omega) (by norm_num)
  rw [← thBW2NumerCorrect k hk i hi] at he
  norm_num only [show (64 : ℚ)^2 = 4096 by norm_num,
    show (0 : ℚ)/64 = 0 by norm_num,
    show (1 : ℚ)/64 = (1/64) by norm_num] at he
  simpa only [thBW2, neg_div] using he

private def thBW3Data : IntTable :=
  (.node 8 (.node 4 (.node 2 (.node 1 (.leaf (262144 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 2 (.node 1 (.leaf (786432 : ℤ))
    (.leaf (4096 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))))
    (.node 4 (.node 2 (.node 1 (.leaf (786432 : ℤ))
    (.leaf (8192 : ℤ)))
    (.node 1 (.leaf (64 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 2 (.node 1 (.leaf (262144 : ℤ))
    (.leaf (4096 : ℤ)))
    (.node 1 (.leaf (64 : ℤ))
    (.leaf (1 : ℤ))))))

private def thBW3Numer (k i : ℕ) : ℤ :=
  thBW3Data.get (k * 4 + i)

private def thBW3 (k i : ℕ) : ℚ :=
  (thBW3Numer k i : ℚ) / 262144

private theorem thBW3NumerCorrect :
    ∀ k ∈ range 4, ∀ i ∈ range 4,
      thBW3Numer k i = intTransWeight 3 (0) 1 64 k i := by
  decide +kernel

private theorem thBW3Correct : WeightsCorrect 3 (0 : ℚ) ((1/64) : ℚ) thBW3 := by
  intro k hk i hi
  have he := intTransWeight_cast 3 (0) 1 64 k i
    (by simp only [mem_range] at hi; omega) (by norm_num)
  rw [← thBW3NumerCorrect k hk i hi] at he
  norm_num only [show (64 : ℚ)^3 = 262144 by norm_num,
    show (0 : ℚ)/64 = 0 by norm_num,
    show (1 : ℚ)/64 = (1/64) by norm_num] at he
  simpa only [thBW3, neg_div] using he

private def thBS1Data : IntTable :=
  (.node 48 (.node 24 (.node 12 (.node 6 (.node 3 (.node 1 (.leaf (52776558133248 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (70368744177664 : ℤ))))
    (.node 1 (.leaf (422212465065984 : ℤ))
    (.node 1 (.leaf (35184372088832 : ℤ))
    (.leaf (175921860444160 : ℤ)))))
    (.node 3 (.node 1 (.leaf (351843720888320 : ℤ))
    (.node 1 (.leaf (140737488355328 : ℤ))
    (.leaf (-52776558133248 : ℤ))))
    (.node 1 (.leaf (-105553116266496 : ℤ))
    (.node 1 (.leaf (-211106232532992 : ℤ))
    (.leaf (-140737488355328 : ℤ))))))
    (.node 6 (.node 3 (.node 1 (.leaf (379468950536192 : ℤ))
    (.node 1 (.leaf (8521215115264 : ℤ))
    (.leaf (496429499940864 : ℤ))))
    (.node 1 (.leaf (2945591650811904 : ℤ))
    (.node 1 (.leaf (241067924389888 : ℤ))
    (.leaf (1215784982413312 : ℤ)))))
    (.node 3 (.node 1 (.leaf (2435968011337728 : ℤ))
    (.node 1 (.leaf (970868767326208 : ℤ))
    (.leaf (-367511761584128 : ℤ))))
    (.node 1 (.leaf (-732274744098816 : ℤ))
    (.node 1 (.leaf (-1464549488197632 : ℤ))
    (.leaf (-976366325465088 : ℤ)))))))
    (.node 12 (.node 6 (.node 3 (.node 1 (.leaf (1168392165785600 : ℤ))
    (.node 1 (.leaf (50845970333696 : ℤ))
    (.leaf (1500472594661376 : ℤ))))
    (.node 1 (.leaf (8806933519663104 : ℤ))
    (.node 1 (.leaf (707643106656256 : ℤ))
    (.leaf (3600758847045632 : ℤ)))))
    (.node 3 (.node 1 (.leaf (7227837253681152 : ℤ))
    (.node 1 (.leaf (2870189204963328 : ℤ))
    (.leaf (-1096788618510336 : ℤ))))
    (.node 1 (.leaf (-2177187641819136 : ℤ))
    (.node 1 (.leaf (-4354375283638272 : ℤ))
    (.leaf (-2902916855758848 : ℤ))))))
    (.node 6 (.node 3 (.node 1 (.leaf (1997104914366464 : ℤ))
    (.node 1 (.leaf (126412832899072 : ℤ))
    (.leaf (2518833902387200 : ℤ))))
    (.node 1 (.leaf (14628234750590976 : ℤ))
    (.node 1 (.leaf (1153648985899008 : ℤ))
    (.leaf (5924281326239744 : ℤ)))))
    (.node 3 (.node 1 (.leaf (11914187336843264 : ℤ))
    (.node 1 (.leaf (4713720433344512 : ℤ))
    (.leaf (-1818445465255936 : ℤ))))
    (.node 1 (.leaf (-3596174506328064 : ℤ))
    (.node 1 (.leaf (-7192349012656128 : ℤ))
    (.leaf (-4794899341770752 : ℤ))))))))
    (.node 24 (.node 12 (.node 6 (.node 3 (.node 1 (.leaf (2046697452601344 : ℤ))
    (.node 1 (.leaf (167615956254720 : ℤ))
    (.leaf (2536293569396736 : ℤ))))
    (.node 1 (.leaf (14578000506912768 : ℤ))
    (.node 1 (.leaf (1128070373703680 : ℤ))
    (.leaf (5847971364077568 : ℤ)))))
    (.node 3 (.node 1 (.leaf (11783206846070784 : ℤ))
    (.node 1 (.leaf (4644552967192576 : ℤ))
    (.leaf (-1808951392862208 : ℤ))))
    (.node 1 (.leaf (-3563957426061312 : ℤ))
    (.node 1 (.leaf (-7127914852122624 : ℤ))
    (.leaf (-4751943234748416 : ℤ))))))
    (.node 6 (.node 3 (.node 1 (.leaf (1257657992994816 : ℤ))
    (.node 1 (.leaf (125012348043264 : ℤ))
    (.leaf (1531904369098752 : ℤ))))
    (.node 1 (.leaf (8716515218030592 : ℤ))
    (.node 1 (.leaf (661601219715072 : ℤ))
    (.leaf (3463398938345472 : ℤ)))))
    (.node 3 (.node 1 (.leaf (6992067022553088 : ℤ))
    (.node 1 (.leaf (2745684096712704 : ℤ))
    (.leaf (-1079698869043200 : ℤ))))
    (.node 1 (.leaf (-2119195938521088 : ℤ))
    (.node 1 (.leaf (-4238391877042176 : ℤ))
    (.leaf (-2825594584694784 : ℤ)))))))
    (.node 12 (.node 6 (.node 3 (.node 1 (.leaf (429060253006656 : ℤ))
    (.node 1 (.leaf (49725597938688 : ℤ))
    (.leaf (513896456650752 : ℤ))))
    (.node 1 (.leaf (2895362968780800 : ℤ))
    (.node 1 (.leaf (215488670350464 : ℤ))
    (.leaf (1139471725561344 : ℤ)))))
    (.node 3 (.node 1 (.leaf (2304978607669248 : ℤ))
    (.node 1 (.leaf (901695185879040 : ℤ))
    (.leaf (-358016990542848 : ℤ))))
    (.node 1 (.leaf (-700056065802240 : ℤ))
    (.node 1 (.leaf (-1400112131604480 : ℤ))
    (.leaf (-933408087736320 : ℤ))))))
    (.node 6 (.node 3 (.node 1 (.leaf (62694571629312 : ℤ))
    (.node 1 (.leaf (8241128469504 : ℤ))
    (.leaf (73863593459712 : ℤ))))
    (.node 1 (.leaf (412167840989184 : ℤ))
    (.node 1 (.leaf (30068392795308 : ℤ))
    (.leaf (160658550130176 : ℤ)))))
    (.node 3 (.node 1 (.leaf (325644057575424 : ℤ))
    (.node 1 (.leaf (126901549006848 : ℤ))
    (.leaf (-50877464165388 : ℤ))))
    (.node 1 (.leaf (-99109061001216 : ℤ))
    (.node 1 (.leaf (-198218122002432 : ℤ))
    (.leaf (-132145414668288 : ℤ)))))))))

private def thBS1Numer (i j k : ℕ) : ℤ :=
  thBS1Data.get ((i * 3 + j) * 4 + k)

private def thBS1 (i j k : ℕ) : ℚ :=
  (thBS1Numer i j k : ℚ) / 6412351813189632

private theorem thBS1NumerCorrect :
    ∀ h ∈ range 8, ∀ j ∈ range 3, ∀ k ∈ range 4,
      thBS1Numer h j k = ∑ i ∈ range 8, thBInputNumer i j k * thBW1Numer h i := by
  decide +kernel

private theorem thBS1Correct : Axis1Correct 7 2 3 thBW1 thBInput thBS1 := by
  intro h hh j hj k hk
  have he := scaled_dot_eq (fun i => thBInputNumer i j k) (thBW1Numer h) (thBS1Numer h j k) 1458 4398046511104 7
    (thBS1NumerCorrect h hh j hj k hk)
  norm_num only [show (1458 : ℚ)*4398046511104 = 6412351813189632 by norm_num] at he
  exact he

private def thBS2Data : IntTable :=
  (.node 48 (.node 24 (.node 12 (.node 6 (.node 3 (.node 1 (.leaf (216172782113783808 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (288230376151711744 : ℤ))))
    (.node 1 (.leaf (1729382256910270464 : ℤ))
    (.node 1 (.leaf (434597364041252864 : ℤ))
    (.leaf (11258999068426240 : ℤ)))))
    (.node 3 (.node 1 (.leaf (598978750440275968 : ℤ))
    (.node 1 (.leaf (3467771713075281920 : ℤ))
    (.leaf (218371805369335808 : ℤ))))
    (.node 1 (.leaf (11153445952159744 : ℤ))
    (.node 1 (.leaf (310537268056031232 : ℤ))
    (.leaf (1738248718676656128 : ℤ))))))
    (.node 6 (.node 3 (.node 1 (.leaf (1554304821396242432 : ℤ))
    (.node 1 (.leaf (34902897112121344 : ℤ))
    (.leaf (2033375231757778944 : ℤ))))
    (.node 1 (.leaf (12065143401725558784 : ℤ))
    (.node 1 (.leaf (3124037989953437696 : ℤ))
    (.leaf (147616033098694656 : ℤ)))))
    (.node 3 (.node 1 (.leaf (4222652416241172480 : ℤ))
    (.node 1 (.leaf (24192422404559994880 : ℤ))
    (.leaf (1569365656795611136 : ℤ))))
    (.node 1 (.leaf (111980861242474496 : ℤ))
    (.node 1 (.leaf (2187812634995195904 : ℤ))
    (.leaf (12126302636508971008 : ℤ)))))))
    (.node 12 (.node 6 (.node 3 (.node 1 (.leaf (4785734311057817600 : ℤ))
    (.node 1 (.leaf (208265094486818816 : ℤ))
    (.leaf (6145935747732996096 : ℤ))))
    (.node 1 (.leaf (36073199696540073984 : ℤ))
    (.node 1 (.leaf (9616757780941635584 : ℤ))
    (.leaf (646978755184558080 : ℤ)))))
    (.node 3 (.node 1 (.leaf (12754453079701585920 : ℤ))
    (.node 1 (.leaf (72330091502197800960 : ℤ))
    (.leaf (4829926681265307648 : ℤ))))
    (.node 1 (.leaf (436536473055920128 : ℤ))
    (.node 1 (.leaf (6604162956684951552 : ℤ))
    (.leaf (36253988888801968128 : ℤ))))))
    (.node 6 (.node 3 (.node 1 (.leaf (8180141729245036544 : ℤ))
    (.node 1 (.leaf (517786963554598912 : ℤ))
    (.leaf (10317143664177971200 : ℤ))))
    (.node 1 (.leaf (59917249538420637696 : ℤ))
    (.node 1 (.leaf (16434116993587609600 : ℤ))
    (.leaf (1414727931988541440 : ℤ)))))
    (.node 3 (.node 1 (.leaf (21396795317913911296 : ℤ))
    (.node 1 (.leaf (120136177184575324160 : ℤ))
    (.leaf (8252156818877317120 : ℤ))))
    (.node 1 (.leaf (893344793927614464 : ℤ))
    (.node 1 (.leaf (11072459304723283968 : ℤ))
    (.leaf (60214132746812915712 : ℤ))))))))
    (.node 24 (.node 12 (.node 6 (.node 3 (.node 1 (.leaf (8383272765855105024 : ℤ))
    (.node 1 (.leaf (686554956819333120 : ℤ))
    (.leaf (10388658460249030656 : ℤ))))
    (.node 1 (.leaf (59711490076314697728 : ℤ))
    (.node 1 (.leaf (16838742035627245568 : ℤ))
    (.leaf (1747380080939630592 : ℤ)))))
    (.node 3 (.node 1 (.leaf (21531442158646591488 : ℤ))
    (.node 1 (.leaf (119720231542529720320 : ℤ))
    (.leaf (8453660318379278336 : ℤ))))
    (.node 1 (.leaf (1057261166694236160 : ℤ))
    (.node 1 (.leaf (11135655783545438208 : ℤ))
    (.leaf (60003989522980274176 : ℤ))))))
    (.node 6 (.node 3 (.node 1 (.leaf (5151367139306766336 : ℤ))
    (.node 1 (.leaf (512050577585209344 : ℤ))
    (.leaf (6274680295828488192 : ℤ))))
    (.node 1 (.leaf (35702846333053304832 : ℤ))
    (.node 1 (.leaf (10345076756675297280 : ℤ))
    (.leaf (1245758687224528896 : ℤ)))))
    (.node 3 (.node 1 (.leaf (12996852881100374016 : ℤ))
    (.node 1 (.leaf (71581416448296222720 : ℤ))
    (.leaf (5192629918499487744 : ℤ))))
    (.node 1 (.leaf (731588913700798464 : ℤ))
    (.node 1 (.leaf (6717934193394843648 : ℤ))
    (.leaf (35875744520658223104 : ℤ)))))))
    (.node 12 (.node 6 (.node 3 (.node 1 (.leaf (1757430796315262976 : ℤ))
    (.node 1 (.leaf (203676049156866048 : ℤ))
    (.leaf (2104919886441480192 : ℤ))))
    (.node 1 (.leaf (11859406720126156800 : ℤ))
    (.node 1 (.leaf (3528652867532955648 : ℤ))
    (.leaf (480278288749658112 : ℤ)))))
    (.node 3 (.node 1 (.leaf (4357358403773792256 : ℤ))
    (.node 1 (.leaf (23776521932148572160 : ℤ))
    (.leaf (1770864054227149824 : ℤ))))
    (.node 1 (.leaf (275902183526989824 : ℤ))
    (.node 1 (.leaf (2251038405200707584 : ℤ))
    (.leaf (11916181803934679040 : ℤ))))))
    (.node 6 (.node 3 (.node 1 (.leaf (256796965393661952 : ℤ))
    (.node 1 (.leaf (33755662211088384 : ℤ))
    (.leaf (302545278810980352 : ℤ))))
    (.node 1 (.leaf (1688239476691697664 : ℤ))
    (.node 1 (.leaf (515518307926223616 : ℤ))
    (.leaf (77793471630508032 : ℤ)))))
    (.node 3 (.node 1 (.leaf (625931777306787840 : ℤ))
    (.node 1 (.leaf (3384600652519833600 : ℤ))
    (.leaf (258670465068396276 : ℤ))))
    (.node 1 (.leaf (43938700358418432 : ℤ))
    (.node 1 (.leaf (323188280373805056 : ℤ))
    (.leaf (1696229030413467648 : ℤ)))))))))

private def thBS2Numer (i j k : ℕ) : ℤ :=
  thBS2Data.get ((i * 3 + j) * 4 + k)

private def thBS2 (i j k : ℕ) : ℚ :=
  (thBS2Numer i j k : ℚ) / 26264993026824732672

private theorem thBS2NumerCorrect :
    ∀ k ∈ range 8, ∀ j ∈ range 3, ∀ h ∈ range 4,
      thBS2Numer k j h = ∑ i ∈ range 3, thBS1Numer k i h * thBW2Numer j i := by
  decide +kernel

private theorem thBS2Correct : Axis2Correct 7 2 3 thBW2 thBS1 thBS2 := by
  intro k hk j hj h hh
  have he := scaled_dot_eq (fun i => thBS1Numer k i h) (thBW2Numer j) (thBS2Numer k j h) 6412351813189632 4096 2
    (thBS2NumerCorrect k hk j hj h hh)
  norm_num only [show (6412351813189632 : ℚ)*4096 = 26264993026824732672 by norm_num] at he
  exact he

private def thBS3Data : IntTable :=
  (.node 48 (.node 24 (.node 12 (.node 6 (.node 3 (.node 1 (.leaf (56668397794435742564352 : ℤ))
    (.node 1 (.leaf (170005193383307227693056 : ℤ))
    (.leaf (170023640127380937244672 : ℤ))))
    (.node 1 (.leaf (56688573920766362386432 : ℤ))
    (.node 1 (.leaf (113927091399230190780416 : ℤ))
    (.leaf (341827391057874846220288 : ℤ)))))
    (.node 3 (.node 1 (.leaf (341911842558087297761280 : ℤ))
    (.node 1 (.leaf (114015010671155717603328 : ℤ))
    (.leaf (57244858546739166052352 : ℤ))))
    (.node 1 (.leaf (171780260154837544468480 : ℤ))
    (.node 1 (.leaf (171845819054613176778752 : ℤ))
    (.leaf (57312155695233475018752 : ℤ))))))
    (.node 6 (.node 3 (.node 1 (.leaf (407451683100096576094208 : ℤ))
    (.node 1 (.leaf (1222498011566860977307648 : ℤ))
    (.leaf (1222771109848264724185088 : ℤ))))
    (.node 1 (.leaf (407736846524902048530432 : ℤ))
    (.node 1 (.leaf (818947814838353971380224 : ℤ))
    (.leaf (2457448079786634167451648 : ℤ)))))
    (.node 3 (.node 1 (.leaf (2458322964812845855801344 : ℤ))
    (.node 1 (.leaf (819846892286970219724800 : ℤ))
    (.leaf (411399790735028685635584 : ℤ))))
    (.node 1 (.leaf (1234658045812735232442368 : ℤ))
    (.node 1 (.leaf (1235256739429024100515840 : ℤ))
    (.leaf (412010610653954062680064 : ℤ)))))))
    (.node 12 (.node 6 (.node 3 (.node 1 (.leaf (1254551535237940536934400 : ℤ))
    (.node 1 (.leaf (3764507659540839620673536 : ℤ))
    (.leaf (3765754053255712542294016 : ℤ))))
    (.node 1 (.leaf (1255834002152509998628864 : ℤ))
    (.node 1 (.leaf (2520975351727164118532096 : ℤ))
    (.leaf (7565576080162728305491968 : ℤ)))))
    (.node 3 (.node 1 (.leaf (7569042390141065156886528 : ℤ))
    (.node 1 (.leaf (2524513991797003167727616 : ℤ))
    (.leaf (1266136299933612808077312 : ℤ))))
    (.node 1 (.leaf (3800196953194475473076224 : ℤ))
    (.node 1 (.leaf (3802407673017340358819840 : ℤ))
    (.leaf (1268383273745366495789056 : ℤ))))))
    (.node 6 (.node 3 (.node 1 (.leaf (2144375073471210859790336 : ℤ))
    (.node 1 (.leaf (6435246075816352216514560 : ℤ))
    (.leaf (6438027228413579243814912 : ℤ))))
    (.node 1 (.leaf (2147216143317976307728384 : ℤ))
    (.node 1 (.leaf (4308105165167030330982400 : ℤ))
    (.leaf (12930110221110516058685440 : ℤ)))))
    (.node 3 (.node 1 (.leaf (12937274341620287614746624 : ℤ))
    (.node 1 (.leaf (4315389421853986462367744 : ℤ))
    (.leaf (2163253397127775419105280 : ℤ))))
    (.node 1 (.leaf (6493419331659253766160384 : ℤ))
    (.node 1 (.leaf (6497787109330683565178880 : ℤ))
    (.leaf (2167681388931952031039488 : ℤ))))))))
    (.node 24 (.node 12 (.node 6 (.node 3 (.node 1 (.leaf (2197624655932320651411456 : ℤ))
    (.node 1 (.leaf (6595686096900093942693888 : ℤ))
    (.leaf (6599163100144681869115392 : ℤ))))
    (.node 1 (.leaf (2201161370666984892530688 : ℤ))
    (.node 1 (.leaf (4414175192187468662177792 : ℤ))
    (.leaf (13249682845373934713438208 : ℤ)))))
    (.node 3 (.node 1 (.leaf (13258218126483616822198272 : ℤ))
    (.node 1 (.leaf (4422830193528693300658176 : ℤ))
    (.leaf (2216076330501217540112384 : ℤ))))
    (.node 1 (.leaf (6652559533242432211648512 : ℤ))
    (.node 1 (.leaf (6657602756951358711005184 : ℤ))
    (.leaf (2221179558199667019743232 : ℤ))))))
    (.node 6 (.node 3 (.node 1 (.leaf (1350399987366432954384384 : ℤ))
    (.node 1 (.leaf (4053297321265087880626176 : ℤ))
    (.leaf (4055796259969809921343488 : ℤ))))
    (.node 1 (.leaf (1352934628917488048406528 : ℤ))
    (.node 1 (.leaf (2711899801301889130168320 : ℤ))
    (.leaf (8140802031488539060862976 : ℤ)))))
    (.node 3 (.node 1 (.leaf (8146736457655801155158016 : ℤ))
    (.node 1 (.leaf (2717905808885599520686080 : ℤ))
    (.leaf (1361216777355129715163136 : ℤ))))
    (.node 1 (.leaf (4086646920255907615997952 : ℤ))
    (.node 1 (.leaf (4090073456234803356499968 : ℤ))
    (.leaf (1364679189078546113888256 : ℤ)))))))
    (.node 12 (.node 6 (.node 3 (.node 1 (.leaf (460699938669268297580544 : ℤ))
    (.node 1 (.leaf (1382934073105151416074240 : ℤ))
    (.leaf (1383903045075230194139136 : ℤ))))
    (.node 1 (.leaf (461680770046067201802240 : ℤ))
    (.node 1 (.leaf (925015177306559125389312 : ℤ))
    (.leaf (2777012751790395975794688 : ℤ)))))
    (.node 3 (.node 1 (.leaf (2779258842598956098125824 : ℤ))
    (.node 1 (.leaf (927285044637051396292608 : ℤ))
    (.leaf (464221386631321963462656 : ℤ))))
    (.node 1 (.leaf (1393794255237692440707072 : ℤ))
    (.node 1 (.leaf (1395068417039351836311552 : ℤ))
    (.leaf (465507464614785293746176 : ℤ))))))
    (.node 6 (.node 3 (.node 1 (.leaf (67317783696156118745088 : ℤ))
    (.node 1 (.leaf (202091614280884974256128 : ℤ))
    (.leaf (202249240371145495019520 : ℤ))))
    (.node 1 (.leaf (67477098025893331206144 : ℤ))
    (.node 1 (.leaf (135140031313011963592704 : ℤ))
    (.leaf (405738735998834451677184 : ℤ)))))
    (.node 3 (.node 1 (.leaf (406097437692380646998016 : ℤ))
    (.node 1 (.leaf (135502117607210678747136 : ℤ))
    (.leaf (67808910394889673375744 : ℤ))))
    (.node 1 (.leaf (203606704101337102024704 : ℤ))
    (.node 1 (.leaf (203807361067949107445760 : ℤ))
    (.leaf (68011263590532092264448 : ℤ)))))))))

private def thBS3Numer (i j k : ℕ) : ℤ :=
  thBS3Data.get ((i * 3 + j) * 4 + k)

private def thBS3 (i j k : ℕ) : ℚ :=
  (thBS3Numer i j k : ℚ) / 6885210332023942721568768

private theorem thBS3NumerCorrect :
    ∀ k ∈ range 8, ∀ j ∈ range 3, ∀ h ∈ range 4,
      thBS3Numer k j h = ∑ i ∈ range 4, thBS2Numer k j i * thBW3Numer h i := by
  decide +kernel

private theorem thBS3Correct : Axis3Correct 7 2 3 thBW3 thBS2 thBS3 := by
  intro k hk j hj h hh
  have he := scaled_dot_eq (fun i => thBS2Numer k j i) (thBW3Numer h) (thBS3Numer k j h) 26264993026824732672 262144 3
    (thBS3NumerCorrect k hk j hj h hh)
  norm_num only [show (26264993026824732672 : ℚ)*262144 = 6885210332023942721568768 by norm_num] at he
  exact he

private theorem thBNumerSigns :
    ∀ i ∈ range 8, ∀ j ∈ range 3, ∀ k ∈ range 4,
      0 ≤ thBS3Numer i j k := by
  decide +kernel

private theorem thBSigns :
    ∀ i ∈ range 8, ∀ j ∈ range 3, ∀ k ∈ range 4,
      0 ≤ thBS3 i j k := by
  intro i hi j hj k hk
  apply div_nonneg
  · exact_mod_cast thBNumerSigns i hi j hj k hk
  · norm_num


private theorem thBCertificate :
    ∀ i ∈ range 8, ∀ j ∈ range 3, ∀ k ∈ range 4,
      0 ≤ trans3 thBCoeff 7 2 3 (0 : ℚ) ((1/64) : ℚ) (0 : ℚ) ((1/64) : ℚ) (0 : ℚ) ((1/64) : ℚ) i j k := by
  have exactTable := checked_trans3 thBCoeff thBS1 thBS2 thBS3 7 2 3 (0 : ℚ) ((1/64) : ℚ) (0 : ℚ) ((1/64) : ℚ) (0 : ℚ) ((1/64) : ℚ) thBW1 thBW2 thBW3
    thBW1Correct thBW2Correct thBW3Correct
    (axis1Correct_of_table thBInputCorrect thBS1Correct) thBS2Correct thBS3Correct
  intro i hi j hj k hk
  rw [← exactTable i hi j hj k hk]
  exact thBSigns i hi j hj k hk

private theorem thB_nonneg {r y z : ℝ}
    (hr0 : (0 : ℝ) ≤ r) (hr1 : r ≤ (1/64 : ℝ))
    (hy0 : (0 : ℝ) ≤ y) (hy1 : y ≤ (1/64 : ℝ))
    (hz0 : (0 : ℝ) ≤ z) (hz1 : z ≤ (1/64 : ℝ)) : 0 ≤ thB r y z := by
  have h := msum_nonneg_on_box thBCoeff 7 2 3 (x := r) (y := y) (z := z)
    (by norm_num) (by norm_num) (by norm_num)
    (by push_cast; linarith) (by push_cast; linarith)
    (by push_cast; linarith) (by push_cast; linarith)
    (by push_cast; linarith) (by push_cast; linarith) thBCertificate
  rwa [thBExpansion] at h


private noncomputable def thC (r y z : ℝ) : ℝ :=
  (5/243 : ℝ) * r ^ 6 +
    (-8/729 : ℝ) * r ^ 5 +
    (160/729 : ℝ) * r ^ 4 * y * z +
    (176/729 : ℝ) * r ^ 4 * y +
    (-32/729 : ℝ) * r ^ 4 * z +
    (-197/1458 : ℝ) * r ^ 4 +
    (-160/729 : ℝ) * r ^ 3 * y * z +
    (-80/729 : ℝ) * r ^ 3 * y +
    (-32/729 : ℝ) * r ^ 3 * z +
    (-25/243 : ℝ) * r ^ 3 +
    (-160/243 : ℝ) * r ^ 2 * y * z +
    (-176/243 : ℝ) * r ^ 2 * y +
    (32/81 : ℝ) * r ^ 2 * z +
    (829/1458 : ℝ) * r ^ 2 +
    (800/729 : ℝ) * r * y * z +
    (592/729 : ℝ) * r * y +
    (-352/729 : ℝ) * r * z +
    (-260/729 : ℝ) * r +
    (-320/729 : ℝ) * y * z +
    (-160/729 : ℝ) * y +
    (128/729 : ℝ) * z +
    (4/243 : ℝ)

private def thCCoeffTerms : List IntTerm := [
  ⟨0, 0, 0, (24 : ℤ)⟩,
  ⟨0, 0, 1, (256 : ℤ)⟩,
  ⟨0, 1, 0, (-320 : ℤ)⟩,
  ⟨0, 1, 1, (-640 : ℤ)⟩,
  ⟨1, 0, 0, (-520 : ℤ)⟩,
  ⟨1, 0, 1, (-704 : ℤ)⟩,
  ⟨1, 1, 0, (1184 : ℤ)⟩,
  ⟨1, 1, 1, (1600 : ℤ)⟩,
  ⟨2, 0, 0, (829 : ℤ)⟩,
  ⟨2, 0, 1, (576 : ℤ)⟩,
  ⟨2, 1, 0, (-1056 : ℤ)⟩,
  ⟨2, 1, 1, (-960 : ℤ)⟩,
  ⟨3, 0, 0, (-150 : ℤ)⟩,
  ⟨3, 0, 1, (-64 : ℤ)⟩,
  ⟨3, 1, 0, (-160 : ℤ)⟩,
  ⟨3, 1, 1, (-320 : ℤ)⟩,
  ⟨4, 0, 0, (-197 : ℤ)⟩,
  ⟨4, 0, 1, (-64 : ℤ)⟩,
  ⟨4, 1, 0, (352 : ℤ)⟩,
  ⟨4, 1, 1, (320 : ℤ)⟩,
  ⟨5, 0, 0, (-16 : ℤ)⟩,
  ⟨6, 0, 0, (30 : ℤ)⟩]

private def thCCoeffNumer (i j k : ℕ) : ℤ :=
  intSparseCoeff thCCoeffTerms i j k

private def thCCoeff (i j k : ℕ) : ℚ :=
  (thCCoeffNumer i j k : ℚ) / 1458

private theorem thCCoeffExpansion (x d u : ℝ) :
    msum thCCoeff 6 1 1 x d u = sparseEval (thCCoeffTerms.map IntTerm.toRat) x d u / 1458 := by
  have he : ∀ i ∈ range 7, ∀ j ∈ range 2, ∀ k ∈ range 2,
      thCCoeffNumer i j k = intSparseCoeff thCCoeffTerms i j k := by intros; rfl
  have hb : ∀ t ∈ thCCoeffTerms, t.i ≤ 6 ∧ t.j ≤ 1 ∧ t.k ≤ 1 := by decide +kernel
  exact msum_intSparse_scaled thCCoeffNumer thCCoeffTerms 1458 6 1 1 he hb x d u

private theorem thCExpansion (r y z : ℝ) :
    msum thCCoeff 6 1 1 r y z = thC r y z := by
  rw [thCCoeffExpansion]
  simp only [sparseEval, IntTerm.toRat, thCCoeffTerms, thC,
    List.map_cons, List.map_nil, List.sum_cons, List.sum_nil]
  push_cast
  ring


private def thCInputData : IntTable :=
  (.node 14 (.node 7 (.node 3 (.node 1 (.leaf (24 : ℤ))
    (.node 1 (.leaf (256 : ℤ))
    (.leaf (-320 : ℤ))))
    (.node 2 (.node 1 (.leaf (-640 : ℤ))
    (.leaf (-520 : ℤ)))
    (.node 1 (.leaf (-704 : ℤ))
    (.leaf (1184 : ℤ)))))
    (.node 3 (.node 1 (.leaf (1600 : ℤ))
    (.node 1 (.leaf (829 : ℤ))
    (.leaf (576 : ℤ))))
    (.node 2 (.node 1 (.leaf (-1056 : ℤ))
    (.leaf (-960 : ℤ)))
    (.node 1 (.leaf (-150 : ℤ))
    (.leaf (-64 : ℤ))))))
    (.node 7 (.node 3 (.node 1 (.leaf (-160 : ℤ))
    (.node 1 (.leaf (-320 : ℤ))
    (.leaf (-197 : ℤ))))
    (.node 2 (.node 1 (.leaf (-64 : ℤ))
    (.leaf (352 : ℤ)))
    (.node 1 (.leaf (320 : ℤ))
    (.leaf (-16 : ℤ)))))
    (.node 3 (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 2 (.node 1 (.leaf (30 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))))))

private def thCInputNumer (i j k : ℕ) : ℤ :=
  thCInputData.get ((i * 2 + j) * 2 + k)

private def thCInput (i j k : ℕ) : ℚ :=
  (thCInputNumer i j k : ℚ) / 1458

private theorem thCInputNumerCorrect :
    ∀ i ∈ range 7, ∀ j ∈ range 2, ∀ k ∈ range 2,
      thCInputNumer i j k = thCCoeffNumer i j k := by
  decide +kernel

private theorem thCInputCorrect :
    ∀ i ∈ range 7, ∀ j ∈ range 2, ∀ k ∈ range 2,
      thCInput i j k = thCCoeff i j k := by
  intro i hi j hj k hk
  exact congrArg (fun v : ℤ => (v : ℚ)/1458)
    (thCInputNumerCorrect i hi j hj k hk)

private def thCW1Data : IntTable :=
  (.node 24 (.node 12 (.node 6 (.node 3 (.node 1 (.leaf (68719476736 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ)))))
    (.node 3 (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (412316860416 : ℤ))
    (.leaf (1073741824 : ℤ))))
    (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))))
    (.node 6 (.node 3 (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (1030792151040 : ℤ))))
    (.node 1 (.leaf (5368709120 : ℤ))
    (.node 1 (.leaf (16777216 : ℤ))
    (.leaf (0 : ℤ)))))
    (.node 3 (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 1 (.leaf (1374389534720 : ℤ))
    (.node 1 (.leaf (10737418240 : ℤ))
    (.leaf (67108864 : ℤ)))))))
    (.node 12 (.node 6 (.node 3 (.node 1 (.leaf (262144 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (0 : ℤ))))
    (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (1030792151040 : ℤ))
    (.leaf (10737418240 : ℤ)))))
    (.node 3 (.node 1 (.leaf (100663296 : ℤ))
    (.node 1 (.leaf (786432 : ℤ))
    (.leaf (4096 : ℤ))))
    (.node 1 (.leaf (0 : ℤ))
    (.node 1 (.leaf (0 : ℤ))
    (.leaf (412316860416 : ℤ))))))
    (.node 6 (.node 3 (.node 1 (.leaf (5368709120 : ℤ))
    (.node 1 (.leaf (67108864 : ℤ))
    (.leaf (786432 : ℤ))))
    (.node 1 (.leaf (8192 : ℤ))
    (.node 1 (.leaf (64 : ℤ))
    (.leaf (0 : ℤ)))))
    (.node 3 (.node 1 (.leaf (68719476736 : ℤ))
    (.node 1 (.leaf (1073741824 : ℤ))
    (.leaf (16777216 : ℤ))))
    (.node 2 (.node 1 (.leaf (262144 : ℤ))
    (.leaf (4096 : ℤ)))
    (.node 1 (.leaf (64 : ℤ))
    (.leaf (1 : ℤ))))))))

private def thCW1Numer (k i : ℕ) : ℤ :=
  thCW1Data.get (k * 7 + i)

private def thCW1 (k i : ℕ) : ℚ :=
  (thCW1Numer k i : ℚ) / 68719476736

private theorem thCW1NumerCorrect :
    ∀ k ∈ range 7, ∀ i ∈ range 7,
      thCW1Numer k i = intTransWeight 6 (0) 1 64 k i := by
  decide +kernel

private theorem thCW1Correct : WeightsCorrect 6 (0 : ℚ) ((1/64) : ℚ) thCW1 := by
  intro k hk i hi
  have he := intTransWeight_cast 6 (0) 1 64 k i
    (by simp only [mem_range] at hi; omega) (by norm_num)
  rw [← thCW1NumerCorrect k hk i hi] at he
  norm_num only [show (64 : ℚ)^6 = 68719476736 by norm_num,
    show (0 : ℚ)/64 = 0 by norm_num,
    show (1 : ℚ)/64 = (1/64) by norm_num] at he
  simpa only [thCW1, neg_div] using he

private def thCW2Data : IntTable :=
  (.node 2 (.node 1 (.leaf (64 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (64 : ℤ))
    (.leaf (1 : ℤ))))

private def thCW2Numer (k i : ℕ) : ℤ :=
  thCW2Data.get (k * 2 + i)

private def thCW2 (k i : ℕ) : ℚ :=
  (thCW2Numer k i : ℚ) / 64

private theorem thCW2NumerCorrect :
    ∀ k ∈ range 2, ∀ i ∈ range 2,
      thCW2Numer k i = intTransWeight 1 (0) 1 64 k i := by
  decide +kernel

private theorem thCW2Correct : WeightsCorrect 1 (0 : ℚ) ((1/64) : ℚ) thCW2 := by
  intro k hk i hi
  have he := intTransWeight_cast 1 (0) 1 64 k i
    (by simp only [mem_range] at hi; omega) (by norm_num)
  rw [← thCW2NumerCorrect k hk i hi] at he
  norm_num only [show (64 : ℚ)^1 = 64 by norm_num,
    show (0 : ℚ)/64 = 0 by norm_num,
    show (1 : ℚ)/64 = (1/64) by norm_num] at he
  simpa only [thCW2, neg_div] using he

private def thCW3Data : IntTable :=
  (.node 2 (.node 1 (.leaf (64 : ℤ))
    (.leaf (0 : ℤ)))
    (.node 1 (.leaf (64 : ℤ))
    (.leaf (1 : ℤ))))

private def thCW3Numer (k i : ℕ) : ℤ :=
  thCW3Data.get (k * 2 + i)

private def thCW3 (k i : ℕ) : ℚ :=
  (thCW3Numer k i : ℚ) / 64

private theorem thCW3NumerCorrect :
    ∀ k ∈ range 2, ∀ i ∈ range 2,
      thCW3Numer k i = intTransWeight 1 (0) 1 64 k i := by
  decide +kernel

private theorem thCW3Correct : WeightsCorrect 1 (0 : ℚ) ((1/64) : ℚ) thCW3 := by
  intro k hk i hi
  have he := intTransWeight_cast 1 (0) 1 64 k i
    (by simp only [mem_range] at hi; omega) (by norm_num)
  rw [← thCW3NumerCorrect k hk i hi] at he
  norm_num only [show (64 : ℚ)^1 = 64 by norm_num,
    show (0 : ℚ)/64 = 0 by norm_num,
    show (1 : ℚ)/64 = (1/64) by norm_num] at he
  simpa only [thCW3, neg_div] using he

private def thCS1Data : IntTable :=
  (.node 14 (.node 7 (.node 3 (.node 1 (.leaf (1649267441664 : ℤ))
    (.node 1 (.leaf (17592186044416 : ℤ))
    (.leaf (-21990232555520 : ℤ))))
    (.node 2 (.node 1 (.leaf (-43980465111040 : ℤ))
    (.leaf (9337258901504 : ℤ)))
    (.node 1 (.leaf (104797202022400 : ℤ))
    (.leaf (-130670085013504 : ℤ)))))
    (.node 3 (.node 1 (.leaf (-262164803747840 : ℤ))
    (.node 1 (.leaf (21961191194624 : ℤ))
    (.leaf (260112883122176 : ℤ))))
    (.node 2 (.node 1 (.leaf (-323514653474816 : ℤ))
    (.leaf (-651133148200960 : ℤ)))
    (.node 1 (.leaf (27457485275136 : ℤ))
    (.leaf (344323216375808 : ℤ))))))
    (.node 7 (.node 3 (.node 1 (.leaf (-427162456817664 : ℤ))
    (.node 1 (.leaf (-862493941432320 : ℤ))
    (.leaf (19238885240832 : ℤ))))
    (.node 2 (.node 1 (.leaf (256381579689984 : ℤ))
    (.leaf (-317246809964544 : ℤ)))
    (.node 1 (.leaf (-642623994593280 : ℤ))
    (.leaf (7159389576192 : ℤ)))))
    (.node 3 (.node 1 (.leaf (101812148895744 : ℤ))
    (.node 1 (.leaf (-125655833640960 : ℤ))
    (.leaf (-255357529620480 : ℤ))))
    (.node 2 (.node 1 (.leaf (1104789875742 : ℤ))
    (.leaf (16845918437376 : ℤ)))
    (.node 1 (.leaf (-20736679477248 : ℤ))
    (.leaf (-42278666895360 : ℤ)))))))

private def thCS1Numer (i j k : ℕ) : ℤ :=
  thCS1Data.get ((i * 2 + j) * 2 + k)

private def thCS1 (i j k : ℕ) : ℚ :=
  (thCS1Numer i j k : ℚ) / 100192997081088

private theorem thCS1NumerCorrect :
    ∀ h ∈ range 7, ∀ j ∈ range 2, ∀ k ∈ range 2,
      thCS1Numer h j k = ∑ i ∈ range 7, thCInputNumer i j k * thCW1Numer h i := by
  decide +kernel

private theorem thCS1Correct : Axis1Correct 6 1 1 thCW1 thCInput thCS1 := by
  intro h hh j hj k hk
  have he := scaled_dot_eq (fun i => thCInputNumer i j k) (thCW1Numer h) (thCS1Numer h j k) 1458 68719476736 6
    (thCS1NumerCorrect h hh j hj k hk)
  norm_num only [show (1458 : ℚ)*68719476736 = 100192997081088 by norm_num] at he
  exact he

private def thCS2Data : IntTable :=
  (.node 14 (.node 7 (.node 3 (.node 1 (.leaf (105553116266496 : ℤ))
    (.node 1 (.leaf (1125899906842624 : ℤ))
    (.leaf (83562883710976 : ℤ))))
    (.node 2 (.node 1 (.leaf (1081919441731584 : ℤ))
    (.leaf (597584569696256 : ℤ)))
    (.node 1 (.leaf (6707020929433600 : ℤ))
    (.leaf (466914484682752 : ℤ)))))
    (.node 3 (.node 1 (.leaf (6444856125685760 : ℤ))
    (.node 1 (.leaf (1405516236455936 : ℤ))
    (.leaf (16647224519819264 : ℤ))))
    (.node 2 (.node 1 (.leaf (1082001582981120 : ℤ))
    (.leaf (15996091371618304 : ℤ)))
    (.node 1 (.leaf (1757279057608704 : ℤ))
    (.leaf (22036685848051712 : ℤ))))))
    (.node 7 (.node 3 (.node 1 (.leaf (1330116600791040 : ℤ))
    (.node 1 (.leaf (21174191906619392 : ℤ))
    (.leaf (1231288655413248 : ℤ))))
    (.node 2 (.node 1 (.leaf (16408421100158976 : ℤ))
    (.leaf (914041845448704 : ℤ)))
    (.node 1 (.leaf (15765797105565696 : ℤ))
    (.leaf (458200932876288 : ℤ)))))
    (.node 3 (.node 1 (.leaf (6515977529327616 : ℤ))
    (.node 1 (.leaf (332545099235328 : ℤ))
    (.leaf (6260619999707136 : ℤ))))
    (.node 2 (.node 1 (.leaf (70706552047488 : ℤ))
    (.leaf (1078138779992064 : ℤ)))
    (.node 1 (.leaf (49969872570240 : ℤ))
    (.leaf (1035860113096704 : ℤ)))))))

private def thCS2Numer (i j k : ℕ) : ℤ :=
  thCS2Data.get ((i * 2 + j) * 2 + k)

private def thCS2 (i j k : ℕ) : ℚ :=
  (thCS2Numer i j k : ℚ) / 6412351813189632

private theorem thCS2NumerCorrect :
    ∀ k ∈ range 7, ∀ j ∈ range 2, ∀ h ∈ range 2,
      thCS2Numer k j h = ∑ i ∈ range 2, thCS1Numer k i h * thCW2Numer j i := by
  decide +kernel

private theorem thCS2Correct : Axis2Correct 6 1 1 thCW2 thCS1 thCS2 := by
  intro k hk j hj h hh
  have he := scaled_dot_eq (fun i => thCS1Numer k i h) (thCW2Numer j) (thCS2Numer k j h) 100192997081088 64 1
    (thCS2NumerCorrect k hk j hj h hh)
  norm_num only [show (100192997081088 : ℚ)*64 = 6412351813189632 by norm_num] at he
  exact he

private def thCS3Data : IntTable :=
  (.node 14 (.node 7 (.node 3 (.node 1 (.leaf (6755399441055744 : ℤ))
    (.node 1 (.leaf (7881299347898368 : ℤ))
    (.leaf (5348024557502464 : ℤ))))
    (.node 2 (.node 1 (.leaf (6429943999234048 : ℤ))
    (.leaf (38245412460560384 : ℤ)))
    (.node 1 (.leaf (44952433389993984 : ℤ))
    (.leaf (29882527019696128 : ℤ)))))
    (.node 3 (.node 1 (.leaf (36327383145381888 : ℤ))
    (.node 1 (.leaf (89953039133179904 : ℤ))
    (.leaf (106600263652999168 : ℤ))))
    (.node 2 (.node 1 (.leaf (69248101310791680 : ℤ))
    (.leaf (85244192682409984 : ℤ)))
    (.node 1 (.leaf (112465859686957056 : ℤ))
    (.leaf (134502545535008768 : ℤ))))))
    (.node 7 (.node 3 (.node 1 (.leaf (85127462450626560 : ℤ))
    (.node 1 (.leaf (106301654357245952 : ℤ))
    (.leaf (78802473946447872 : ℤ))))
    (.node 2 (.node 1 (.leaf (95210895046606848 : ℤ))
    (.leaf (58498678108717056 : ℤ)))
    (.node 1 (.leaf (74264475214282752 : ℤ))
    (.leaf (29324859704082432 : ℤ)))))
    (.node 3 (.node 1 (.leaf (35840837233410048 : ℤ))
    (.node 1 (.leaf (21282886351060992 : ℤ))
    (.leaf (27543506350768128 : ℤ))))
    (.node 2 (.node 1 (.leaf (4525219331039232 : ℤ))
    (.leaf (5603358111031296 : ℤ)))
    (.node 1 (.leaf (3198071844495360 : ℤ))
    (.leaf (4233931957592064 : ℤ)))))))

private def thCS3Numer (i j k : ℕ) : ℤ :=
  thCS3Data.get ((i * 2 + j) * 2 + k)

private def thCS3 (i j k : ℕ) : ℚ :=
  (thCS3Numer i j k : ℚ) / 410390516044136448

private theorem thCS3NumerCorrect :
    ∀ k ∈ range 7, ∀ j ∈ range 2, ∀ h ∈ range 2,
      thCS3Numer k j h = ∑ i ∈ range 2, thCS2Numer k j i * thCW3Numer h i := by
  decide +kernel

private theorem thCS3Correct : Axis3Correct 6 1 1 thCW3 thCS2 thCS3 := by
  intro k hk j hj h hh
  have he := scaled_dot_eq (fun i => thCS2Numer k j i) (thCW3Numer h) (thCS3Numer k j h) 6412351813189632 64 1
    (thCS3NumerCorrect k hk j hj h hh)
  norm_num only [show (6412351813189632 : ℚ)*64 = 410390516044136448 by norm_num] at he
  exact he

private theorem thCNumerSigns :
    ∀ i ∈ range 7, ∀ j ∈ range 2, ∀ k ∈ range 2,
      0 ≤ thCS3Numer i j k := by
  decide +kernel

private theorem thCSigns :
    ∀ i ∈ range 7, ∀ j ∈ range 2, ∀ k ∈ range 2,
      0 ≤ thCS3 i j k := by
  intro i hi j hj k hk
  apply div_nonneg
  · exact_mod_cast thCNumerSigns i hi j hj k hk
  · norm_num


private theorem thCCertificate :
    ∀ i ∈ range 7, ∀ j ∈ range 2, ∀ k ∈ range 2,
      0 ≤ trans3 thCCoeff 6 1 1 (0 : ℚ) ((1/64) : ℚ) (0 : ℚ) ((1/64) : ℚ) (0 : ℚ) ((1/64) : ℚ) i j k := by
  have exactTable := checked_trans3 thCCoeff thCS1 thCS2 thCS3 6 1 1 (0 : ℚ) ((1/64) : ℚ) (0 : ℚ) ((1/64) : ℚ) (0 : ℚ) ((1/64) : ℚ) thCW1 thCW2 thCW3
    thCW1Correct thCW2Correct thCW3Correct
    (axis1Correct_of_table thCInputCorrect thCS1Correct) thCS2Correct thCS3Correct
  intro i hi j hj k hk
  rw [← exactTable i hi j hj k hk]
  exact thCSigns i hi j hj k hk

private theorem thC_nonneg {r y z : ℝ}
    (hr0 : (0 : ℝ) ≤ r) (hr1 : r ≤ (1/64 : ℝ))
    (hy0 : (0 : ℝ) ≤ y) (hy1 : y ≤ (1/64 : ℝ))
    (hz0 : (0 : ℝ) ≤ z) (hz1 : z ≤ (1/64 : ℝ)) : 0 ≤ thC r y z := by
  have h := msum_nonneg_on_box thCCoeff 6 1 1 (x := r) (y := y) (z := z)
    (by norm_num) (by norm_num) (by norm_num)
    (by push_cast; linarith) (by push_cast; linarith)
    (by push_cast; linarith) (by push_cast; linarith)
    (by push_cast; linarith) (by push_cast; linarith) thCCertificate
  rwa [thCExpansion] at h


private theorem thIdentity (r y z : ℝ) :
    highTHTarget r (1-y) z = thA r y z*r^2+thB r y z*y^2+thC r y z*z^2/4+
      2*thV r y z*(r-z/2)^2+2*thW r y z*(y-z/2)^2+2*thU r y z*r*y := by
  simp only [highTHTarget,thA,thB,thC,thU,thV,thW]
  ring

theorem highTHLocal {x d u : ℝ}
    (hx0 : 0 ≤ x) (hx1 : x ≤ (1/64 : ℝ))
    (hd0 : (63/64 : ℝ) ≤ d) (hd1 : d ≤ 1)
    (hu0 : 0 ≤ u) (hu1 : u ≤ (1/64 : ℝ)) : 0 ≤ highTHTarget x d u := by
  have hy0 : 0 ≤ 1-d := by linarith
  have hy1 : 1-d ≤ (1/64 : ℝ) := by linarith
  have hA := thA_nonneg hx0 hx1 hy0 hy1 hu0 hu1
  have hB := thB_nonneg hx0 hx1 hy0 hy1 hu0 hu1
  have hC := thC_nonneg hx0 hx1 hy0 hy1 hu0 hu1
  have hU := thU_nonneg hx0 hx1 hy0 hy1 hu0 hu1
  have hV := thV_nonneg hx0 hx1 hy0 hy1 hu0 hu1
  have hW := thW_nonneg hx0 hx1 hy0 hy1 hu0 hu1
  have hid := thIdentity x (1-d) u
  rw [sub_sub_cancel] at hid
  rw [hid]
  positivity

end Taeyoung.Methods.Atlas126
