/-
# High-density theorem — `eq:constant-A` finite sweep, shared core (`app:constants`)

Hand-written foundation for the `63 ≤ m ≤ 499` finite sweep that closes `eq:constant-A` on the
residual strip-left A-branch (`θ = r/m ≤ 1/6`).  The per-`m` files (`M0xx.lean`) and the aggregate
(`Aggregate.lean`) are GENERATED by `app_constants_finite_sweep.py`; do not hand-edit them.

Two pieces live here:

* `gRatA m r` — the **fully rational** value of the sweep target `g(m,r) = (99/100m)·P(θ)·B₀(θ)^m`,
  with `B₀(θ)^m` already collapsed to integer powers (`θ = r/m`, `n = m−2r`):
      B₀(r/m)^m = (7/6)^{m-2r} · (m/(8m−24r))^r · (6(m+2r)/(5m+12r))^m.
  Every per-pair obligation is `1 ≤ gRatA m r`, a pure `norm_num` rational fact.

* `constA_B0pow_eq` — the **only** `rpow` work of the sweep: the collapse identity above, proved via
  `mul_pow` + `rpow_npow_eq`/`rpow_neg_npow_eq` (this is exactly the `hB1` step of
  `diagKernel_nonneg_strip_left_b`, specialised to the case-A third factor `(1/2+θ)/(5/12+θ)`).
  `constA_of_gRatA` then lifts a rational `1 ≤ gRatA m r` to `eq:constant-A` in `B₀` form, matching
  the shape of `constA_m500`.
-/

import OddCycleBound.HighDensity.M6TailRatio
import OddCycleBound.HighDensity.AppConstantsB0

namespace OddCycleBound.HighDensity

/-- The exact-rational sweep target `g(m,r) = (99/100m)·P(r/m)·B₀(r/m)^m` with `B₀^m` collapsed to
integer powers.  Each admissible case-A pair satisfies `1 ≤ gRatA m r` (a pure `norm_num` fact). -/
noncomputable def gRatA (m r : ℕ) : ℝ :=
  99 / (100 * (m : ℝ))
    * ((2 / 3 - 2 * ((r : ℝ) / m)) / (((r : ℝ) / m) * (1 / 2 - 2 * ((r : ℝ) / m)) ^ 2))
    * ((7 / 6 : ℝ) ^ (m - 2 * r)
        * ((m : ℝ) / (8 * (m : ℝ) - 24 * (r : ℝ))) ^ r
        * ((6 * ((m : ℝ) + 2 * (r : ℝ))) / (5 * (m : ℝ) + 12 * (r : ℝ))) ^ m)

/-- **The `B₀(r/m)^m` integer-power collapse** (the sole `rpow` step of the finite sweep).  For
`0 < m` and `6r < m` (so `θ = r/m < 1/6`, in particular `8m − 24r > 0` and `2r ≤ m`),
`B₀(r/m)^m = (7/6)^{m-2r} · (m/(8m−24r))^r · (6(m+2r)/(5m+12r))^m`. -/
lemma constA_B0pow_eq {m r : ℕ} (hm : 0 < m) (h6r : 6 * r < m) :
    (B0 ((r : ℝ) / m)) ^ m
      = (7 / 6 : ℝ) ^ (m - 2 * r)
        * ((m : ℝ) / (8 * (m : ℝ) - 24 * (r : ℝ))) ^ r
        * ((6 * ((m : ℝ) + 2 * (r : ℝ))) / (5 * (m : ℝ) + 12 * (r : ℝ))) ^ m := by
  have hmR : (0 : ℝ) < (m : ℝ) := by exact_mod_cast hm
  have hm0 : (m : ℝ) ≠ 0 := ne_of_gt hmR
  have hrR : (0 : ℝ) ≤ (r : ℝ) := Nat.cast_nonneg r
  have h6rR : 6 * (r : ℝ) < (m : ℝ) := by exact_mod_cast h6r
  have h2rm : 2 * r ≤ m := by omega
  -- `8 − 24θ > 0`  (θ = r/m < 1/6 since 6r < m)
  have hθ16 : (r : ℝ) / m < 1 / 6 := by rw [div_lt_iff₀ hmR]; nlinarith [h6rR]
  have hx2 : (0 : ℝ) < 8 - 24 * ((r : ℝ) / m) := by nlinarith [hθ16]
  -- exponent identities feeding the rpow collapses
  have hk1 : (1 - 2 * ((r : ℝ) / m)) * (m : ℝ) = ((m - 2 * r : ℕ) : ℝ) := by
    rw [Nat.cast_sub h2rm]; push_cast; field_simp
  have hk2 : ((r : ℝ) / m) * (m : ℝ) = (r : ℝ) := by field_simp
  have E1 : ((7 / 6 : ℝ) ^ (1 - 2 * ((r : ℝ) / m))) ^ m = (7 / 6 : ℝ) ^ (m - 2 * r) :=
    rpow_npow_eq (by norm_num) hk1
  have E2 : ((8 - 24 * ((r : ℝ) / m)) ^ (-((r : ℝ) / m))) ^ m
      = (1 / (8 - 24 * ((r : ℝ) / m))) ^ r := rpow_neg_npow_eq hx2 hk2
  unfold B0
  rw [mul_pow, mul_pow, E1, E2]
  -- rewrite the two rational bases into their cleared integer forms
  rw [show (1 : ℝ) / (8 - 24 * ((r : ℝ) / m)) = (m : ℝ) / (8 * (m : ℝ) - 24 * (r : ℝ)) from by
        rw [div_eq_div_iff (ne_of_gt hx2)
          (ne_of_gt (by nlinarith [h6rR] : (0 : ℝ) < 8 * (m : ℝ) - 24 * (r : ℝ)))]
        field_simp,
      show (1 / 2 + (r : ℝ) / m) / (5 / 12 + (r : ℝ) / m)
          = (6 * ((m : ℝ) + 2 * (r : ℝ))) / (5 * (m : ℝ) + 12 * (r : ℝ)) from by
        rw [div_eq_div_iff (by positivity) (by positivity)]
        field_simp; ring]

/-- Lift a rational `1 ≤ gRatA m r` to `eq:constant-A` in `B₀` form, matching `constA_m500`'s shape.
Uses only `constA_B0pow_eq`; the `P(θ)` factor is identical on both sides. -/
lemma constA_of_gRatA {m r : ℕ} (hm : 0 < m) (h6r : 6 * r < m) (h : 1 ≤ gRatA m r) :
    1 ≤ 99 / (100 * (m : ℝ))
        * ((2 / 3 - 2 * ((r : ℝ) / m)) / (((r : ℝ) / m) * (1 / 2 - 2 * ((r : ℝ) / m)) ^ 2))
        * (B0 ((r : ℝ) / m)) ^ m := by
  rw [constA_B0pow_eq hm h6r]
  exact h

end OddCycleBound.HighDensity
