/-
# `eq:constant-A` finite sweep — m = 87  (GENERATED by app_constants_finite_sweep.py; do not hand-edit)

One lemma `constA_m87` covering every admissible case-A pair `(87, r)` (`2 <= r`, `6r < 87`,
i.e. `theta = r/87 <= 1/6`), each discharged by `norm_num` on the exact-rational collapsed value
`gRatA 87 r`.
-/

import OddCycleBound.HighDensity.Sweep.Core

namespace OddCycleBound.HighDensity

set_option exponentiation.threshold 600 in
/-- `eq:constant-A` for every admissible case-A pair `(87, r)`. -/
theorem constA_m87 {r : ℕ} (hr2 : 2 ≤ r) (h6r : 6 * r < 87) : 1 ≤ gRatA 87 r := by
  have hub : r ≤ 14 := by omega
  interval_cases r <;> norm_num [gRatA]

end OddCycleBound.HighDensity
