/-
# `eq:constant-A` finite sweep — m = 109  (GENERATED by app_constants_finite_sweep.py; do not hand-edit)

One lemma `constA_m109` covering every admissible case-A pair `(109, r)` (`2 <= r`, `6r < 109`,
i.e. `theta = r/109 <= 1/6`), each discharged by `norm_num` on the exact-rational collapsed value
`gRatA 109 r`.
-/

import OddCycleBound.HighDensity.Sweep.Core

namespace OddCycleBound.HighDensity

set_option exponentiation.threshold 600 in
/-- `eq:constant-A` for every admissible case-A pair `(109, r)`. -/
theorem constA_m109 {r : ℕ} (hr2 : 2 ≤ r) (h6r : 6 * r < 109) : 1 ≤ gRatA 109 r := by
  have hub : r ≤ 18 := by omega
  interval_cases r <;> norm_num [gRatA]

end OddCycleBound.HighDensity
