/-
# `eq:constant-A` finite sweep — m = 113  (GENERATED by app_constants_finite_sweep.py; do not hand-edit)

One lemma `constA_m113` covering every admissible case-A pair `(113, r)` (`2 <= r`, `6r < 113`,
i.e. `theta = r/113 <= 1/6`), each discharged by `norm_num` on the exact-rational collapsed value
`gRatA 113 r`.
-/

import OddCycleBound.HighDensity.Sweep.Core

namespace OddCycleBound.HighDensity

set_option exponentiation.threshold 600 in
/-- `eq:constant-A` for every admissible case-A pair `(113, r)`. -/
theorem constA_m113 {r : ℕ} (hr2 : 2 ≤ r) (h6r : 6 * r < 113) : 1 ≤ gRatA 113 r := by
  have hub : r ≤ 18 := by omega
  interval_cases r <;> norm_num [gRatA]

end OddCycleBound.HighDensity
