/-
# `eq:constant-A` finite sweep — m = 117  (GENERATED by app_constants_finite_sweep.py; do not hand-edit)

One lemma `constA_m117` covering every admissible case-A pair `(117, r)` (`2 <= r`, `6r < 117`,
i.e. `theta = r/117 <= 1/6`), each discharged by `norm_num` on the exact-rational collapsed value
`gRatA 117 r`.
-/

import OddCycleBound.HighDensity.Sweep.Core

namespace OddCycleBound.HighDensity

set_option exponentiation.threshold 600 in
/-- `eq:constant-A` for every admissible case-A pair `(117, r)`. -/
theorem constA_m117 {r : ℕ} (hr2 : 2 ≤ r) (h6r : 6 * r < 117) : 1 ≤ gRatA 117 r := by
  have hub : r ≤ 19 := by omega
  interval_cases r <;> norm_num [gRatA]

end OddCycleBound.HighDensity
