/-
# `eq:constant-A` finite sweep — m = 133  (GENERATED by app_constants_finite_sweep.py; do not hand-edit)

One lemma `constA_m133` covering every admissible case-A pair `(133, r)` (`2 <= r`, `6r < 133`,
i.e. `theta = r/133 <= 1/6`), each discharged by `norm_num` on the exact-rational collapsed value
`gRatA 133 r`.
-/

import OddCycleBound.HighDensity.Sweep.Core

namespace OddCycleBound.HighDensity

set_option exponentiation.threshold 600 in
/-- `eq:constant-A` for every admissible case-A pair `(133, r)`. -/
theorem constA_m133 {r : ℕ} (hr2 : 2 ≤ r) (h6r : 6 * r < 133) : 1 ≤ gRatA 133 r := by
  have hub : r ≤ 22 := by omega
  interval_cases r <;> norm_num [gRatA]

end OddCycleBound.HighDensity
