/-
# `eq:constant-A` finite sweep — m = 137  (GENERATED by app_constants_finite_sweep.py; do not hand-edit)

One lemma `constA_m137` covering every admissible case-A pair `(137, r)` (`2 <= r`, `6r < 137`,
i.e. `theta = r/137 <= 1/6`), each discharged by `norm_num` on the exact-rational collapsed value
`gRatA 137 r`.
-/

import OddCycleBound.HighDensity.Sweep.Core

namespace OddCycleBound.HighDensity

set_option exponentiation.threshold 600 in
/-- `eq:constant-A` for every admissible case-A pair `(137, r)`. -/
theorem constA_m137 {r : ℕ} (hr2 : 2 ≤ r) (h6r : 6 * r < 137) : 1 ≤ gRatA 137 r := by
  have hub : r ≤ 22 := by omega
  interval_cases r <;> norm_num [gRatA]

end OddCycleBound.HighDensity
