/-
# `eq:constant-A` finite sweep — m = 145  (GENERATED by app_constants_finite_sweep.py; do not hand-edit)

One lemma `constA_m145` covering every admissible case-A pair `(145, r)` (`2 <= r`, `6r < 145`,
i.e. `theta = r/145 <= 1/6`), each discharged by `norm_num` on the exact-rational collapsed value
`gRatA 145 r`.
-/

import OddCycleBound.HighDensity.Sweep.Core

namespace OddCycleBound.HighDensity

set_option exponentiation.threshold 600 in
/-- `eq:constant-A` for every admissible case-A pair `(145, r)`. -/
theorem constA_m145 {r : ℕ} (hr2 : 2 ≤ r) (h6r : 6 * r < 145) : 1 ≤ gRatA 145 r := by
  have hub : r ≤ 24 := by omega
  interval_cases r <;> norm_num [gRatA]

end OddCycleBound.HighDensity
