/-
# `eq:constant-A` finite sweep — m = 149  (GENERATED by app_constants_finite_sweep.py; do not hand-edit)

One lemma `constA_m149` covering every admissible case-A pair `(149, r)` (`2 <= r`, `6r < 149`,
i.e. `theta = r/149 <= 1/6`), each discharged by `norm_num` on the exact-rational collapsed value
`gRatA 149 r`.
-/

import OddCycleBound.HighDensity.Sweep.Core

namespace OddCycleBound.HighDensity

set_option exponentiation.threshold 600 in
/-- `eq:constant-A` for every admissible case-A pair `(149, r)`. -/
theorem constA_m149 {r : ℕ} (hr2 : 2 ≤ r) (h6r : 6 * r < 149) : 1 ≤ gRatA 149 r := by
  have hub : r ≤ 24 := by omega
  interval_cases r <;> norm_num [gRatA]

end OddCycleBound.HighDensity
