/-
# `eq:constant-A` finite sweep — m = 151  (GENERATED by app_constants_finite_sweep.py; do not hand-edit)

One lemma `constA_m151` covering every admissible case-A pair `(151, r)` (`2 <= r`, `6r < 151`,
i.e. `theta = r/151 <= 1/6`), each discharged by `norm_num` on the exact-rational collapsed value
`gRatA 151 r`.
-/

import OddCycleBound.HighDensity.Sweep.Core

namespace OddCycleBound.HighDensity

set_option exponentiation.threshold 600 in
/-- `eq:constant-A` for every admissible case-A pair `(151, r)`. -/
theorem constA_m151 {r : ℕ} (hr2 : 2 ≤ r) (h6r : 6 * r < 151) : 1 ≤ gRatA 151 r := by
  have hub : r ≤ 25 := by omega
  interval_cases r <;> norm_num [gRatA]

end OddCycleBound.HighDensity
