/-
# `eq:constant-A` finite sweep — m = 175  (GENERATED by app_constants_finite_sweep.py; do not hand-edit)

One lemma `constA_m175` covering every admissible case-A pair `(175, r)` (`2 <= r`, `6r < 175`,
i.e. `theta = r/175 <= 1/6`), each discharged by `norm_num` on the exact-rational collapsed value
`gRatA 175 r`.
-/

import OddCycleBound.HighDensity.Sweep.Core

namespace OddCycleBound.HighDensity

set_option exponentiation.threshold 600 in
/-- `eq:constant-A` for every admissible case-A pair `(175, r)`. -/
theorem constA_m175 {r : ℕ} (hr2 : 2 ≤ r) (h6r : 6 * r < 175) : 1 ≤ gRatA 175 r := by
  have hub : r ≤ 29 := by omega
  interval_cases r <;> norm_num [gRatA]

end OddCycleBound.HighDensity
