/-
# `eq:constant-A` finite sweep — m = 233  (GENERATED by app_constants_finite_sweep.py; do not hand-edit)

One lemma `constA_m233` covering every admissible case-A pair `(233, r)` (`2 <= r`, `6r < 233`,
i.e. `theta = r/233 <= 1/6`), each discharged by `norm_num` on the exact-rational collapsed value
`gRatA 233 r`.
-/

import OddCycleBound.HighDensity.Sweep.Core

namespace OddCycleBound.HighDensity

set_option exponentiation.threshold 600 in
/-- `eq:constant-A` for every admissible case-A pair `(233, r)`. -/
theorem constA_m233 {r : ℕ} (hr2 : 2 ≤ r) (h6r : 6 * r < 233) : 1 ≤ gRatA 233 r := by
  have hub : r ≤ 38 := by omega
  interval_cases r <;> norm_num [gRatA]

end OddCycleBound.HighDensity
