/-
# `eq:constant-A` finite sweep — m = 235  (GENERATED by app_constants_finite_sweep.py; do not hand-edit)

One lemma `constA_m235` covering every admissible case-A pair `(235, r)` (`2 <= r`, `6r < 235`,
i.e. `theta = r/235 <= 1/6`), each discharged by `norm_num` on the exact-rational collapsed value
`gRatA 235 r`.
-/

import OddCycleBound.HighDensity.Sweep.Core

namespace OddCycleBound.HighDensity

set_option exponentiation.threshold 600 in
/-- `eq:constant-A` for every admissible case-A pair `(235, r)`. -/
theorem constA_m235 {r : ℕ} (hr2 : 2 ≤ r) (h6r : 6 * r < 235) : 1 ≤ gRatA 235 r := by
  have hub : r ≤ 39 := by omega
  interval_cases r <;> norm_num [gRatA]

end OddCycleBound.HighDensity
