/-
# `eq:constant-A` finite sweep — m = 279  (GENERATED by app_constants_finite_sweep.py; do not hand-edit)

One lemma `constA_m279` covering every admissible case-A pair `(279, r)` (`2 <= r`, `6r < 279`,
i.e. `theta = r/279 <= 1/6`), each discharged by `norm_num` on the exact-rational collapsed value
`gRatA 279 r`.
-/

import OddCycleBound.HighDensity.Sweep.Core

namespace OddCycleBound.HighDensity

set_option exponentiation.threshold 600 in
/-- `eq:constant-A` for every admissible case-A pair `(279, r)`. -/
theorem constA_m279 {r : ℕ} (hr2 : 2 ≤ r) (h6r : 6 * r < 279) : 1 ≤ gRatA 279 r := by
  have hub : r ≤ 46 := by omega
  interval_cases r <;> norm_num [gRatA]

end OddCycleBound.HighDensity
