/-
# `eq:constant-A` finite sweep — m = 299  (GENERATED by app_constants_finite_sweep.py; do not hand-edit)

One lemma `constA_m299` covering every admissible case-A pair `(299, r)` (`2 <= r`, `6r < 299`,
i.e. `theta = r/299 <= 1/6`), each discharged by `norm_num` on the exact-rational collapsed value
`gRatA 299 r`.
-/

import OddCycleBound.HighDensity.Sweep.Core

namespace OddCycleBound.HighDensity

set_option exponentiation.threshold 600 in
/-- `eq:constant-A` for every admissible case-A pair `(299, r)`. -/
theorem constA_m299 {r : ℕ} (hr2 : 2 ≤ r) (h6r : 6 * r < 299) : 1 ≤ gRatA 299 r := by
  have hub : r ≤ 49 := by omega
  interval_cases r <;> norm_num [gRatA]

end OddCycleBound.HighDensity
