/-
# `eq:constant-A` finite sweep — m = 311  (GENERATED by app_constants_finite_sweep.py; do not hand-edit)

One lemma `constA_m311` covering every admissible case-A pair `(311, r)` (`2 <= r`, `6r < 311`,
i.e. `theta = r/311 <= 1/6`), each discharged by `norm_num` on the exact-rational collapsed value
`gRatA 311 r`.
-/

import OddCycleBound.HighDensity.Sweep.Core

namespace OddCycleBound.HighDensity

set_option exponentiation.threshold 600 in
/-- `eq:constant-A` for every admissible case-A pair `(311, r)`. -/
theorem constA_m311 {r : ℕ} (hr2 : 2 ≤ r) (h6r : 6 * r < 311) : 1 ≤ gRatA 311 r := by
  have hub : r ≤ 51 := by omega
  interval_cases r <;> norm_num [gRatA]

end OddCycleBound.HighDensity
