/-
# `eq:constant-A` finite sweep — m = 383  (GENERATED by app_constants_finite_sweep.py; do not hand-edit)

One lemma `constA_m383` covering every admissible case-A pair `(383, r)` (`2 <= r`, `6r < 383`,
i.e. `theta = r/383 <= 1/6`), each discharged by `norm_num` on the exact-rational collapsed value
`gRatA 383 r`.
-/

import OddCycleBound.HighDensity.Sweep.Core

namespace OddCycleBound.HighDensity

set_option exponentiation.threshold 600 in
/-- `eq:constant-A` for every admissible case-A pair `(383, r)`. -/
theorem constA_m383 {r : ℕ} (hr2 : 2 ≤ r) (h6r : 6 * r < 383) : 1 ≤ gRatA 383 r := by
  have hub : r ≤ 63 := by omega
  interval_cases r <;> norm_num [gRatA]

end OddCycleBound.HighDensity
