/-
# `eq:constant-A` finite sweep — m = 449  (GENERATED by app_constants_finite_sweep.py; do not hand-edit)

One lemma `constA_m449` covering every admissible case-A pair `(449, r)` (`2 <= r`, `6r < 449`,
i.e. `theta = r/449 <= 1/6`), each discharged by `norm_num` on the exact-rational collapsed value
`gRatA 449 r`.
-/

import OddCycleBound.HighDensity.Sweep.Core

namespace OddCycleBound.HighDensity

set_option exponentiation.threshold 600 in
/-- `eq:constant-A` for every admissible case-A pair `(449, r)`. -/
theorem constA_m449 {r : ℕ} (hr2 : 2 ≤ r) (h6r : 6 * r < 449) : 1 ≤ gRatA 449 r := by
  have hub : r ≤ 74 := by omega
  interval_cases r <;> norm_num [gRatA]

end OddCycleBound.HighDensity
