/-
# `eq:constant-A` finite sweep — m = 459  (GENERATED by app_constants_finite_sweep.py; do not hand-edit)

One lemma `constA_m459` covering every admissible case-A pair `(459, r)` (`2 <= r`, `6r < 459`,
i.e. `theta = r/459 <= 1/6`), each discharged by `norm_num` on the exact-rational collapsed value
`gRatA 459 r`.
-/

import OddCycleBound.HighDensity.Sweep.Core

namespace OddCycleBound.HighDensity

set_option exponentiation.threshold 600 in
/-- `eq:constant-A` for every admissible case-A pair `(459, r)`. -/
theorem constA_m459 {r : ℕ} (hr2 : 2 ≤ r) (h6r : 6 * r < 459) : 1 ≤ gRatA 459 r := by
  have hub : r ≤ 76 := by omega
  interval_cases r <;> norm_num [gRatA]

end OddCycleBound.HighDensity
