/-
# `eq:constant-A` finite sweep — m = 463  (GENERATED by app_constants_finite_sweep.py; do not hand-edit)

One lemma `constA_m463` covering every admissible case-A pair `(463, r)` (`2 <= r`, `6r < 463`,
i.e. `theta = r/463 <= 1/6`), each discharged by `norm_num` on the exact-rational collapsed value
`gRatA 463 r`.
-/

import OddCycleBound.HighDensity.Sweep.Core

namespace OddCycleBound.HighDensity

set_option exponentiation.threshold 600 in
/-- `eq:constant-A` for every admissible case-A pair `(463, r)`. -/
theorem constA_m463 {r : ℕ} (hr2 : 2 ≤ r) (h6r : 6 * r < 463) : 1 ≤ gRatA 463 r := by
  have hub : r ≤ 77 := by omega
  interval_cases r <;> norm_num [gRatA]

end OddCycleBound.HighDensity
