/-
# `eq:constant-A` finite sweep — m = 465  (GENERATED by app_constants_finite_sweep.py; do not hand-edit)

One lemma `constA_m465` covering every admissible case-A pair `(465, r)` (`2 <= r`, `6r < 465`,
i.e. `theta = r/465 <= 1/6`), each discharged by `norm_num` on the exact-rational collapsed value
`gRatA 465 r`.
-/

import OddCycleBound.HighDensity.Sweep.Core

namespace OddCycleBound.HighDensity

set_option exponentiation.threshold 600 in
/-- `eq:constant-A` for every admissible case-A pair `(465, r)`. -/
theorem constA_m465 {r : ℕ} (hr2 : 2 ≤ r) (h6r : 6 * r < 465) : 1 ≤ gRatA 465 r := by
  have hub : r ≤ 77 := by omega
  interval_cases r <;> norm_num [gRatA]

end OddCycleBound.HighDensity
