/-
# `eq:constant-A` finite sweep — m = 475  (GENERATED by app_constants_finite_sweep.py; do not hand-edit)

One lemma `constA_m475` covering every admissible case-A pair `(475, r)` (`2 <= r`, `6r < 475`,
i.e. `theta = r/475 <= 1/6`), each discharged by `norm_num` on the exact-rational collapsed value
`gRatA 475 r`.
-/

import OddCycleBound.HighDensity.Sweep.Core

namespace OddCycleBound.HighDensity

set_option exponentiation.threshold 600 in
/-- `eq:constant-A` for every admissible case-A pair `(475, r)`. -/
theorem constA_m475 {r : ℕ} (hr2 : 2 ≤ r) (h6r : 6 * r < 475) : 1 ≤ gRatA 475 r := by
  have hub : r ≤ 79 := by omega
  interval_cases r <;> norm_num [gRatA]

end OddCycleBound.HighDensity
