/-
# `eq:constant-A` finite sweep — m = 479  (GENERATED by app_constants_finite_sweep.py; do not hand-edit)

One lemma `constA_m479` covering every admissible case-A pair `(479, r)` (`2 <= r`, `6r < 479`,
i.e. `theta = r/479 <= 1/6`), each discharged by `norm_num` on the exact-rational collapsed value
`gRatA 479 r`.
-/

import OddCycleBound.HighDensity.Sweep.Core

namespace OddCycleBound.HighDensity

set_option exponentiation.threshold 600 in
/-- `eq:constant-A` for every admissible case-A pair `(479, r)`. -/
theorem constA_m479 {r : ℕ} (hr2 : 2 ≤ r) (h6r : 6 * r < 479) : 1 ≤ gRatA 479 r := by
  have hub : r ≤ 79 := by omega
  interval_cases r <;> norm_num [gRatA]

end OddCycleBound.HighDensity
