/-
Hfin dispatcher for m = 9 (GENERATED by hfin_certs.py --gen; do not edit).
-/
import OddCycleBound.HighDensity.Hfin.P009R02

namespace OddCycleBound.HighDensity

/-- Dispatcher for `m = 9`: all residual-strip pairs `(m,r)`. -/
theorem finKernel_M9 {q l : ℝ} (r : ℕ) (hr2 : 2 ≤ r) (hres : 2*r < 9 - 2*r)
    (hq0 : 0 ≤ q) (hq : q ≤ 1/3) (hl0 : 0 < l) (hlr : l < q + (r : ℝ)/9) :
    0 ≤ diagKernel 9 r q l := by
  have hub : r ≤ 2 := by omega
  interval_cases r
  · exact finKernel_9_2 hq0 hq hl0 (by push_cast at hlr; exact hlr)

end OddCycleBound.HighDensity
