-- EXCERPT ONLY -- lean/OddCycleBound/RegionII/Certificate/Generated.lean
-- full file: 94198 bytes / 6231 lines of generated certificate data.
-- Long lines are cut at 300 chars. Regenerate via archive/cert-toolkit/; full text in git (archive/README.md).

import OddCycleBound.RegionII.Certificate.Tree

/-! Deterministically generated by `cert_scripts/regionII/emit_certificates.py`. -/

namespace OddCycleBound.RegionII.Certificate

def zoneBTokens : Array RegionCertToken := #[
  .splitK,
  .splitK,
  .splitK,
  .splitE,
  .splitK,
  .splitE,
  .splitK,
  .bVerified,
  .splitE,
  .bVerified,
  .bVerified,
  .bVerified,
  .splitE,
  .splitE,
  .bVerified,
  .bVerified,
  .bVerified,
  .splitK,
  .bSkipZoneC,
  .splitE,
  .splitK,
  .bSkipZoneC,
  .bVerified,
  .bSkipZoneC,
  .splitE,
  .splitE,
  .splitE,
  .splitE,
  .bVerified,
  .bVerified,
  .bVerified,
  .bVerified,
  .bVerified,

-- ... truncated ...
