import EvenCycleApex.Certificate.Checks.Witness

/-!
# Kernel check: the certificate of `meanThree_mean,3`

`prop:checked-data` for this target, evaluated by the kernel (`decide +kernel`): the 19
factorizations (`meanThree_ldl*`), identity (C) as accumulated totals (`meanThree_acc*` for the groups, in row
ranges for `r = 4`; `meanThree_t*` for the target in chunks of 1024 monomials, witnesses and totals
together), and the final comparison `meanThree_fin`.  Then `thm:certificate-inequalities` for this target:
`meanThree_nonneg`.

Generated by `tools/gen_cert_data.py checks`; do not edit.  The files `Checks/{MeanThree,Neg,Pos}`
import each other in a chain so that `lake build` evaluates them one at a time (kernel memory).
-/

set_option maxRecDepth 100000

namespace EvenCycleApex.Checks

open EvenCycleApex Certificate

theorem meanThree_ldl0 : ∀ j < schema0.types.length, meanThreeG0.ldlOK j = true := by
  decide +kernel

theorem meanThree_ldl1 : ∀ j < schema1.types.length, meanThreeG1.ldlOK j = true := by
  decide +kernel

theorem meanThree_ldl2 : ∀ j < schema2.types.length, meanThreeG2.ldlOK j = true := by
  decide +kernel

theorem meanThree_ldl3 : ∀ j < schema3.types.length, meanThreeG3.ldlOK j = true := by
  decide +kernel

theorem meanThree_ldl4 : ∀ j < schema4.types.length, meanThreeG4.ldlOK j = true := by
  decide +kernel

theorem meanThree_acc0 : meanThreeG0.accRows 0 meanThreeG0.S.feats.length 0 0 0
    (claimOK Data.MeanThree.claim0_0.1 Data.MeanThree.claim0_0.2.1 Data.MeanThree.claim0_0.2.2) = true := by
  decide +kernel

theorem meanThree_acc1 : meanThreeG1.accRows 0 meanThreeG1.S.feats.length 0 0 0
    (claimOK Data.MeanThree.claim1_0.1 Data.MeanThree.claim1_0.2.1 Data.MeanThree.claim1_0.2.2) = true := by
  decide +kernel

theorem meanThree_acc2 : meanThreeG2.accRows 0 meanThreeG2.S.feats.length 0 0 0
    (claimOK Data.MeanThree.claim2_0.1 Data.MeanThree.claim2_0.2.1 Data.MeanThree.claim2_0.2.2) = true := by
  decide +kernel

theorem meanThree_acc3 : meanThreeG3.accRows 0 meanThreeG3.S.feats.length 0 0 0
    (claimOK Data.MeanThree.claim3_0.1 Data.MeanThree.claim3_0.2.1 Data.MeanThree.claim3_0.2.2) = true := by
  decide +kernel

theorem meanThree_acc4_0 : meanThreeG4.accRows 0 5 0 0 0
    (claimOK Data.MeanThree.claim4_0.1 Data.MeanThree.claim4_0.2.1 Data.MeanThree.claim4_0.2.2) = true := by
  decide +kernel

theorem meanThree_acc4_5 : meanThreeG4.accRows 5 5 0 0 0
    (claimOK Data.MeanThree.claim4_5.1 Data.MeanThree.claim4_5.2.1 Data.MeanThree.claim4_5.2.2) = true := by
  decide +kernel

theorem meanThree_acc4_10 : meanThreeG4.accRows 10 5 0 0 0
    (claimOK Data.MeanThree.claim4_10.1 Data.MeanThree.claim4_10.2.1 Data.MeanThree.claim4_10.2.2) = true := by
  decide +kernel

theorem meanThree_t0 : tchunk Data.rep 1024 targetMeanThree 0 Data.MeanThree.Wt_0 Data.MeanThree.claimT_0 = true := by
  decide +kernel

theorem meanThree_t1 : tchunk Data.rep 1024 targetMeanThree 1 Data.MeanThree.Wt_1 Data.MeanThree.claimT_1 = true := by
  decide +kernel

theorem meanThree_chunks : ∀ k < Data.MeanThree.WtChunks.length,
    tchunk Data.rep 1024 targetMeanThree k (Data.MeanThree.WtChunks.getD k []) (Data.MeanThree.claimsT.getD k (0, 0, 0)) = true := by
  intro k hk
  change k < 2 at hk
  interval_cases k
  · exact meanThree_t0
  · exact meanThree_t1

theorem meanThree_end : targetMeanThree.drop (1024 * Data.MeanThree.WtChunks.length) = [] := by
  decide +kernel

/-- The claimed weighted totals of the five groups. -/
def meanThreeClaims : List (ℕ × (ℕ × ℕ × ℕ)) :=
  [(meanThreeG0.S.weight, Data.MeanThree.claim0_0), (meanThreeG1.S.weight, Data.MeanThree.claim1_0),
   (meanThreeG2.S.weight, Data.MeanThree.claim2_0), (meanThreeG3.S.weight, Data.MeanThree.claim3_0),
   (meanThreeG4.S.weight, add3 (add3 Data.MeanThree.claim4_0 Data.MeanThree.claim4_5) Data.MeanThree.claim4_10)]

theorem meanThree_fin : totalsOK certScale (sum3 Data.MeanThree.claimsT) meanThreeClaims = true := by
  decide +kernel

theorem meanThree_valid : ∀ G ∈ meanThreeGroups, G.valid Data.rep := by
  intro G hG
  simp only [meanThreeGroups, List.mem_cons, List.not_mem_nil, or_false] at hG
  rcases hG with rfl | rfl | rfl | rfl | rfl
  · exact ⟨schemas_ok schema0 (by simp [schemas]), fun a ha => wit0 a ha, meanThree_ldl0⟩
  · exact ⟨schemas_ok schema1 (by simp [schemas]), fun a ha => wit1 a ha, meanThree_ldl1⟩
  · exact ⟨schemas_ok schema2 (by simp [schemas]), fun a ha => wit2 a ha, meanThree_ldl2⟩
  · exact ⟨schemas_ok schema3 (by simp [schemas]), fun a ha => wit3 a ha, meanThree_ldl3⟩
  · exact ⟨schemas_ok schema4 (by simp [schemas]), fun a ha => wit4 a ha, meanThree_ldl4⟩

theorem meanThree_totals : List.Forall₂ GroupCert.Totals meanThreeGroups meanThreeClaims :=
  .cons (GroupCert.totals_of_claim meanThree_acc0) <|
  .cons (GroupCert.totals_of_claim meanThree_acc1) <|
  .cons (GroupCert.totals_of_claim meanThree_acc2) <|
  .cons (GroupCert.totals_of_claim meanThree_acc3) <|
  .cons (GroupCert.totals_of_claims3 rfl meanThree_acc4_0 meanThree_acc4_5 meanThree_acc4_10) .nil

/-- **`thm:certificate-inequalities` for `P_mean,3`**: `eval_U(P_mean,3) ≥ 0` on every finite host. -/
theorem meanThree_nonneg {d : ℕ} (K : FiniteKernel d) : 0 ≤ evalPoly K targetMeanThree :=
  cert_sound_of_chunks (by decide) meanThree_valid (Ws := Data.MeanThree.WtChunks) (cs := Data.MeanThree.claimsT) rfl
    meanThree_chunks meanThree_end meanThree_totals meanThree_fin K

end EvenCycleApex.Checks
