import EvenCycleApex.Certificate.Checks.MeanThree

/-!
# Kernel check: the certificate of `P₋`

`prop:checked-data` for this target, evaluated by the kernel (`decide +kernel`): the 19
factorizations (`neg_ldl*`), identity (C) as accumulated totals (`neg_acc*` for the groups, in row
ranges for `r = 4`; `neg_t*` for the target in chunks of 1024 monomials, witnesses and totals
together), and the final comparison `neg_fin`.  Then `thm:certificate-inequalities` for this target:
`negMajority_nonneg`.

Generated by `tools/gen_cert_data.py checks`; do not edit.  The files `Checks/{MeanThree,Neg,Pos}`
import each other in a chain so that `lake build` evaluates them one at a time (kernel memory).
-/

set_option maxRecDepth 100000

namespace EvenCycleApex.Checks

open EvenCycleApex Certificate

theorem neg_ldl0 : ∀ j < schema0.types.length, negG0.ldlOK j = true := by
  decide +kernel

theorem neg_ldl1 : ∀ j < schema1.types.length, negG1.ldlOK j = true := by
  decide +kernel

theorem neg_ldl2 : ∀ j < schema2.types.length, negG2.ldlOK j = true := by
  decide +kernel

theorem neg_ldl3 : ∀ j < schema3.types.length, negG3.ldlOK j = true := by
  decide +kernel

theorem neg_ldl4 : ∀ j < schema4.types.length, negG4.ldlOK j = true := by
  decide +kernel

theorem neg_acc0 : negG0.accRows 0 negG0.S.feats.length 0 0 0
    (claimOK Data.Neg.claim0_0.1 Data.Neg.claim0_0.2.1 Data.Neg.claim0_0.2.2) = true := by
  decide +kernel

theorem neg_acc1 : negG1.accRows 0 negG1.S.feats.length 0 0 0
    (claimOK Data.Neg.claim1_0.1 Data.Neg.claim1_0.2.1 Data.Neg.claim1_0.2.2) = true := by
  decide +kernel

theorem neg_acc2 : negG2.accRows 0 negG2.S.feats.length 0 0 0
    (claimOK Data.Neg.claim2_0.1 Data.Neg.claim2_0.2.1 Data.Neg.claim2_0.2.2) = true := by
  decide +kernel

theorem neg_acc3 : negG3.accRows 0 negG3.S.feats.length 0 0 0
    (claimOK Data.Neg.claim3_0.1 Data.Neg.claim3_0.2.1 Data.Neg.claim3_0.2.2) = true := by
  decide +kernel

theorem neg_acc4_0 : negG4.accRows 0 5 0 0 0
    (claimOK Data.Neg.claim4_0.1 Data.Neg.claim4_0.2.1 Data.Neg.claim4_0.2.2) = true := by
  decide +kernel

theorem neg_acc4_5 : negG4.accRows 5 5 0 0 0
    (claimOK Data.Neg.claim4_5.1 Data.Neg.claim4_5.2.1 Data.Neg.claim4_5.2.2) = true := by
  decide +kernel

theorem neg_acc4_10 : negG4.accRows 10 5 0 0 0
    (claimOK Data.Neg.claim4_10.1 Data.Neg.claim4_10.2.1 Data.Neg.claim4_10.2.2) = true := by
  decide +kernel

theorem neg_t0 : tchunk Data.rep 1024 targetNeg 0 Data.Neg.Wt_0 Data.Neg.claimT_0 = true := by
  decide +kernel

theorem neg_t1 : tchunk Data.rep 1024 targetNeg 1 Data.Neg.Wt_1 Data.Neg.claimT_1 = true := by
  decide +kernel

theorem neg_t2 : tchunk Data.rep 1024 targetNeg 2 Data.Neg.Wt_2 Data.Neg.claimT_2 = true := by
  decide +kernel

theorem neg_t3 : tchunk Data.rep 1024 targetNeg 3 Data.Neg.Wt_3 Data.Neg.claimT_3 = true := by
  decide +kernel

theorem neg_t4 : tchunk Data.rep 1024 targetNeg 4 Data.Neg.Wt_4 Data.Neg.claimT_4 = true := by
  decide +kernel

theorem neg_t5 : tchunk Data.rep 1024 targetNeg 5 Data.Neg.Wt_5 Data.Neg.claimT_5 = true := by
  decide +kernel

theorem neg_t6 : tchunk Data.rep 1024 targetNeg 6 Data.Neg.Wt_6 Data.Neg.claimT_6 = true := by
  decide +kernel

theorem neg_chunks : ∀ k < Data.Neg.WtChunks.length,
    tchunk Data.rep 1024 targetNeg k (Data.Neg.WtChunks.getD k []) (Data.Neg.claimsT.getD k (0, 0, 0)) = true := by
  intro k hk
  change k < 7 at hk
  interval_cases k
  · exact neg_t0
  · exact neg_t1
  · exact neg_t2
  · exact neg_t3
  · exact neg_t4
  · exact neg_t5
  · exact neg_t6

theorem neg_end : targetNeg.drop (1024 * Data.Neg.WtChunks.length) = [] := by
  decide +kernel

/-- The claimed weighted totals of the five groups. -/
def negClaims : List (ℕ × (ℕ × ℕ × ℕ)) :=
  [(negG0.S.weight, Data.Neg.claim0_0), (negG1.S.weight, Data.Neg.claim1_0),
   (negG2.S.weight, Data.Neg.claim2_0), (negG3.S.weight, Data.Neg.claim3_0),
   (negG4.S.weight, add3 (add3 Data.Neg.claim4_0 Data.Neg.claim4_5) Data.Neg.claim4_10)]

theorem neg_fin : totalsOK certScale (sum3 Data.Neg.claimsT) negClaims = true := by
  decide +kernel

theorem neg_valid : ∀ G ∈ negGroups, G.valid Data.rep := by
  intro G hG
  simp only [negGroups, List.mem_cons, List.not_mem_nil, or_false] at hG
  rcases hG with rfl | rfl | rfl | rfl | rfl
  · exact ⟨schemas_ok schema0 (by simp [schemas]), fun a ha => wit0 a ha, neg_ldl0⟩
  · exact ⟨schemas_ok schema1 (by simp [schemas]), fun a ha => wit1 a ha, neg_ldl1⟩
  · exact ⟨schemas_ok schema2 (by simp [schemas]), fun a ha => wit2 a ha, neg_ldl2⟩
  · exact ⟨schemas_ok schema3 (by simp [schemas]), fun a ha => wit3 a ha, neg_ldl3⟩
  · exact ⟨schemas_ok schema4 (by simp [schemas]), fun a ha => wit4 a ha, neg_ldl4⟩

theorem neg_totals : List.Forall₂ GroupCert.Totals negGroups negClaims :=
  .cons (GroupCert.totals_of_claim neg_acc0) <|
  .cons (GroupCert.totals_of_claim neg_acc1) <|
  .cons (GroupCert.totals_of_claim neg_acc2) <|
  .cons (GroupCert.totals_of_claim neg_acc3) <|
  .cons (GroupCert.totals_of_claims3 rfl neg_acc4_0 neg_acc4_5 neg_acc4_10) .nil

/-- **`thm:certificate-inequalities` for `P₋`**: `eval_U(P₋) ≥ 0` on every finite host. -/
theorem negMajority_nonneg {d : ℕ} (K : FiniteKernel d) : 0 ≤ evalPoly K targetNeg :=
  cert_sound_of_chunks (by decide) neg_valid (Ws := Data.Neg.WtChunks) (cs := Data.Neg.claimsT) rfl
    neg_chunks neg_end neg_totals neg_fin K

end EvenCycleApex.Checks
