import EvenCycleApex.Certificate.Checks.Neg

/-!
# Kernel check: the certificate of `P₊`

`prop:checked-data` for this target, evaluated by the kernel (`decide +kernel`): the 19
factorizations (`pos_ldl*`), identity (C) as accumulated totals (`pos_acc*` for the groups, in row
ranges for `r = 4`; `pos_t*` for the target in chunks of 1024 monomials, witnesses and totals
together), and the final comparison `pos_fin`.  Then `thm:certificate-inequalities` for this target:
`posMajority_nonneg`.

Generated by `tools/gen_cert_data.py checks`; do not edit.  The files `Checks/{MeanThree,Neg,Pos}`
import each other in a chain so that `lake build` evaluates them one at a time (kernel memory).
-/

set_option maxRecDepth 100000

namespace EvenCycleApex.Checks

open EvenCycleApex Certificate

theorem pos_ldl0 : ∀ j < schema0.types.length, posG0.ldlOK j = true := by
  decide +kernel

theorem pos_ldl1 : ∀ j < schema1.types.length, posG1.ldlOK j = true := by
  decide +kernel

theorem pos_ldl2 : ∀ j < schema2.types.length, posG2.ldlOK j = true := by
  decide +kernel

theorem pos_ldl3 : ∀ j < schema3.types.length, posG3.ldlOK j = true := by
  decide +kernel

theorem pos_ldl4 : ∀ j < schema4.types.length, posG4.ldlOK j = true := by
  decide +kernel

theorem pos_acc0 : posG0.accRows 0 posG0.S.feats.length 0 0 0
    (claimOK Data.Pos.claim0_0.1 Data.Pos.claim0_0.2.1 Data.Pos.claim0_0.2.2) = true := by
  decide +kernel

theorem pos_acc1 : posG1.accRows 0 posG1.S.feats.length 0 0 0
    (claimOK Data.Pos.claim1_0.1 Data.Pos.claim1_0.2.1 Data.Pos.claim1_0.2.2) = true := by
  decide +kernel

theorem pos_acc2 : posG2.accRows 0 posG2.S.feats.length 0 0 0
    (claimOK Data.Pos.claim2_0.1 Data.Pos.claim2_0.2.1 Data.Pos.claim2_0.2.2) = true := by
  decide +kernel

theorem pos_acc3 : posG3.accRows 0 posG3.S.feats.length 0 0 0
    (claimOK Data.Pos.claim3_0.1 Data.Pos.claim3_0.2.1 Data.Pos.claim3_0.2.2) = true := by
  decide +kernel

theorem pos_acc4_0 : posG4.accRows 0 5 0 0 0
    (claimOK Data.Pos.claim4_0.1 Data.Pos.claim4_0.2.1 Data.Pos.claim4_0.2.2) = true := by
  decide +kernel

theorem pos_acc4_5 : posG4.accRows 5 5 0 0 0
    (claimOK Data.Pos.claim4_5.1 Data.Pos.claim4_5.2.1 Data.Pos.claim4_5.2.2) = true := by
  decide +kernel

theorem pos_acc4_10 : posG4.accRows 10 5 0 0 0
    (claimOK Data.Pos.claim4_10.1 Data.Pos.claim4_10.2.1 Data.Pos.claim4_10.2.2) = true := by
  decide +kernel

theorem pos_t0 : tchunk Data.rep 1024 targetPos 0 Data.Pos.Wt_0 Data.Pos.claimT_0 = true := by
  decide +kernel

theorem pos_t1 : tchunk Data.rep 1024 targetPos 1 Data.Pos.Wt_1 Data.Pos.claimT_1 = true := by
  decide +kernel

theorem pos_t2 : tchunk Data.rep 1024 targetPos 2 Data.Pos.Wt_2 Data.Pos.claimT_2 = true := by
  decide +kernel

theorem pos_t3 : tchunk Data.rep 1024 targetPos 3 Data.Pos.Wt_3 Data.Pos.claimT_3 = true := by
  decide +kernel

theorem pos_t4 : tchunk Data.rep 1024 targetPos 4 Data.Pos.Wt_4 Data.Pos.claimT_4 = true := by
  decide +kernel

theorem pos_t5 : tchunk Data.rep 1024 targetPos 5 Data.Pos.Wt_5 Data.Pos.claimT_5 = true := by
  decide +kernel

theorem pos_t6 : tchunk Data.rep 1024 targetPos 6 Data.Pos.Wt_6 Data.Pos.claimT_6 = true := by
  decide +kernel

theorem pos_chunks : ∀ k < Data.Pos.WtChunks.length,
    tchunk Data.rep 1024 targetPos k (Data.Pos.WtChunks.getD k []) (Data.Pos.claimsT.getD k (0, 0, 0)) = true := by
  intro k hk
  change k < 7 at hk
  interval_cases k
  · exact pos_t0
  · exact pos_t1
  · exact pos_t2
  · exact pos_t3
  · exact pos_t4
  · exact pos_t5
  · exact pos_t6

theorem pos_end : targetPos.drop (1024 * Data.Pos.WtChunks.length) = [] := by
  decide +kernel

/-- The claimed weighted totals of the five groups. -/
def posClaims : List (ℕ × (ℕ × ℕ × ℕ)) :=
  [(posG0.S.weight, Data.Pos.claim0_0), (posG1.S.weight, Data.Pos.claim1_0),
   (posG2.S.weight, Data.Pos.claim2_0), (posG3.S.weight, Data.Pos.claim3_0),
   (posG4.S.weight, add3 (add3 Data.Pos.claim4_0 Data.Pos.claim4_5) Data.Pos.claim4_10)]

theorem pos_fin : totalsOK certScale (sum3 Data.Pos.claimsT) posClaims = true := by
  decide +kernel

theorem pos_valid : ∀ G ∈ posGroups, G.valid Data.rep := by
  intro G hG
  simp only [posGroups, List.mem_cons, List.not_mem_nil, or_false] at hG
  rcases hG with rfl | rfl | rfl | rfl | rfl
  · exact ⟨schemas_ok schema0 (by simp [schemas]), fun a ha => wit0 a ha, pos_ldl0⟩
  · exact ⟨schemas_ok schema1 (by simp [schemas]), fun a ha => wit1 a ha, pos_ldl1⟩
  · exact ⟨schemas_ok schema2 (by simp [schemas]), fun a ha => wit2 a ha, pos_ldl2⟩
  · exact ⟨schemas_ok schema3 (by simp [schemas]), fun a ha => wit3 a ha, pos_ldl3⟩
  · exact ⟨schemas_ok schema4 (by simp [schemas]), fun a ha => wit4 a ha, pos_ldl4⟩

theorem pos_totals : List.Forall₂ GroupCert.Totals posGroups posClaims :=
  .cons (GroupCert.totals_of_claim pos_acc0) <|
  .cons (GroupCert.totals_of_claim pos_acc1) <|
  .cons (GroupCert.totals_of_claim pos_acc2) <|
  .cons (GroupCert.totals_of_claim pos_acc3) <|
  .cons (GroupCert.totals_of_claims3 rfl pos_acc4_0 pos_acc4_5 pos_acc4_10) .nil

/-- **`thm:certificate-inequalities` for `P₊`**: `eval_U(P₊) ≥ 0` on every finite host. -/
theorem posMajority_nonneg {d : ℕ} (K : FiniteKernel d) : 0 ≤ evalPoly K targetPos :=
  cert_sound_of_chunks (by decide) pos_valid (Ws := Data.Pos.WtChunks) (cs := Data.Pos.claimsT) rfl
    pos_chunks pos_end pos_totals pos_fin K

end EvenCycleApex.Checks
