import ApicesCommonness.Cycles.Certificate.Checker

/-!
# The certificate feature schema

Blueprint `def:feature-schema`: the nineteen blocks, grouped by their number of roots `r`
(`schema0`, …, `schema4`; the blocks of a group share their features and differ in the root type).
Every feature is a six-vertex mask on the roots `0, …, r − 1` and the first copy
`r, …, r + k − 1`; root types are six-vertex masks of root pairs (the blueprint's type `t` has bit `e`
for the `e`-th root pair in lexicographic order).  `sigma` is the block swap (roots fixed, first and
second copy exchanged), `weight = 2^{6 − C(r,2)}`.

Generated by `tools/gen_cert_data.py schema` from `certificates/lean-data/feature_schema.json`;
do not edit.  The checks `Schema.ok` and the block dimensions are proved below by `decide`.
-/

namespace ApicesCommonness

/-- Blocks 0–0 (`r = 0`, `k = 3`); root types [0]. -/
def schema0 : Schema where
  r := 0
  k := 3
  p := 0
  sigma := 69987
  rootMask := 0
  feats := [1, 3, 35]
  types := [0]
  weight := 64

/-- Blocks 1–1 (`r = 1`, `k = 2`); root types [0]. -/
def schema1 : Schema where
  r := 1
  k := 2
  p := 1
  sigma := 172824
  rootMask := 0
  feats := [1, 3, 32, 33, 35]
  types := [0]
  weight := 64

/-- Blocks 2–3 (`r = 2`, `k = 2`); root types [0, 1]. -/
def schema2 : Schema where
  r := 2
  k := 2
  p := 0
  sigma := 109320
  rootMask := 1
  feats := [2, 6, 32, 34, 36, 38, 96, 98, 102, 512, 514, 518, 544, 546, 548, 550, 608, 610, 614]
  types := [0, 1]
  weight := 32

/-- Blocks 4–7 (`r = 3`, `k = 1`); root types [0, 1, 3, 7]. -/
def schema3 : Schema where
  r := 3
  k := 1
  p := 1
  sigma := 178312
  rootMask := 35
  feats := [4, 64, 68, 512, 516, 576, 580]
  types := [0, 1, 3, 35]
  weight := 8

/-- Blocks 8–18 (`r = 4`, `k = 1`); root types [0, 1, 3, 7, 11, 12, 13, 15, 30, 31, 63]. -/
def schema4 : Schema where
  r := 4
  k := 1
  p := 0
  sigma := 153224
  rootMask := 615
  feats := [8, 128, 136, 1024, 1032, 1152, 1160, 4096, 4104, 4224, 4232, 5120, 5128, 5248, 5256]
  types := [0, 1, 3, 7, 35, 36, 37, 39, 102, 103, 615]
  weight := 1

/-- The five groups, in block order. -/
def schemas : List Schema := [schema0, schema1, schema2, schema3, schema4]

theorem schemas_ok : ∀ S ∈ schemas, S.ok = true := by decide

/-- The block dimensions `3, 5, 19, 19, 7 × 4, 15 × 11` (`def:feature-schema`). -/
theorem schema_dims :
    (schemas.flatMap fun S => S.types.map fun _ => S.feats.length)
      = [3, 5, 19, 19, 7, 7, 7, 7, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15] := by decide

end ApicesCommonness
