/-
Hfin dispatcher for m = 13 (GENERATED by hfin_certs.py --gen; do not edit).
-/
import OddCycleBound.HighDensity.Hfin.P013R02
import OddCycleBound.HighDensity.Hfin.P013R03

namespace OddCycleBound.HighDensity

/-- Dispatcher for `m = 13`: all residual-strip pairs `(m,r)`. -/
theorem finKernel_M13 {q l : ℝ} (r : ℕ) (hr2 : 2 ≤ r) (hres : 2*r < 13 - 2*r)
    (hq0 : 0 ≤ q) (hq : q ≤ 1/3) (hl0 : 0 < l) (hlr : l < q + (r : ℝ)/13) :
    0 ≤ diagKernel 13 r q l := by
  have hub : r ≤ 3 := by omega
  interval_cases r
  · exact finKernel_13_2 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_13_3 hq0 hq hl0 (by push_cast at hlr; exact hlr)

end OddCycleBound.HighDensity
