/-
Hfin dispatcher for m = 17 (GENERATED by hfin_certs.py --gen; do not edit).
-/
import OddCycleBound.HighDensity.Hfin.P017R02
import OddCycleBound.HighDensity.Hfin.P017R03
import OddCycleBound.HighDensity.Hfin.P017R04

namespace OddCycleBound.HighDensity

/-- Dispatcher for `m = 17`: all residual-strip pairs `(m,r)`. -/
theorem finKernel_M17 {q l : ℝ} (r : ℕ) (hr2 : 2 ≤ r) (hres : 2*r < 17 - 2*r)
    (hq0 : 0 ≤ q) (hq : q ≤ 1/3) (hl0 : 0 < l) (hlr : l < q + (r : ℝ)/17) :
    0 ≤ diagKernel 17 r q l := by
  have hub : r ≤ 4 := by omega
  interval_cases r
  · exact finKernel_17_2 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_17_3 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_17_4 hq0 hq hl0 (by push_cast at hlr; exact hlr)

end OddCycleBound.HighDensity
