/-
Hfin dispatcher for m = 19 (GENERATED by hfin_certs.py --gen; do not edit).
-/
import OddCycleBound.HighDensity.Hfin.P019R02
import OddCycleBound.HighDensity.Hfin.P019R03
import OddCycleBound.HighDensity.Hfin.P019R04

namespace OddCycleBound.HighDensity

/-- Dispatcher for `m = 19`: all residual-strip pairs `(m,r)`. -/
theorem finKernel_M19 {q l : ℝ} (r : ℕ) (hr2 : 2 ≤ r) (hres : 2*r < 19 - 2*r)
    (hq0 : 0 ≤ q) (hq : q ≤ 1/3) (hl0 : 0 < l) (hlr : l < q + (r : ℝ)/19) :
    0 ≤ diagKernel 19 r q l := by
  have hub : r ≤ 4 := by omega
  interval_cases r
  · exact finKernel_19_2 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_19_3 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_19_4 hq0 hq hl0 (by push_cast at hlr; exact hlr)

end OddCycleBound.HighDensity
