/-
Hfin dispatcher for m = 23 (GENERATED by hfin_certs.py --gen; do not edit).
-/
import OddCycleBound.HighDensity.Hfin.P023R02
import OddCycleBound.HighDensity.Hfin.P023R03
import OddCycleBound.HighDensity.Hfin.P023R04
import OddCycleBound.HighDensity.Hfin.P023R05

namespace OddCycleBound.HighDensity

/-- Dispatcher for `m = 23`: all residual-strip pairs `(m,r)`. -/
theorem finKernel_M23 {q l : ℝ} (r : ℕ) (hr2 : 2 ≤ r) (hres : 2*r < 23 - 2*r)
    (hq0 : 0 ≤ q) (hq : q ≤ 1/3) (hl0 : 0 < l) (hlr : l < q + (r : ℝ)/23) :
    0 ≤ diagKernel 23 r q l := by
  have hub : r ≤ 5 := by omega
  interval_cases r
  · exact finKernel_23_2 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_23_3 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_23_4 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_23_5 hq0 hq hl0 (by push_cast at hlr; exact hlr)

end OddCycleBound.HighDensity
