/-
Hfin dispatcher for m = 27 (GENERATED by hfin_certs.py --gen; do not edit).
-/
import OddCycleBound.HighDensity.Hfin.P027R02
import OddCycleBound.HighDensity.Hfin.P027R03
import OddCycleBound.HighDensity.Hfin.P027R04
import OddCycleBound.HighDensity.Hfin.P027R05
import OddCycleBound.HighDensity.Hfin.P027R06

namespace OddCycleBound.HighDensity

/-- Dispatcher for `m = 27`: all residual-strip pairs `(m,r)`. -/
theorem finKernel_M27 {q l : ℝ} (r : ℕ) (hr2 : 2 ≤ r) (hres : 2*r < 27 - 2*r)
    (hq0 : 0 ≤ q) (hq : q ≤ 1/3) (hl0 : 0 < l) (hlr : l < q + (r : ℝ)/27) :
    0 ≤ diagKernel 27 r q l := by
  have hub : r ≤ 6 := by omega
  interval_cases r
  · exact finKernel_27_2 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_27_3 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_27_4 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_27_5 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_27_6 hq0 hq hl0 (by push_cast at hlr; exact hlr)

end OddCycleBound.HighDensity
