/-
Hfin dispatcher for m = 29 (GENERATED by hfin_certs.py --gen; do not edit).
-/
import OddCycleBound.HighDensity.Hfin.P029R02
import OddCycleBound.HighDensity.Hfin.P029R03
import OddCycleBound.HighDensity.Hfin.P029R04
import OddCycleBound.HighDensity.Hfin.P029R05
import OddCycleBound.HighDensity.Hfin.P029R06
import OddCycleBound.HighDensity.Hfin.P029R07

namespace OddCycleBound.HighDensity

/-- Dispatcher for `m = 29`: all residual-strip pairs `(m,r)`. -/
theorem finKernel_M29 {q l : ℝ} (r : ℕ) (hr2 : 2 ≤ r) (hres : 2*r < 29 - 2*r)
    (hq0 : 0 ≤ q) (hq : q ≤ 1/3) (hl0 : 0 < l) (hlr : l < q + (r : ℝ)/29) :
    0 ≤ diagKernel 29 r q l := by
  have hub : r ≤ 7 := by omega
  interval_cases r
  · exact finKernel_29_2 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_29_3 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_29_4 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_29_5 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_29_6 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_29_7 hq0 hq hl0 (by push_cast at hlr; exact hlr)

end OddCycleBound.HighDensity
