/-
Hfin dispatcher for m = 31 (GENERATED by hfin_certs.py --gen; do not edit).
-/
import OddCycleBound.HighDensity.Hfin.P031R02
import OddCycleBound.HighDensity.Hfin.P031R03
import OddCycleBound.HighDensity.Hfin.P031R04
import OddCycleBound.HighDensity.Hfin.P031R05
import OddCycleBound.HighDensity.Hfin.P031R06
import OddCycleBound.HighDensity.Hfin.P031R07

namespace OddCycleBound.HighDensity

/-- Dispatcher for `m = 31`: all residual-strip pairs `(m,r)`. -/
theorem finKernel_M31 {q l : ℝ} (r : ℕ) (hr2 : 2 ≤ r) (hres : 2*r < 31 - 2*r)
    (hq0 : 0 ≤ q) (hq : q ≤ 1/3) (hl0 : 0 < l) (hlr : l < q + (r : ℝ)/31) :
    0 ≤ diagKernel 31 r q l := by
  have hub : r ≤ 7 := by omega
  interval_cases r
  · exact finKernel_31_2 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_31_3 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_31_4 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_31_5 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_31_6 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_31_7 hq0 hq hl0 (by push_cast at hlr; exact hlr)

end OddCycleBound.HighDensity
