/-
Hfin dispatcher for m = 33 (GENERATED by hfin_certs.py --gen; do not edit).
-/
import OddCycleBound.HighDensity.Hfin.P033R02
import OddCycleBound.HighDensity.Hfin.P033R03
import OddCycleBound.HighDensity.Hfin.P033R04
import OddCycleBound.HighDensity.Hfin.P033R05
import OddCycleBound.HighDensity.Hfin.P033R06
import OddCycleBound.HighDensity.Hfin.P033R07
import OddCycleBound.HighDensity.Hfin.P033R08

namespace OddCycleBound.HighDensity

/-- Dispatcher for `m = 33`: all residual-strip pairs `(m,r)`. -/
theorem finKernel_M33 {q l : ℝ} (r : ℕ) (hr2 : 2 ≤ r) (hres : 2*r < 33 - 2*r)
    (hq0 : 0 ≤ q) (hq : q ≤ 1/3) (hl0 : 0 < l) (hlr : l < q + (r : ℝ)/33) :
    0 ≤ diagKernel 33 r q l := by
  have hub : r ≤ 8 := by omega
  interval_cases r
  · exact finKernel_33_2 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_33_3 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_33_4 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_33_5 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_33_6 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_33_7 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_33_8 hq0 hq hl0 (by push_cast at hlr; exact hlr)

end OddCycleBound.HighDensity
