/-
Hfin dispatcher for m = 37 (GENERATED by hfin_certs.py --gen; do not edit).
-/
import OddCycleBound.HighDensity.Hfin.P037R02
import OddCycleBound.HighDensity.Hfin.P037R03
import OddCycleBound.HighDensity.Hfin.P037R04
import OddCycleBound.HighDensity.Hfin.P037R05
import OddCycleBound.HighDensity.Hfin.P037R06
import OddCycleBound.HighDensity.Hfin.P037R07
import OddCycleBound.HighDensity.Hfin.P037R08
import OddCycleBound.HighDensity.Hfin.P037R09

namespace OddCycleBound.HighDensity

/-- Dispatcher for `m = 37`: all residual-strip pairs `(m,r)`. -/
theorem finKernel_M37 {q l : ℝ} (r : ℕ) (hr2 : 2 ≤ r) (hres : 2*r < 37 - 2*r)
    (hq0 : 0 ≤ q) (hq : q ≤ 1/3) (hl0 : 0 < l) (hlr : l < q + (r : ℝ)/37) :
    0 ≤ diagKernel 37 r q l := by
  have hub : r ≤ 9 := by omega
  interval_cases r
  · exact finKernel_37_2 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_37_3 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_37_4 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_37_5 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_37_6 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_37_7 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_37_8 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_37_9 hq0 hq hl0 (by push_cast at hlr; exact hlr)

end OddCycleBound.HighDensity
