/-
Hfin dispatcher for m = 39 (GENERATED by hfin_certs.py --gen; do not edit).
-/
import OddCycleBound.HighDensity.Hfin.P039R02
import OddCycleBound.HighDensity.Hfin.P039R03
import OddCycleBound.HighDensity.Hfin.P039R04
import OddCycleBound.HighDensity.Hfin.P039R05
import OddCycleBound.HighDensity.Hfin.P039R06
import OddCycleBound.HighDensity.Hfin.P039R07
import OddCycleBound.HighDensity.Hfin.P039R08
import OddCycleBound.HighDensity.Hfin.P039R09

namespace OddCycleBound.HighDensity

/-- Dispatcher for `m = 39`: all residual-strip pairs `(m,r)`. -/
theorem finKernel_M39 {q l : ℝ} (r : ℕ) (hr2 : 2 ≤ r) (hres : 2*r < 39 - 2*r)
    (hq0 : 0 ≤ q) (hq : q ≤ 1/3) (hl0 : 0 < l) (hlr : l < q + (r : ℝ)/39) :
    0 ≤ diagKernel 39 r q l := by
  have hub : r ≤ 9 := by omega
  interval_cases r
  · exact finKernel_39_2 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_39_3 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_39_4 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_39_5 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_39_6 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_39_7 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_39_8 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_39_9 hq0 hq hl0 (by push_cast at hlr; exact hlr)

end OddCycleBound.HighDensity
