/-
Hfin dispatcher for m = 41 (GENERATED by hfin_certs.py --gen; do not edit).
-/
import OddCycleBound.HighDensity.Hfin.P041R02
import OddCycleBound.HighDensity.Hfin.P041R03
import OddCycleBound.HighDensity.Hfin.P041R04
import OddCycleBound.HighDensity.Hfin.P041R05
import OddCycleBound.HighDensity.Hfin.P041R06
import OddCycleBound.HighDensity.Hfin.P041R07
import OddCycleBound.HighDensity.Hfin.P041R08
import OddCycleBound.HighDensity.Hfin.P041R09
import OddCycleBound.HighDensity.Hfin.P041R10

namespace OddCycleBound.HighDensity

/-- Dispatcher for `m = 41`: all residual-strip pairs `(m,r)`. -/
theorem finKernel_M41 {q l : ℝ} (r : ℕ) (hr2 : 2 ≤ r) (hres : 2*r < 41 - 2*r)
    (hq0 : 0 ≤ q) (hq : q ≤ 1/3) (hl0 : 0 < l) (hlr : l < q + (r : ℝ)/41) :
    0 ≤ diagKernel 41 r q l := by
  have hub : r ≤ 10 := by omega
  interval_cases r
  · exact finKernel_41_2 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_41_3 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_41_4 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_41_5 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_41_6 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_41_7 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_41_8 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_41_9 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_41_10 hq0 hq hl0 (by push_cast at hlr; exact hlr)

end OddCycleBound.HighDensity
