/-
Hfin dispatcher for m = 43 (GENERATED by hfin_certs.py --gen; do not edit).
-/
import OddCycleBound.HighDensity.Hfin.P043R02
import OddCycleBound.HighDensity.Hfin.P043R03
import OddCycleBound.HighDensity.Hfin.P043R04
import OddCycleBound.HighDensity.Hfin.P043R05
import OddCycleBound.HighDensity.Hfin.P043R06
import OddCycleBound.HighDensity.Hfin.P043R07
import OddCycleBound.HighDensity.Hfin.P043R08
import OddCycleBound.HighDensity.Hfin.P043R09
import OddCycleBound.HighDensity.Hfin.P043R10

namespace OddCycleBound.HighDensity

/-- Dispatcher for `m = 43`: all residual-strip pairs `(m,r)`. -/
theorem finKernel_M43 {q l : ℝ} (r : ℕ) (hr2 : 2 ≤ r) (hres : 2*r < 43 - 2*r)
    (hq0 : 0 ≤ q) (hq : q ≤ 1/3) (hl0 : 0 < l) (hlr : l < q + (r : ℝ)/43) :
    0 ≤ diagKernel 43 r q l := by
  have hub : r ≤ 10 := by omega
  interval_cases r
  · exact finKernel_43_2 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_43_3 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_43_4 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_43_5 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_43_6 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_43_7 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_43_8 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_43_9 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_43_10 hq0 hq hl0 (by push_cast at hlr; exact hlr)

end OddCycleBound.HighDensity
