/-
Hfin dispatcher for m = 45 (GENERATED by hfin_certs.py --gen; do not edit).
-/
import OddCycleBound.HighDensity.Hfin.P045R02
import OddCycleBound.HighDensity.Hfin.P045R03
import OddCycleBound.HighDensity.Hfin.P045R04
import OddCycleBound.HighDensity.Hfin.P045R05
import OddCycleBound.HighDensity.Hfin.P045R06
import OddCycleBound.HighDensity.Hfin.P045R07
import OddCycleBound.HighDensity.Hfin.P045R08
import OddCycleBound.HighDensity.Hfin.P045R09
import OddCycleBound.HighDensity.Hfin.P045R10
import OddCycleBound.HighDensity.Hfin.P045R11

namespace OddCycleBound.HighDensity

/-- Dispatcher for `m = 45`: all residual-strip pairs `(m,r)`. -/
theorem finKernel_M45 {q l : ℝ} (r : ℕ) (hr2 : 2 ≤ r) (hres : 2*r < 45 - 2*r)
    (hq0 : 0 ≤ q) (hq : q ≤ 1/3) (hl0 : 0 < l) (hlr : l < q + (r : ℝ)/45) :
    0 ≤ diagKernel 45 r q l := by
  have hub : r ≤ 11 := by omega
  interval_cases r
  · exact finKernel_45_2 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_45_3 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_45_4 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_45_5 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_45_6 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_45_7 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_45_8 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_45_9 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_45_10 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_45_11 hq0 hq hl0 (by push_cast at hlr; exact hlr)

end OddCycleBound.HighDensity
