/-
Hfin dispatcher for m = 47 (GENERATED by hfin_certs.py --gen; do not edit).
-/
import OddCycleBound.HighDensity.Hfin.P047R02
import OddCycleBound.HighDensity.Hfin.P047R03
import OddCycleBound.HighDensity.Hfin.P047R04
import OddCycleBound.HighDensity.Hfin.P047R05
import OddCycleBound.HighDensity.Hfin.P047R06
import OddCycleBound.HighDensity.Hfin.P047R07
import OddCycleBound.HighDensity.Hfin.P047R08
import OddCycleBound.HighDensity.Hfin.P047R09
import OddCycleBound.HighDensity.Hfin.P047R10
import OddCycleBound.HighDensity.Hfin.P047R11

namespace OddCycleBound.HighDensity

/-- Dispatcher for `m = 47`: all residual-strip pairs `(m,r)`. -/
theorem finKernel_M47 {q l : ℝ} (r : ℕ) (hr2 : 2 ≤ r) (hres : 2*r < 47 - 2*r)
    (hq0 : 0 ≤ q) (hq : q ≤ 1/3) (hl0 : 0 < l) (hlr : l < q + (r : ℝ)/47) :
    0 ≤ diagKernel 47 r q l := by
  have hub : r ≤ 11 := by omega
  interval_cases r
  · exact finKernel_47_2 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_47_3 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_47_4 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_47_5 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_47_6 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_47_7 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_47_8 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_47_9 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_47_10 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_47_11 hq0 hq hl0 (by push_cast at hlr; exact hlr)

end OddCycleBound.HighDensity
