/-
Hfin dispatcher for m = 49 (GENERATED by hfin_certs.py --gen; do not edit).
-/
import OddCycleBound.HighDensity.Hfin.P049R02
import OddCycleBound.HighDensity.Hfin.P049R03
import OddCycleBound.HighDensity.Hfin.P049R04
import OddCycleBound.HighDensity.Hfin.P049R05
import OddCycleBound.HighDensity.Hfin.P049R06
import OddCycleBound.HighDensity.Hfin.P049R07
import OddCycleBound.HighDensity.Hfin.P049R08
import OddCycleBound.HighDensity.Hfin.P049R09
import OddCycleBound.HighDensity.Hfin.P049R10
import OddCycleBound.HighDensity.Hfin.P049R11
import OddCycleBound.HighDensity.Hfin.P049R12

namespace OddCycleBound.HighDensity

/-- Dispatcher for `m = 49`: all residual-strip pairs `(m,r)`. -/
theorem finKernel_M49 {q l : ℝ} (r : ℕ) (hr2 : 2 ≤ r) (hres : 2*r < 49 - 2*r)
    (hq0 : 0 ≤ q) (hq : q ≤ 1/3) (hl0 : 0 < l) (hlr : l < q + (r : ℝ)/49) :
    0 ≤ diagKernel 49 r q l := by
  have hub : r ≤ 12 := by omega
  interval_cases r
  · exact finKernel_49_2 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_49_3 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_49_4 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_49_5 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_49_6 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_49_7 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_49_8 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_49_9 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_49_10 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_49_11 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_49_12 hq0 hq hl0 (by push_cast at hlr; exact hlr)

end OddCycleBound.HighDensity
