/-
Hfin dispatcher for m = 51 (GENERATED by hfin_certs.py --gen; do not edit).
-/
import OddCycleBound.HighDensity.Hfin.P051R02
import OddCycleBound.HighDensity.Hfin.P051R03
import OddCycleBound.HighDensity.Hfin.P051R04
import OddCycleBound.HighDensity.Hfin.P051R05
import OddCycleBound.HighDensity.Hfin.P051R06
import OddCycleBound.HighDensity.Hfin.P051R07
import OddCycleBound.HighDensity.Hfin.P051R08
import OddCycleBound.HighDensity.Hfin.P051R09
import OddCycleBound.HighDensity.Hfin.P051R10
import OddCycleBound.HighDensity.Hfin.P051R11
import OddCycleBound.HighDensity.Hfin.P051R12

namespace OddCycleBound.HighDensity

/-- Dispatcher for `m = 51`: all residual-strip pairs `(m,r)`. -/
theorem finKernel_M51 {q l : ℝ} (r : ℕ) (hr2 : 2 ≤ r) (hres : 2*r < 51 - 2*r)
    (hq0 : 0 ≤ q) (hq : q ≤ 1/3) (hl0 : 0 < l) (hlr : l < q + (r : ℝ)/51) :
    0 ≤ diagKernel 51 r q l := by
  have hub : r ≤ 12 := by omega
  interval_cases r
  · exact finKernel_51_2 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_51_3 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_51_4 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_51_5 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_51_6 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_51_7 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_51_8 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_51_9 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_51_10 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_51_11 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_51_12 hq0 hq hl0 (by push_cast at hlr; exact hlr)

end OddCycleBound.HighDensity
