/-
Hfin dispatcher for m = 53 (GENERATED by hfin_certs.py --gen; do not edit).
-/
import OddCycleBound.HighDensity.Hfin.P053R02
import OddCycleBound.HighDensity.Hfin.P053R03
import OddCycleBound.HighDensity.Hfin.P053R04
import OddCycleBound.HighDensity.Hfin.P053R05
import OddCycleBound.HighDensity.Hfin.P053R06
import OddCycleBound.HighDensity.Hfin.P053R07
import OddCycleBound.HighDensity.Hfin.P053R08
import OddCycleBound.HighDensity.Hfin.P053R09
import OddCycleBound.HighDensity.Hfin.P053R10
import OddCycleBound.HighDensity.Hfin.P053R11
import OddCycleBound.HighDensity.Hfin.P053R12
import OddCycleBound.HighDensity.Hfin.P053R13

namespace OddCycleBound.HighDensity

/-- Dispatcher for `m = 53`: all residual-strip pairs `(m,r)`. -/
theorem finKernel_M53 {q l : ℝ} (r : ℕ) (hr2 : 2 ≤ r) (hres : 2*r < 53 - 2*r)
    (hq0 : 0 ≤ q) (hq : q ≤ 1/3) (hl0 : 0 < l) (hlr : l < q + (r : ℝ)/53) :
    0 ≤ diagKernel 53 r q l := by
  have hub : r ≤ 13 := by omega
  interval_cases r
  · exact finKernel_53_2 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_53_3 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_53_4 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_53_5 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_53_6 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_53_7 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_53_8 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_53_9 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_53_10 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_53_11 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_53_12 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_53_13 hq0 hq hl0 (by push_cast at hlr; exact hlr)

end OddCycleBound.HighDensity
