/-
Hfin dispatcher for m = 55 (GENERATED by hfin_certs.py --gen; do not edit).
-/
import OddCycleBound.HighDensity.Hfin.P055R02
import OddCycleBound.HighDensity.Hfin.P055R03
import OddCycleBound.HighDensity.Hfin.P055R04
import OddCycleBound.HighDensity.Hfin.P055R05
import OddCycleBound.HighDensity.Hfin.P055R06
import OddCycleBound.HighDensity.Hfin.P055R07
import OddCycleBound.HighDensity.Hfin.P055R08
import OddCycleBound.HighDensity.Hfin.P055R09
import OddCycleBound.HighDensity.Hfin.P055R10
import OddCycleBound.HighDensity.Hfin.P055R11
import OddCycleBound.HighDensity.Hfin.P055R12
import OddCycleBound.HighDensity.Hfin.P055R13

namespace OddCycleBound.HighDensity

/-- Dispatcher for `m = 55`: all residual-strip pairs `(m,r)`. -/
theorem finKernel_M55 {q l : ℝ} (r : ℕ) (hr2 : 2 ≤ r) (hres : 2*r < 55 - 2*r)
    (hq0 : 0 ≤ q) (hq : q ≤ 1/3) (hl0 : 0 < l) (hlr : l < q + (r : ℝ)/55) :
    0 ≤ diagKernel 55 r q l := by
  have hub : r ≤ 13 := by omega
  interval_cases r
  · exact finKernel_55_2 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_55_3 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_55_4 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_55_5 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_55_6 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_55_7 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_55_8 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_55_9 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_55_10 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_55_11 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_55_12 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_55_13 hq0 hq hl0 (by push_cast at hlr; exact hlr)

end OddCycleBound.HighDensity
