/-
Hfin dispatcher for m = 57 (GENERATED by hfin_certs.py --gen; do not edit).
-/
import OddCycleBound.HighDensity.Hfin.P057R02
import OddCycleBound.HighDensity.Hfin.P057R03
import OddCycleBound.HighDensity.Hfin.P057R04
import OddCycleBound.HighDensity.Hfin.P057R05
import OddCycleBound.HighDensity.Hfin.P057R06
import OddCycleBound.HighDensity.Hfin.P057R07
import OddCycleBound.HighDensity.Hfin.P057R08
import OddCycleBound.HighDensity.Hfin.P057R09
import OddCycleBound.HighDensity.Hfin.P057R10
import OddCycleBound.HighDensity.Hfin.P057R11
import OddCycleBound.HighDensity.Hfin.P057R12
import OddCycleBound.HighDensity.Hfin.P057R13
import OddCycleBound.HighDensity.Hfin.P057R14

namespace OddCycleBound.HighDensity

/-- Dispatcher for `m = 57`: all residual-strip pairs `(m,r)`. -/
theorem finKernel_M57 {q l : ℝ} (r : ℕ) (hr2 : 2 ≤ r) (hres : 2*r < 57 - 2*r)
    (hq0 : 0 ≤ q) (hq : q ≤ 1/3) (hl0 : 0 < l) (hlr : l < q + (r : ℝ)/57) :
    0 ≤ diagKernel 57 r q l := by
  have hub : r ≤ 14 := by omega
  interval_cases r
  · exact finKernel_57_2 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_57_3 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_57_4 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_57_5 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_57_6 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_57_7 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_57_8 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_57_9 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_57_10 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_57_11 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_57_12 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_57_13 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_57_14 hq0 hq hl0 (by push_cast at hlr; exact hlr)

end OddCycleBound.HighDensity
