/-
Hfin dispatcher for m = 59 (GENERATED by hfin_certs.py --gen; do not edit).
-/
import OddCycleBound.HighDensity.Hfin.P059R02
import OddCycleBound.HighDensity.Hfin.P059R03
import OddCycleBound.HighDensity.Hfin.P059R04
import OddCycleBound.HighDensity.Hfin.P059R05
import OddCycleBound.HighDensity.Hfin.P059R06
import OddCycleBound.HighDensity.Hfin.P059R07
import OddCycleBound.HighDensity.Hfin.P059R08
import OddCycleBound.HighDensity.Hfin.P059R09
import OddCycleBound.HighDensity.Hfin.P059R10
import OddCycleBound.HighDensity.Hfin.P059R11
import OddCycleBound.HighDensity.Hfin.P059R12
import OddCycleBound.HighDensity.Hfin.P059R13
import OddCycleBound.HighDensity.Hfin.P059R14

namespace OddCycleBound.HighDensity

/-- Dispatcher for `m = 59`: all residual-strip pairs `(m,r)`. -/
theorem finKernel_M59 {q l : ℝ} (r : ℕ) (hr2 : 2 ≤ r) (hres : 2*r < 59 - 2*r)
    (hq0 : 0 ≤ q) (hq : q ≤ 1/3) (hl0 : 0 < l) (hlr : l < q + (r : ℝ)/59) :
    0 ≤ diagKernel 59 r q l := by
  have hub : r ≤ 14 := by omega
  interval_cases r
  · exact finKernel_59_2 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_59_3 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_59_4 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_59_5 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_59_6 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_59_7 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_59_8 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_59_9 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_59_10 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_59_11 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_59_12 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_59_13 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_59_14 hq0 hq hl0 (by push_cast at hlr; exact hlr)

end OddCycleBound.HighDensity
