/-
Hfin dispatcher for m = 61 (GENERATED by hfin_certs.py --gen; do not edit).
-/
import OddCycleBound.HighDensity.Hfin.P061R02
import OddCycleBound.HighDensity.Hfin.P061R03
import OddCycleBound.HighDensity.Hfin.P061R04
import OddCycleBound.HighDensity.Hfin.P061R05
import OddCycleBound.HighDensity.Hfin.P061R06
import OddCycleBound.HighDensity.Hfin.P061R07
import OddCycleBound.HighDensity.Hfin.P061R08
import OddCycleBound.HighDensity.Hfin.P061R09
import OddCycleBound.HighDensity.Hfin.P061R10
import OddCycleBound.HighDensity.Hfin.P061R11
import OddCycleBound.HighDensity.Hfin.P061R12
import OddCycleBound.HighDensity.Hfin.P061R13
import OddCycleBound.HighDensity.Hfin.P061R14
import OddCycleBound.HighDensity.Hfin.P061R15

namespace OddCycleBound.HighDensity

/-- Dispatcher for `m = 61`: all residual-strip pairs `(m,r)`. -/
theorem finKernel_M61 {q l : ℝ} (r : ℕ) (hr2 : 2 ≤ r) (hres : 2*r < 61 - 2*r)
    (hq0 : 0 ≤ q) (hq : q ≤ 1/3) (hl0 : 0 < l) (hlr : l < q + (r : ℝ)/61) :
    0 ≤ diagKernel 61 r q l := by
  have hub : r ≤ 15 := by omega
  interval_cases r
  · exact finKernel_61_2 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_61_3 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_61_4 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_61_5 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_61_6 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_61_7 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_61_8 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_61_9 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_61_10 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_61_11 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_61_12 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_61_13 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_61_14 hq0 hq hl0 (by push_cast at hlr; exact hlr)
  · exact finKernel_61_15 hq0 hq hl0 (by push_cast at hlr; exact hlr)

end OddCycleBound.HighDensity
