/-
Hfin certificate for (m,r) = (9,2) via Horner BP reflection (GENERATED by hfin_certs.py
--gen; do not edit).  Depth-0 Bernstein certificate of the cleared identity
`6561 * (q+2/9)^4 * (r*m^dy) * diagKernel 9 2 = certReal`, checked in-kernel
(`decide +kernel`); nonnegativity of `certReal` is structural, so `0 <= diagKernel 9 2`.
-/
import OddCycleBound.HighDensity.HfinPolyReflect

set_option maxHeartbeats 400000000
set_option maxRecDepth 100000

namespace OddCycleBound.HighDensity

def grid_9_2 : List (List ℕ) := [
  [1650550770, 2894713200, 2312437572, 767217096, 294155874],
  [791492796, 1476159390, 1163777058, 367324146, 46937394],
  [143134776, 285915258, 231485202, 82445526, 11376774],
  [11573604, 24839946, 20824614, 7674426, 1049274],
  [354294, 826686, 747954, 301806, 45684]]

theorem finKernel_9_2 {q l : ℝ} (hq0 : 0 ≤ q) (hq : q ≤ 1/3)
    (hl0 : 0 < l) (hlr : l < q + 2/9) :
    0 ≤ diagKernel 9 2 q l := by
  have hpos : (0:ℝ) ≤ ((9:ℤ):ℝ) * q + ((2:ℤ):ℝ) - ((9:ℤ):ℝ) * l := by
    push_cast; linarith [hlr]
  have hcert : 0 ≤ certReal (9:ℤ) (2:ℤ) 4 4 q l grid_9_2 :=
    certReal_nonneg (9:ℤ) (2:ℤ) 4 4 (by linarith) (by linarith) hl0.le hpos grid_9_2
  have hdata : eqBP (smulBP (6561 : ℤ) (dkClearedBP 9 2))
      (hornerBP (9:ℤ) (2:ℤ) 4 4 grid_9_2) = true := by
    decide +kernel
  have hbridge : bpEval q l (smulBP (6561 : ℤ) (dkClearedBP 9 2))
      = bpEval q l (hornerBP (9:ℤ) (2:ℤ) 4 4 grid_9_2) := eqBP_sound q l _ _ hdata
  rw [eval_smulBP, eval_dkClearedBP 9 2 (by norm_num) (by norm_num) q l,
      eval_hornerBP (9:ℤ) (2:ℤ) 4 4 q l grid_9_2] at hbridge
  have hqt : (0:ℝ) < q + ((2:ℕ):ℝ) / ((9:ℕ):ℝ) := by
    have : (0:ℝ) < ((2:ℕ):ℝ) / ((9:ℕ):ℝ) := by positivity
    linarith [hq0]
  have hL : (0:ℝ) < ((6561:ℤ):ℝ) := by norm_num
  have hA0 : (0:ℝ) < ((2:ℕ):ℝ) * ((9:ℕ):ℝ) ^ (9 - 2 * 2 - 1)
      * (q + ((2:ℕ):ℝ) / ((9:ℕ):ℝ)) ^ (9 - 2 * 2 - 1) := by
    have h2 : (0:ℝ) < ((9:ℕ):ℝ) ^ (9 - 2 * 2 - 1) := by positivity
    have h3 : (0:ℝ) < (q + ((2:ℕ):ℝ) / ((9:ℕ):ℝ)) ^ (9 - 2 * 2 - 1) := pow_pos hqt _
    positivity
  rw [← hbridge] at hcert
  exact (mul_nonneg_iff_of_pos_left hA0).mp ((mul_nonneg_iff_of_pos_left hL).mp hcert)

end OddCycleBound.HighDensity
