/-
Hfin certificate for (m,r) = (11,2) via Horner BP reflection (GENERATED by hfin_certs.py
--gen; do not edit).  Depth-0 Bernstein certificate of the cleared identity
`1291467969 * (q+2/11)^6 * (r*m^dy) * diagKernel 11 2 = certReal`, checked in-kernel
(`decide +kernel`); nonnegativity of `certReal` is structural, so `0 <= diagKernel 11 2`.
-/
import OddCycleBound.HighDensity.HfinPolyReflect

set_option maxHeartbeats 400000000
set_option maxRecDepth 100000

namespace OddCycleBound.HighDensity

def grid_11_2 : List (List ℕ) := [
  [149696578398137364, 459257098320381834, 619149348822369420, 452996857437931620, 192794150634435900, 44047241727587406, 7842518813186376],
  [85413326307924780, 269103405415956606, 368141739460318890, 273126208176366930, 116177551731666810, 25583632056531252, 2394540608582628],
  [20336839093536768, 65867030919316044, 91695506935225248, 69140977986851892, 29802968307849528, 6820041449271600, 646359118773192],
  [2586769014931992, 8622241377093036, 12249885360234852, 9399737428962408, 4107078730419192, 956827253206440, 91663698259848],
  [185418639245268, 636899482613394, 926600716440828, 725805763892352, 322805639549448, 76785902222040, 7559998385742],
  [7103073829500, 25182764416854, 37665232826562, 30250676055798, 13749797088522, 3338779524894, 335962371162],
  [113649181272, 416713664664, 644012027208, 534572074872, 251150659848, 63138434040, 6604379408]]

theorem finKernel_11_2 {q l : ℝ} (hq0 : 0 ≤ q) (hq : q ≤ 1/3)
    (hl0 : 0 < l) (hlr : l < q + 2/11) :
    0 ≤ diagKernel 11 2 q l := by
  have hpos : (0:ℝ) ≤ ((11:ℤ):ℝ) * q + ((2:ℤ):ℝ) - ((11:ℤ):ℝ) * l := by
    push_cast; linarith [hlr]
  have hcert : 0 ≤ certReal (11:ℤ) (2:ℤ) 6 6 q l grid_11_2 :=
    certReal_nonneg (11:ℤ) (2:ℤ) 6 6 (by linarith) (by linarith) hl0.le hpos grid_11_2
  have hdata : eqBP (smulBP (1291467969 : ℤ) (dkClearedBP 11 2))
      (hornerBP (11:ℤ) (2:ℤ) 6 6 grid_11_2) = true := by
    decide +kernel
  have hbridge : bpEval q l (smulBP (1291467969 : ℤ) (dkClearedBP 11 2))
      = bpEval q l (hornerBP (11:ℤ) (2:ℤ) 6 6 grid_11_2) := eqBP_sound q l _ _ hdata
  rw [eval_smulBP, eval_dkClearedBP 11 2 (by norm_num) (by norm_num) q l,
      eval_hornerBP (11:ℤ) (2:ℤ) 6 6 q l grid_11_2] at hbridge
  have hqt : (0:ℝ) < q + ((2:ℕ):ℝ) / ((11:ℕ):ℝ) := by
    have : (0:ℝ) < ((2:ℕ):ℝ) / ((11:ℕ):ℝ) := by positivity
    linarith [hq0]
  have hL : (0:ℝ) < ((1291467969:ℤ):ℝ) := by norm_num
  have hA0 : (0:ℝ) < ((2:ℕ):ℝ) * ((11:ℕ):ℝ) ^ (11 - 2 * 2 - 1)
      * (q + ((2:ℕ):ℝ) / ((11:ℕ):ℝ)) ^ (11 - 2 * 2 - 1) := by
    have h2 : (0:ℝ) < ((11:ℕ):ℝ) ^ (11 - 2 * 2 - 1) := by positivity
    have h3 : (0:ℝ) < (q + ((2:ℕ):ℝ) / ((11:ℕ):ℝ)) ^ (11 - 2 * 2 - 1) := pow_pos hqt _
    positivity
  rw [← hbridge] at hcert
  exact (mul_nonneg_iff_of_pos_left hA0).mp ((mul_nonneg_iff_of_pos_left hL).mp hcert)

end OddCycleBound.HighDensity
