/-
Hfin certificate for (m,r) = (13,3) via Horner BP reflection (GENERATED by hfin_certs.py
--gen; do not edit).  Depth-0 Bernstein certificate of the cleared identity
`1172914587 * (q+3/13)^6 * (r*m^dy) * diagKernel 13 3 = certReal`, checked in-kernel
(`decide +kernel`); nonnegativity of `certReal` is structural, so `0 <= diagKernel 13 3`.
-/
import OddCycleBound.HighDensity.HfinPolyReflect

set_option maxHeartbeats 400000000
set_option maxRecDepth 100000

namespace OddCycleBound.HighDensity

def grid_13_3 : List (List ℕ) := [
  [1607149730501435952, 4566748635466076124, 5846035686167950416, 4070362320226352124, 1722510536343148656, 447852250223937936, 167596420741900488],
  [799141163662007712, 2358053651083406796, 3071760544306032930, 2171688941923582770, 883827578113351560, 175959149355196740, 19103225820504696],
  [166058300866017456, 509614967247282000, 679287268959568074, 491893562614512006, 204766665074505144, 44737216603133652, 4322305980667584],
  [18463334100606018, 59021988620363730, 80851050390778902, 59947529786716338, 25374445462575612, 5689119509055216, 529725529069152],
  [1159053082410834, 3867322247110530, 5474998738244646, 4176712092983274, 1812396134323476, 420471981631728, 40670422332696],
  [38973605896836, 136072167067044, 200357269751340, 158273094369780, 70693734222540, 16837666750476, 1664322357672],
  [548924026716, 2012721431292, 3110569484724, 2581975977516, 1213054330644, 304957792620, 31972782816]]

theorem finKernel_13_3 {q l : ℝ} (hq0 : 0 ≤ q) (hq : q ≤ 1/3)
    (hl0 : 0 < l) (hlr : l < q + 3/13) :
    0 ≤ diagKernel 13 3 q l := by
  have hpos : (0:ℝ) ≤ ((13:ℤ):ℝ) * q + ((3:ℤ):ℝ) - ((13:ℤ):ℝ) * l := by
    push_cast; linarith [hlr]
  have hcert : 0 ≤ certReal (13:ℤ) (3:ℤ) 6 6 q l grid_13_3 :=
    certReal_nonneg (13:ℤ) (3:ℤ) 6 6 (by linarith) (by linarith) hl0.le hpos grid_13_3
  have hdata : eqBP (smulBP (1172914587 : ℤ) (dkClearedBP 13 3))
      (hornerBP (13:ℤ) (3:ℤ) 6 6 grid_13_3) = true := by
    decide +kernel
  have hbridge : bpEval q l (smulBP (1172914587 : ℤ) (dkClearedBP 13 3))
      = bpEval q l (hornerBP (13:ℤ) (3:ℤ) 6 6 grid_13_3) := eqBP_sound q l _ _ hdata
  rw [eval_smulBP, eval_dkClearedBP 13 3 (by norm_num) (by norm_num) q l,
      eval_hornerBP (13:ℤ) (3:ℤ) 6 6 q l grid_13_3] at hbridge
  have hqt : (0:ℝ) < q + ((3:ℕ):ℝ) / ((13:ℕ):ℝ) := by
    have : (0:ℝ) < ((3:ℕ):ℝ) / ((13:ℕ):ℝ) := by positivity
    linarith [hq0]
  have hL : (0:ℝ) < ((1172914587:ℤ):ℝ) := by norm_num
  have hA0 : (0:ℝ) < ((3:ℕ):ℝ) * ((13:ℕ):ℝ) ^ (13 - 2 * 3 - 1)
      * (q + ((3:ℕ):ℝ) / ((13:ℕ):ℝ)) ^ (13 - 2 * 3 - 1) := by
    have h2 : (0:ℝ) < ((13:ℕ):ℝ) ^ (13 - 2 * 3 - 1) := by positivity
    have h3 : (0:ℝ) < (q + ((3:ℕ):ℝ) / ((13:ℕ):ℝ)) ^ (13 - 2 * 3 - 1) := pow_pos hqt _
    positivity
  rw [← hbridge] at hcert
  exact (mul_nonneg_iff_of_pos_left hA0).mp ((mul_nonneg_iff_of_pos_left hL).mp hcert)

end OddCycleBound.HighDensity
